youfull/objects/Action_Items__c.object
<CustomObject>
    <fields>
        <fullName>Default__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Default</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Genealogy_Criteria_Fld__c</fullName>
        <inlineHelpText>Used for markets with Mail Plan enabled</inlineHelpText>
        <label>Genealogy Criteria Fld</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Order_Criteria_Fld__c</fullName>
        <inlineHelpText>Used for Downline based action items for Mail Plan enabled Markets</inlineHelpText>
        <label>Order Criteria Fld</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Rep_Criteria_Fld__c</fullName>
        <inlineHelpText>Used for Markets that are mail plan enabled</inlineHelpText>
        <label>Rep Criteria Fld</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Smry_Criteria_Fld__c</fullName>
        <description>field will be populated in cases where the Summary Record should be used.  Primarily two scenarios:
Current Business (for all Markets)
Orders (for Markets with Mail Plans)
Sales (for Markets with Mail Plans)</description>
        <inlineHelpText>This field will be populated in cases where the Summary Record should be used.  Main scenarios:
- Current Business (for all Markets)
- Orders (for Markets without Mail Plans)
- Sales (for Markets without Mail Plans)</inlineHelpText>
        <label>Smry Criteria Fld</label>
        <length>1000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Zone_Or_Leader__c</fullName>
        <label>Zone Or Leader</label>
        <picklist>
            <picklistValues>
                <fullName>Zone</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Leader</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Action Item</label>
    <nameField>
        <label>Action Items Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Action Items</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

youfull/objects/ALM_Rep_Performance_1__c.object
<CustomObject>
    <fields>
        <fullName>ACCT_NR__c</fullName>
        <label>Account Number</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>AVG_GENRTN_2_UNIT_COMM_PCT__c</fullName>
        <label>G2 Average Unit Commission Rates [%]</label>
        <precision>14</precision>
        <scale>1</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>AVG_GENRTN_3_DISTR_SLS_PCT__c</fullName>
        <description>Average of (award sales within 3rd generation / award sales within 3 generations) over last N campaigns</description>
        <label>G3 Average Sales Distribution [%]</label>
        <precision>14</precision>
        <scale>1</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>AVG_GENRTN_3_UNIT_COMM_PCT__c</fullName>
        <label>G3 Average Unit Commission Rates [%]</label>
        <precision>14</precision>
        <scale>1</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>FLD_SLS_CMPGN_NR__c</fullName>
        <label>Campaign</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>MailPlan_Order_Oppty__c</fullName>
        <description>Lookup to corresponding record of MailPlan_Order_Oppty</description>
        <inlineHelpText>Lookup to corresponding record of MailPlan_Order_Oppty</inlineHelpText>
        <label>MailPlan_Order_Oppty</label>
        <referenceTo>MailPlan_Order_Oppty__c</referenceTo>
        <relationshipLabel>ALM Rep Performance</relationshipLabel>
        <relationshipName>ALM_Rep_Performance</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>OPERTNL_CMPGN_NR__c</fullName>
        <label>Campaign</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <label>ALM Rep Performance</label>
    <nameField>
        <label>ALM Rep Performance Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>ALM Rep Performance</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

youfull/objects/MailPlan_Order_Oppty__c.object
<CustomObject>
    <fields>
        <fullName>CMPGN_NR__c</fullName>
        <label>CMPGN_NR</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Market__c</fullName>
        <label>Market</label>
        <referenceTo>Market__c</referenceTo>
        <relationshipLabel>MailPlan_Order_Opptys</relationshipLabel>
        <relationshipName>MailPlan_Order_Opptys</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>MailPlan_Order_Oppty</label>
    <nameField>
        <displayFormat>MPLN-{000000}</displayFormat>
        <label>Mail Plan Order Oppty Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>MailPlan_Order_Opptys</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

youfull/objects/Market__c.object
<CustomObject>
    <fields>
        <fullName>ALM_Rep_Indicator__c</fullName>
        <label>ALM Rep Indicator</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CMPGN_NR__c</fullName>
        <label>CMPGN_NR</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Market_Id__c</fullName>
        <externalId>true</externalId>
        <label>MRKT_ID</label>
        <length>15</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>NEXT_1_CMPGN_NR__c</fullName>
        <label>NEXT_1_CMPGN_NR</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <label>Market</label>
    <nameField>
        <label>Market Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Markets</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

youfull/objects/Market_Action_Items__c.object
<CustomObject>
    <fields>
        <fullName>Action_Item__c</fullName>
        <label>Action Item</label>
        <referenceTo>Action_Items__c</referenceTo>
        <relationshipLabel>Market Action Items</relationshipLabel>
        <relationshipName>Market_Action_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Campaign_Stage__c</fullName>
        <label>Campaign Stage</label>
        <precision>6</precision>
        <scale>1</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Default__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Default</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Filter_Param__c</fullName>
        <label>Filter Param</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Market__c</fullName>
        <label>Market</label>
        <referenceTo>Market__c</referenceTo>
        <relationshipLabel>Market Action Items</relationshipLabel>
        <relationshipName>Market_Action_Items</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Priority__c</fullName>
        <label>Priority</label>
        <picklist>
            <picklistValues>
                <fullName>1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>3</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>4</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>5</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>6</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>7</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>8</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>9</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>10</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>11</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>12</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>13</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Report__c</fullName>
        <label>Report</label>
        <referenceTo>Report_Config__c</referenceTo>
        <relationshipLabel>Market Action Items</relationshipLabel>
        <relationshipName>Market_Action_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Threshold__c</fullName>
        <label>Threshold</label>
        <precision>6</precision>
        <scale>1</scale>
        <type>Number</type>
    </fields>
    <label>Market Action Item</label>
    <nameField>
        <displayFormat>MAI-{000000}</displayFormat>
        <label>Market Action Items Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Market Action Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

youfull/objects/Report_Config__c.object
<CustomObject>
    <fields>
        <fullName>Market__c</fullName>
        <label>Market</label>
        <referenceTo>Market__c</referenceTo>
        <relationshipName>Market_Drilldown_Configs</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Report_Id__c</fullName>
        <description>Unique Id for the drilldown</description>
        <externalId>true</externalId>
        <inlineHelpText>Unique Code that will be passed from the pages.</inlineHelpText>
        <label>Report Id</label>
        <length>7</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Report_Type__c</fullName>
        <label>Report Type</label>
        <picklist>
            <picklistValues>
                <fullName>Inactive</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Inherited</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Orders_Not_Submitted</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Orders_on_Hold</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Orders_below_Minimum</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Orders_at_Minimum</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending_Orders</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Total_Orders_received</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Return_Orders</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Achieved_Minimum_Order</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Current_Balance_Past_Due_Status</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Personal_Sales_Qualifier</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Additions_Reinstatements</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Candidate_Development</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Development_LOA_1_6</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Downline_Detail</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PATD_Certified</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ranking_and_Recognition</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Title_Change</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Birthday_Anniversaries</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Balance_Past_Due</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Personal_Sales_Qual</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Returns</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Brochures_Not_Purchased</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>1st_Order_Award_Sales</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AI_Orders_Not_Submitted</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AI_Orders_on_Hold</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AI_Orders_below_Minimum</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AI_Orders_at_Minimum</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AI_Pending_Orders</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Report_URL__c</fullName>
        <label>Report URL</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Report Config</label>
    <nameField>
        <label>Report Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Report Configs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

youfull/classes/Test_ActionItemsController.cls
/***************************************************************************
 Name          : Test_ActionItemsController 
 Modified By   : Parul Gupta (JDC)
 Description   : Test class for ActionItemsController
 Modified Date : Oct 29, 2013                
****************************************************************************/
@isTest
public class Test_ActionItemsController {
  
    public static String mktIdKey = 'XX';
    
    //---------------------------------------------------------------------------
    // Method Name  : testActionItems
    // Description  : Method for Test Coverage for ActionItemsController
    //---------------------------------------------------------------------------
    static testMethod void testActionItems(){
    
        // Create Basic test data
        User ldrUsr = TestDataHelper.createUser(mktIdKey, 'XZ1', 'Avon Leader', true); 
        ALM_Global_Settings__c setting = TestDataHelper.createALMGlobalSetting(true);     
        Account account = TestDataHelper.createAccount('Test Account', 'USD', true);   
        Contact ldrContact = TestDataHelper.createContact(mktIdKey, account.Id, true);        
        Market__c market = TestDataHelper.createMarket(mktIdKey, true);
        
        // Creating Market Action Items        
        List <Action_Items__c> actItems = TestDataHelper.createActionItems(true);
        List<Market_Action_Items__c> testItmLst = TestDataHelper.createMarketActionItems(market.id, actItems, true);
        
        // Create market key list     
        List<String> mktKeyLst = new List<String>();
        mktKeyLst.add(market.Market_Id__c + market.CMPGN_NR__c + ldrUsr.ACCT_NR__c);
        mktKeyLst.add(market.Market_Id__c + market.NEXT_1_CMPGN_NR__c + ldrUsr.ACCT_NR__c);
        
        // Create ALM_Rep_Indicator__c records
        TestDataHelper.createMulRepPerformance(mktKeyLst, market.Market_Id__c, ldrUsr.Id, 
                                                market, ldrContact.id, true);
        
        
        List<ALM_Rep_Performance_1__c> ppList = [SELECT Id, MailPlan_Order_Oppty__c,AVG_GENRTN_3_UNIT_COMM_PCT__c, 
                                                AVG_GENRTN_3_DISTR_SLS_PCT__c, 
                                                AVG_GENRTN_2_UNIT_COMM_PCT__c,OPERTNL_CMPGN_NR__c,
                                                FLD_SLS_CMPGN_NR__c 
                                                FROM ALM_Rep_Performance_1__c
                                                WHERE ACCT_NR__c =:ldrUsr.ACCT_NR__c];
        
        List<Market_Action_Items__c> mktActItems2 = [Select  Action_Item__r.Zone_Or_Leader__c, Threshold__c, Filter_Param__c,
                        Action_Item__r.Smry_Criteria_Fld__c, Report__r.Report_Id__c,Report__r.Report_Type__c, Report__r.Report_URL__c,
                        Action_Item__r.Order_Criteria_Fld__c,Action_Item__r.Rep_Criteria_Fld__c,
                        Action_Item__r.Genealogy_Criteria_Fld__c,Action_Item__r.Default__c,
                        Priority__c, Market__c, Campaign_Stage__c,
                        Action_Item__r.Action_Item_Type__c,Action_Item__r.Category__c,
                        Action_Item__r.Subject_Area__c,Action_Item__r.Datatype__c,Campaign__c,Default__c  
                        From   Market_Action_Items__c
                        where Market__c=:market.Id
                        and  Action_Item__r.Zone_Or_Leader__c = 'Leader'
                        order by Action_Item__r.Subject_Area__c,Priority__c asc];
        
        //Test case for markets do not have Mailplan
        System.runAs(ldrUsr){
            ActionItemsController objController = new ActionItemsController();
            objController.mkt_actionitem=mktActItems2;
            objController.combObjLst=ppList;
            objController.itemsToDisplay=2;
            objController.userProfile=null;
            objController.isSideBar='1';
            objController.getInitialize(); 
            objController.isSideBar='4'; 
            objController.getInitialize();
            objController.getcoachActionItems();
            objController.getmngNbrActionItems();
            objController.getmngPrsRepActionItems();
            System.assert(objController.mkt_actionitem.size() == 8);
        }
        
        //Test case for markets enables Mailplan
        market.Mail_Plan_Enabled__c=true;
        update market;
       
        // Create MailPlan_Order_Oppty__c records
        List<MailPlan_Order_Oppty__c> mplst = new List<MailPlan_Order_Oppty__c>();
        Date currDate = System.today().addDays(1);
        Date nextCDate= currDate.addDays(10);
        MailPlan_Order_Oppty__c mplan;
        for (Integer i=0;i<5;i++) {
            mplan = TestDataHelper.createMPOrderOpp(market.Id, '4', 'N', currDate.addDays(1+10), 
                                                    'M'+(i+1), 'XZ1', 'M'+i, false);            
            mplst.add(mplan);           
            mplan = TestDataHelper.createMPOrderOpp(market.Id, '4', 'N', nextCDate.addDays(1+10), 
                                                    'M'+(i+1), 'XZ1', 'M'+i, false);
            mplst.add(mplan);  
        }
        insert mplst;
        
        List<MailPlan_Order_Oppty__c> tmpMp=new List<MailPlan_Order_Oppty__c>();
        for(MailPlan_Order_Oppty__c mp:mplst){
            for(ALM_Rep_Performance_1__c ar:ppList){
                if(ar.OPERTNL_CMPGN_NR__c.contains(mp.CMPGN_NR__c)){
                    ar.MailPlan_Order_Oppty__c=mp.Id;
                    tmpMp.add(mp);
                }
            }                           
        }
        update ppList;
        
        //Testing for Current Campaign Scenarios
        System.runAs(ldrUsr){
            ActionItemsController objController = new ActionItemsController();
            objController.mkt_actionitem=mktActItems2;
            objController.cmpTxt='Current';
            objController.combObjLst=ppList;
            objController.market=market;
            objController.itemsToDisplay=2;
            objController.isSideBar='1';
            objController.getInitialize();  
            objController.getcoachActionItems();
            objController.getmngNbrActionItems();
            objController.getmngPrsRepActionItems();
            system.debug('objController.mkt_actionitem.size()2'+objController.mkt_actionitem.size());
            System.assert(objController.mkt_actionitem.size() == 8);
        }
        
        //Testing for Next Campaign Scenarios
        System.runAs(ldrUsr){
            ActionItemsController objController = new ActionItemsController();
            objController.mkt_actionitem=mktActItems2;
            objController.cmpTxt='Next';
            objController.combObjLst=ppList;
            objController.market=market;
            objController.itemsToDisplay=2;
            objController.isSideBar='1';
            objController.getInitialize();  
            objController.getcoachNCActionItems();
            objController.getmngNbrNCActionItems();
            objController.getmngPrsRepNCActionItems();
            system.debug('objController.mkt_actionitem.size()3'+objController.mkt_actionitem.size());
            System.assert(objController.mkt_actionitem.size() == 8);
        }
       
    }

}