youfull/objects/Action_Alert__c.object
<CustomObject>
    <label>Action Alert</label>
    <nameField>
        <label>Action Alert Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Action Alert</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

youfull/objects/Ineligibility_Reason__c.object
<CustomObject>
    <description>Stores mapping of an Ineligibility Reason code to its description for a given Market in given language</description>
    <fields>
        <fullName>Ineligibility_Code__c</fullName>
        <label>Ineligibility Code</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Ineligibility_Reason__c</fullName>
        <label>Ineligibility Reason</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>LANG_CD__c</fullName>
        <description>Language Code</description>
        <inlineHelpText>Language Code</inlineHelpText>
        <label>LANG_CD</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Market__c</fullName>
        <description>Master-detail lookup to Market</description>
        <inlineHelpText>Master-detail lookup to Market</inlineHelpText>
        <label>Market</label>
        <referenceTo>Market__c</referenceTo>
        <relationshipLabel>Ineligibility Reasons</relationshipLabel>
        <relationshipName>Ineligibility_Reasons</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Order__c</fullName>
        <description>Relative order in which the reason will be displayed to users</description>
        <inlineHelpText>Relative order in which the reason will be displayed to users</inlineHelpText>
        <label>Order</label>
        <precision>6</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Ineligibility Reason</label>
    <nameField>
        <displayFormat>IR-{0}</displayFormat>
        <label>Ineligibility Reason Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Ineligibility Reasons</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

youfull/objects/Market__c.object
<CustomObject>
    <fields>
        <fullName>Action_Alert_Enabled__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Action Alert Enabled</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Action_Alerts__c</fullName>
        <label>Action Alerts</label>
        <picklist>
            <picklistValues>
                <fullName>Rising Stars</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Title at Risk</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Title Lost</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Title Promoted</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Balance due</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Featured Product no activity</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>New and In-Progress Leads</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Orders Not submitted</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Orders Over Minimum to earn</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Orders Received Billed and Invoiced</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Orders Received In Process</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Orders under minimum to earn</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Past Due</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending Orders</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Reps with overdue</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Return sales</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Team sales above minimum</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Team sales below minimum</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Avon Anniversary</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Birthday</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Downline PSQ not achieved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>G1 Appointments</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>G1 Candidates</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Inactive</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Inherited</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>LOA 0-6</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>New Repr LOA 0</fullName>
            </picklistValues>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <fields>
        <fullName>Market_Administrator__c</fullName>
        <label>Market Administrator</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Markets</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Market</label>
    <nameField>
        <label>Market Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Markets</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

youfull/objects/Sales_Organization__c.object
<CustomObject>
    <fields>
        <fullName>Market__c</fullName>
        <label>Market</label>
        <referenceTo>Market__c</referenceTo>
        <relationshipLabel>Sales Organizations</relationshipLabel>
        <relationshipName>Sales_Organizations</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Sales Organization</label>
    <nameField>
        <displayFormat>SO-{000000}</displayFormat>
        <label>Sales Org Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sales Organizations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

youfull/objects/User_Sales_Org_Hierarchy__c.object
<CustomObject>
    <fields>
        <fullName>Market__c</fullName>
        <label>Market</label>
        <referenceTo>Market__c</referenceTo>
        <relationshipLabel>User_Sales_Org_Hierarchies</relationshipLabel>
        <relationshipName>User_Sales_Org_Hierarchy</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>SLS_ORG_CD__c</fullName>
        <label>SLS_ORG_CD</label>
        <length>35</length>
        <type>Text</type>
    </fields>
    <label>User_Sales_Org_Hierarchy</label>
    <nameField>
        <displayFormat>USLS-{000000}</displayFormat>
        <label>User Sales Org Hierarchy Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>User_Sales_Org_Hierarchies</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

youfull/classes/Test_UpdateUserPrefController.cls
/***************************************************************************
 Name         : Test_UpdateUserPrefController 
 Created By   : Parul Gupta (JDC)
 Description  : Test class for UpdateUserPrefController
 Created Date : Oct 28, 2013                
****************************************************************************/
@isTest
private class Test_UpdateUserPrefController {

	//---------------------------------------------------------------------------
    // Method Name  : testUpdatePrefController
    // Description  : Method for Test Coverage of Class : UpdatePrefController
    //---------------------------------------------------------------------------
    public static testmethod void testUpdatePrefController(){
        // Create test data
        String acctNbr = '123456';
        User ldrUsr = TestDataHelper.createUser('123456', 'XZ1', 'Avon Leader', true);	                   
        User mktAdmin = TestDataHelper.createUser('MKT_ADMIN', 'XZ1', 'Avon Market Administrator', true);         
        Market__c mrkt = TestDataHelper.createMarket('123456', true);          
        mrkt.Market_Administrator__c = mktAdmin.Id;       
        mrkt.OwnerId = ldrUsr.Id;
     	update mrkt;      
        
        // Test for controller functionality
        UpdateUserPrefController ctlr = new UpdateUserPrefController();
      	ctlr.testMode =true; 
        System.runAs(ldrUsr){
        	ctlr.init();
          	ctlr.userRec.LanguageLocaleKey='fr';
          	ctlr.updatePreferences();
          	System.assert(ctlr.isError==true);
        }      
    } 
    
   /* public static testmethod void testUpdatePrefController(){
        TestDataHelper testData = new TestDataHelper();
        testData.createEmailTemplate();
        String acctNbr = '123456';
        User usr = testData.createZoneUser(acctNbr);
        User mktAdmin = testData.createMarketAdminUser('MKT_ADMIN');
        System.debug('>>>>>>>>>>>>>>>>>>>>>> mktAdmin User:'+mktAdmin);
        testData.market.Market_Administrator__c = mktAdmin.Id;
        update testData.market;
        List<User_Sales_Org_Hierarchy__c> usrHierarchy = testData.createUsrSlsOrgHrchy(usr,'XZ1','Z');
        testData.createUsrSlsOrgHrchy(usr,'XZ2','Z');
        List<Sales_Organization__c> slsOrgs = testData.createSalesOrgs();
        
        UpdateUserPrefController ctlr = new UpdateUserPrefController();
        ctlr.testMode =true; 
        System.runAs(usr){
            System.assert(ctlr.getSlsOrgSize()==0);
            ctlr.init();
            System.assert(ctlr.getAllowedSlsOrgs().size()==2);
            System.debug('>>>>>>>>>>> SALES ORG DATA ZONE:'+ctlr.allowedSlsOrgs);
            ctlr.selOrgCdId = usrHierarchy[0].SLS_ORG_CD__c;
            ctlr.updatePreferences();
            ctlr.selOrgCdId = usrHierarchy[0].SLS_ORG_CD__c;
            ctlr.userRec.LanguageLocaleKey='en_US';
            ctlr.userRec.UserPermissionsMobileUser=true;
            ctlr.updatePreferences();
            System.assert(ctlr.isError==false);
            ctlr.userRec.LanguageLocaleKey='fr';
            ctlr.selOrgCdId = usrHierarchy[0].SLS_ORG_CD__c;
            ctlr.updatePreferences();
            System.assert(ctlr.isError==true);
        }
    }

    
    public static testmethod void test2SalesLeader(){
        TestDataHelper testData = new TestDataHelper();
        testData.createEmailTemplate();
        String acctNbr = '123456';
        User usr = testData.createZoneUser(acctNbr);
        User mktAdmin = testData.createMarketAdminUser('MKT_ADMIN');
        System.debug('>>>>>>>>>>>>>>>>>>>>>> mktAdmin User:'+mktAdmin);
        testData.market.Market_Administrator__c = mktAdmin.Id;
        update testData.market;
        List<User_Sales_Org_Hierarchy__c> usrHierarchy = testData.createUsrSlsOrgHrchy(usr,'XZ1','Z');
        testData.createUsrSlsOrgHrchy(usr,'XZ2','Z');
        List<Sales_Organization__c> slsOrgs = testData.createSalesOrgs();
        
        UpdateUserPrefController ctlr = new UpdateUserPrefController();
        ctlr.testMode =true; 
        System.runAs(usr){
            System.assert(ctlr.getSlsOrgSize()==0);
            ctlr.init();
            System.assert(ctlr.getAllowedSlsOrgs().size()==2);
            System.debug('>>>>>>>>>>> SALES ORG DATA ZONE:'+ctlr.allowedSlsOrgs);
            ctlr.selOrgCdId = usrHierarchy[0].SLS_ORG_CD__c;
            ctlr.updatePreferences();
            System.assert(ctlr.isError==false);
            ctlr.userRec.LanguageLocaleKey='fr';
            ctlr.selOrgCdId = usrHierarchy[0].SLS_ORG_CD__c;
            ctlr.updatePreferences();
            System.assert(ctlr.isError==true);
        }
        System.runAs(mktAdmin){
            List<Task> mobileTask = [select Id,Subject from Task where OwnerId=:mktAdmin.Id];
            //System.debug('>>>>>>>>>>>>>> TOTAL TASKS RETURNED: '+mobileTask);
            //system.assert(mobileTask.size()==1);
        }
        usr = testData.createDivUser('D'+acctNbr);
        usr.DFALT_ZONE_CD__c ='All';
        update usr;
        //usrHierarchy = testData.createUsrSlsOrgHrchy(usr,'D1','D');
        ctlr = new UpdateUserPrefController();
        System.runAs(usr){
            ctlr.init();
            System.assert(ctlr.getAllowedSlsOrgs().size()==1);
            System.assert(ctlr.getSlsOrgSize()==1);
            ctlr.selOrgCdId = 'All';
            ctlr.updatePreferences();
            User tempUsr = [select DFALT_DIV_NM__c,DFALT_ZONE_CD__c 
                            from User
                            where Id=:usr.Id];
            System.assert(tempUsr.DFALT_ZONE_CD__c==null);  
            ctlr.selOrgCdId =   'XZ1';
            ctlr.updatePreferences();
            tempUsr = [select DFALT_DIV_NM__c,DFALT_ZONE_CD__c 
                            from User
                            where Id=:usr.Id];
            System.assert(tempUsr.DFALT_ZONE_CD__c=='XZ1'); 
        }

        ctlr = new UpdateUserPrefController();
        usr = testData.createLeaderUser('L'+acctNbr);
        System.runAs(usr){
            ctlr.init();
            System.assert(ctlr.getAllowedSlsOrgs()==null);
        }
        
    }
    
    public static testmethod void testZoneManager(){
        TestDataHelper testData = new TestDataHelper();
        testData.createEmailTemplate();
        String acctNbr = '123456';
        User usr = testData.createZoneUser(acctNbr);
        User mktAdmin = testData.createMarketAdminUser('MKT_ADMIN');
        System.debug('>>>>>>>>>>>>>>>>>>>>>> mktAdmin User:'+mktAdmin);
        testData.market.Market_Administrator__c = mktAdmin.Id;

        UpdateUserPrefController ctlr = new UpdateUserPrefController();
        ctlr.testMode =true; 
        
        update testData.market;
        List<User_Sales_Org_Hierarchy__c> usrHierarchy = testData.createUsrSlsOrgHrchy(usr,'XZ1','Z');
        testData.createUsrSlsOrgHrchy(usr,'XZ2','Z');
        List<Sales_Organization__c> slsOrgs = testData.createSalesOrgs();
        
        usr = testData.createDivUser('D'+acctNbr);
        usr.DFALT_ZONE_CD__c ='All';
        update usr;
        //usrHierarchy = testData.createUsrSlsOrgHrchy(usr,'D1','D');
        ctlr = new UpdateUserPrefController();
        System.runAs(usr){
            ctlr.init();
            System.assert(ctlr.getAllowedSlsOrgs().size()==1);
            System.assert(ctlr.getSlsOrgSize()==1);
            ctlr.selOrgCdId = 'All';
            ctlr.updatePreferences();
            User tempUsr = [select DFALT_DIV_NM__c,DFALT_ZONE_CD__c 
                            from User
                            where Id=:usr.Id];
            System.assert(tempUsr.DFALT_ZONE_CD__c==null);  
            ctlr.selOrgCdId =   'XZ1';
            ctlr.updatePreferences();
            tempUsr = [select DFALT_DIV_NM__c,DFALT_ZONE_CD__c 
                            from User
                            where Id=:usr.Id];
            System.assert(tempUsr.DFALT_ZONE_CD__c=='XZ1'); 
        }

        ctlr = new UpdateUserPrefController();
        usr = testData.createLeaderUser('L'+acctNbr);
        System.runAs(usr){
            ctlr.init();
            System.assert(ctlr.getAllowedSlsOrgs()==null);
        }
        
    }*/
    
    //---------------------------------------------------------------------------
    // Method Name  : testActionAlerts
    // Description  : Method for Test Coverage of Class : UpdatePrefController
    //---------------------------------------------------------------------------
    public static testmethod void testActionAlerts(){
    	String acctNbr = '123456';
        User usr = TestDataHelper.createUser('123456', 'XZ1', 'Avon Leader', true);	                         
        Market__c mrkt = TestDataHelper.createMarket('123456', true);          
       
  
        mrkt.Action_Alert_Enabled__c=true;
        mrkt.Action_Alerts__c='Orders Not submitted;Title Lost;';        
        mrkt.OwnerId = usr.Id;
        update mrkt;
       
        //Create Ineligibility Reason Code
       /* List<Ineligibility_Reason__c> testRnLst= new List<Ineligibility_Reason__c>();
        testRnLst.add(new Ineligibility_Reason__c(LANG_CD__c='en_US',Ineligibility_Code__c='OOO',Ineligibility_Reason__c='Out Of Office',Market__c=testData.market.id,Order__c=1));
        testRnLst.add(new Ineligibility_Reason__c(LANG_CD__c='en_US',Ineligibility_Code__c='ZMO',Ineligibility_Reason__c='Zone Manager Override',Market__c=testData.market.id,Order__c=2));
        testRnLst.add(new Ineligibility_Reason__c(LANG_CD__c='en_US',Ineligibility_Code__c='SO',Ineligibility_Reason__c='System Override',Market__c=testData.market.id,Order__c=3));
        testRnLst.add(new Ineligibility_Reason__c(LANG_CD__c='en_US',Ineligibility_Code__c='OI',Ineligibility_Reason__c='Opt In',Market__c=testData.market.id,Order__c=4));
        testRnLst.add(new Ineligibility_Reason__c(LANG_CD__c='en_US',Ineligibility_Code__c='SFA',Ineligibility_Reason__c='Salesforce Active',Market__c=testData.market.id,Order__c=5));
        insert testRnLst;*/
        UpdateUserPrefController ctlr = new UpdateUserPrefController();
        ctlr.testMode =true; 
        System.runAs(usr){
            ctlr.init();
           /* System.assert(usr.Is_Eligible__c==false);
            System.assert(ctlr.getOOOMsg().size()==2);
            System.assert(ctlr.getOIMsg().size()==2);
            System.assert(ctlr.getOOOMsg().size()==2);*/
            System.assert(ctlr.getAllowedActionAlerts().size()==3);
            System.assert(ctlr.getAllowedFrequencies().size()==10);
            ctlr.userRec.LanguageLocaleKey='en_US';
           // ctlr.userRec.Action_Alert_Enabled__c=true;
            ctlr.aAlertEnabled=true;
            ctlr.updatePreferences();
            System.assert(ctlr.actionAlertError==true);
            ctlr.userRec.Action_Alert_1__c='Orders Not submitted';
            ctlr.userRec.Action_Alert_Frequency__c=null;
            ctlr.updatePreferences();
            System.assert(ctlr.actionAlertError==true);
            ctlr.userRec.Action_Alert_1__c='Orders Not submitted';
            ctlr.userRec.Action_Alert_Frequency__c='Daily';
            ctlr.updatePreferences();
            System.assert(ctlr.actionAlertError==false);
            List<Action_Alert__c> usrAlerts = [select Id from Action_Alert__c where OwnerId=:usr.Id];
            System.assert(usrAlerts.size()==1);
            ctlr.userRec.Action_Alert_1__c='Rising Stars';
            ctlr.userRec.Action_Alert_2__c='Orders Not submitted';
            ctlr.userRec.Action_Alert_3__c='Title Lost';
            ctlr.updatePreferences();
            System.assert(ctlr.actionAlertError==false);
            usrAlerts = [select Id from Action_Alert__c where OwnerId=:usr.Id];
            System.assert(usrAlerts.size()==3);
            ctlr.sendTestActionAlert();
            System.assert(ctlr.actionAlertError==false);
           // ctlr.userRec.SMS_Address__c='test@avon.com';
           System.debug('My test User >>>'+ctlr.userRec);
            ctlr.userRec.Action_Alert_1__c='Orders Not submitted';
            ctlr.userRec.Action_Alert_2__c='Orders Not submitted';
            ctlr.updatePreferences();
            ctlr.callRepDetails();
            System.assert(ctlr.bDuplicate==true);
            //Snehashis added for ALM+
           /* ctlr.userRec.Opt_In__c=true;
            ctlr.userRec.Lead_Opt_in_Terms__c=false;
            ctlr.updatePreferences();
            System.assert(ctlr.isLeadOptinError==true);
            System.assert(ctlr.userRec.Out_of_Office__c==false);*/
        }
    }
 
}