youfull/objects/Action_Alert__c.object
<CustomObject>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>Orders Not submitted</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Orders / Sales under minimum</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending Orders</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Orders on Hold</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Orders Received</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Downline Personal Sales Qualifier</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Past Due / Balance</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Return Sales</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Minimum Order Size</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Title Change</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Additions / Reinstatements / Removals</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Development Report LOA 1-6</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Candidate Development</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>P.A.T.D. Certified</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ranking &amp;amp; Recognition</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Inherited</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Inactive</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Birthday / Avon Anniversary</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Action Alert</label>
    <nameField>
        <label>Action Alert Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Action Alert</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

youfull/objects/ALM_Rep_Performance_1__c.object
<CustomObject>
    <fields>
        <fullName>GRP_RISNG_STAR_CNT__c</fullName>
        <label>Team Rising Star</label>
        <precision>12</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>MRKT_ID__c</fullName>
        <externalId>true</externalId>
        <label>Market Id</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <label>ALM Rep Performance</label>
    <nameField>
        <label>ALM Rep Performance Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>ALM Rep Performance</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

youfull/objects/Market__c.object
<CustomObject>
    <fields>
        <fullName>ALM_Rep_Indicator__c</fullName>
        <label>ALM Rep Indicator</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Action_Alert_Enabled__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Action Alert Enabled</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>CMPGN_NR__c</fullName>
        <label>CMPGN_NR</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Mail_Plan_Enabled__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Mail Plan Enabled</label>
        <type>Checkbox</type>
    </fields>
    <label>Market</label>
    <nameField>
        <label>Market Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Markets</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

youfull/classes/Test_ActionAlertBatch.cls
/***************************************************************************
 Name         : Test_ActionAlertBatch 
 Created By   : Barkha Jain (JDC)
 Description  : Test class for ActionAlertBatch
 Created Date : Oct. 24, 2013                
****************************************************************************/
@isTest
private class Test_ActionAlertBatch {
	
	//----------------------------------------------------------------------------
    // Method Name  : testActionAlertBatch
    // Description  : Method for Test Coverage of Class : ActionAlertBatch
    //----------------------------------------------------------------------------
	public static testmethod void testActionAlertBatch(){
		//create custom setting
		TestDataHelper.createALMGlobalSetting(true);
		
		Profile profile = [Select Id, Name from Profile where Name Like '%Avon Leader%' limit 1];
      	//create test user
      	User user = TestDataHelper.createUser('1', profile.Id, false);
      	user.Action_Alert_Enabled__c = true;
      	user.Action_Alert_Time__c = system.now().hour();
      	user.MRKT_ID__c = '1234';
      	user.SMS_Address__c = 'test@avon.com';
      	user.Action_Alert_1__c = 'Orders Not submitted';
        user.Action_Alert_Frequency__c = 'Daily';
        user.Action_Alert_View__c = 'Selling Month';
        user.MRKT_ID_ACCT_NR_KEY__c = '1234';
      	insert user;
		
		//create test market
		Market__c mrkt = TestDataHelper.createMarket('test market', '1234', false);
        mrkt.ALM_Rep_Indicator__c = 'ALM_Rep_Performance_1__c';
        mrkt.Mail_Plan_Enabled__c = true;
        mrkt.CMPGN_NR__c = '1234567';
        insert mrkt;
        
        //create test account
        Account acc = TestDataHelper.createAccount('test', 'USD', true);
        //create test contact
        Contact con = TestDataHelper.createContact('1234', acc.Id, true);
        
        System.runAs(user){
	        TestDataHelper.createActionItem('Item 1', 'Downline', 'Leader', 'Rising Stars', 'Coaching Others', 'GRP_RISNG_STAR_CNT__c', 'Number', true);
	        TestDataHelper.createRepPerformance(con.Id, mrkt, '1234', true);
	        
	        Test.startTest();
	        ActionAlertBatch alertBatch = new ActionAlertBatch();
	        Database.executeBatch(alertBatch, 200);
	        Test.stopTest();
        }
        
        //verify result
        List<Action_Alert__c> alerts = [select Id,Type__c from Action_Alert__c where OwnerId =:user.Id];
        if(alerts.size() > 0) {
            System.assert(alerts.size() == 1);
            System.assert(alerts[0].Type__c == 'Orders Not submitted');
        }
    }
}