youfull/objects/ALM_Global_Settings__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <customSettingsVisibility>Protected</customSettingsVisibility>
    <description>Holds global settings that apply across the entire application.</description>
    <label>ALM Global Settings</label>
</CustomObject>

youfull/objects/ALM_Rep_Performance_1__c.object
<CustomObject>
    <fields>
        <fullName>ACCT_NR__c</fullName>
        <label>Account Number</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>MRKT_ID__c</fullName>
        <externalId>true</externalId>
        <label>Market Id</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>OPERTNL_CMPGN_NR__c</fullName>
        <label>Campaign</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <label>ALM Rep Performance</label>
    <nameField>
        <label>ALM Rep Performance Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>ALM Rep Performance</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

youfull/objects/DownloadAll_GenIndex__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <customSettingsVisibility>Public</customSettingsVisibility>
    <description>The hierarchical custom setting to store the genealogy level of the logged in or the currently impersonating user.</description>
    <label>DownloadAll Gen Level</label>
</CustomObject>

youfull/objects/Market__c.object
<CustomObject>
    <fields>
        <fullName>CMPGN_NR__c</fullName>
        <label>CMPGN_NR</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <label>Market</label>
    <nameField>
        <label>Market Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Markets</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

youfull/classes/Test_DownloadAll_PrepData.cls
/***************************************************************************
 Name         : Test_DownloadAll_PrepData
 Created By   : Saurabh Gupta (JDC)
 Description  : Test class for DownloadAll_PrepData
 Created Date : Nov. 07, 2013                
****************************************************************************/

@isTest
private class Test_DownloadAll_PrepData {
	//----------------------------------------------------------------------------
    // Method Name  : testDownloadAll_PrepData
    // Description  : Method for Test Coverage of Class : DownloadAll_PrepData
    //----------------------------------------------------------------------------  
    public static testmethod void testDownloadAll_PrepData() {
    	
    	String mktIdKey = 'TESTDOWN';
    	Market__c mrkt;
    	
    	//Create ALM_Global_Settings__c
        ALM_Global_Settings__c almGlobal = TestDataHelper.createALMGlobalSetting(true);
        
        //Create and Insert Object : User
        List <User> usrList = new List <User>();
        
        User testUsr = TestDataHelper.createUser(mktIdKey, 'XZ1', 'Avon Leader', false);
        testUsr.MRKT_ID__c = mktIdKey;
        testUsr.LDRSHP_TITL_LVL_NBR__c = '2';
        usrList.add(testUsr);
        
        insert usrList;
        
        System.runAs(testUsr) {
            //Create and Insert Object : Market
            mrkt = TestDataHelper.createMarket(mktIdKey, false);
            mrkt.OwnerId = testUsr.Id;
            insert mrkt;
        }
    	
    	//Create and Insert Object : DownloadAll_GenIndex__c
    	DownloadAll_GenIndex__c downloadAllGen = TestDataHelper.createDownloadAllGenIndex(mktIdKey, mrkt.CMPGN_NR__c, true);
    	
    	//Create Object: Account
        Account acct = TestDataHelper.createAccount('Test Acct Down', 'USD', true);
    	
    	Contact con = TestDataHelper.createContact(mktIdKey, String.valueOf(acct.Id), true);
    	
    	//Create and Insert Object : ALM_Rep_Performance_1__c
    	ALM_Rep_Performance_1__c almRep = TestDataHelper.createRepPerformance(con.Id, mrkt, mktIdKey, false);
        almRep.OPERTNL_CMPGN_NR__c = mrkt.CMPGN_NR__c;
        almRep.MRKT_ID__c = mktIdKey;
        almRep.ACCT_NR__c = mktIdKey;
        almRep.Name = '1';
        insert almRep; 
    	
    	PageReference pageRef = Page.DownloadAll_PrepData;
        pageRef.getParameters().put('acctKey', mktIdKey);
        Test.setCurrentPageReference(pageRef);
    	
    	Test.startTest();
    	DownloadAll_PrepData downAllData = new DownloadAll_PrepData();
    	downAllData.updateUserGenIndex();
    	
    	List <ALM_Rep_Performance_1__c> almRepList = [Select Id, Name From ALM_Rep_Performance_1__c Where Id =: almRep.Id];
    	System.assertEquals(almRepList != null, true);
    	Test.stopTest();
    	
    }
}