youfull/objects/ALM_Rep_Performance_1__c.object
<CustomObject>
    <fields>
        <fullName>SLS_ZONE_CD__c</fullName>
        <label>Zone</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <label>ALM Rep Performance</label>
    <nameField>
        <label>ALM Rep Performance Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>ALM Rep Performance</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

youfull/classes/ALM_Model_User_ZoneManager.cls
/***************************************************************************
 Name          : ALM_Model_User_ZoneManager
 Created By    : Fay Salwen
 Description   : Concrete Model class for Zone Manager users
 Created Date  : Feb 19, 2014               
****************************************************************************/

public with sharing class ALM_Model_User_ZoneManager extends ALM_Model_User_AreaManager {
	
	
    //=================================================================//
    // Allow access if and only if the Zone of the repPerformnace is one 
    // of the ones that this Zone Manager has in visible list
    //=================================================================//
	Boolean isAccessPermitted(ALM_Rep_Performance_1__c repPerformance) {
		return getVisibleZoneSet().contains(repPerformance.SLS_ZONE_CD__c);
	}

}