youfull/objects/ALM_Rep_Performance_1__c.object
<CustomObject>
    <fields>
        <fullName>ACCT_NR__c</fullName>
        <label>Account Number</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>AVON_LOA_1_6_IND__c</fullName>
        <label>Avon LOA 1-6 Indicator</label>
        <length>1</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>FLD_SLS_CMPGN_NR__c</fullName>
        <label>Campaign</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Genealogy_Level__c</fullName>
        <label>Genealogy Level</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>LDRSHP_LOA_NR__c</fullName>
        <label>Leadership LOA</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>LDRSHP_TITL_LVL_NR__c</fullName>
        <label>Badge Title (Achieved Title)</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>LFT_ND_ID__c</fullName>
        <label>Sort</label>
        <precision>12</precision>
        <scale>6</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>MRKT_ACCT_KEY__c</fullName>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>ALM Rep Performance</relationshipLabel>
        <relationshipName>ALM_Rep_Performance_1</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>MRKT_ID__c</fullName>
        <externalId>true</externalId>
        <label>Market Id</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>MailPlan_Order_Oppty__c</fullName>
        <description>Lookup to corresponding record of MailPlan_Order_Oppty</description>
        <inlineHelpText>Lookup to corresponding record of MailPlan_Order_Oppty</inlineHelpText>
        <label>MailPlan_Order_Oppty</label>
        <referenceTo>MailPlan_Order_Oppty__c</referenceTo>
        <relationshipLabel>ALM Rep Performance</relationshipLabel>
        <relationshipName>ALM_Rep_Performance</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>OPERTNL_CMPGN_NR__c</fullName>
        <label>Campaign</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>REP_OMS_STUS_CD__c</fullName>
        <inlineHelpText>1=Staff, 0=removed, -2=Recruit</inlineHelpText>
        <label>Rep Status</label>
        <length>5</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>RGT_ND_ID__c</fullName>
        <label>Right Node Id</label>
        <precision>12</precision>
        <scale>6</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>ROOT_UPLN_ACCT_NR__c</fullName>
        <label>Root Upline Account</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>TRNDSTTR_IND__c</fullName>
        <label>Trendsetter Indicator</label>
        <length>1</length>
        <type>Text</type>
    </fields>
    <label>ALM Rep Performance</label>
    <nameField>
        <label>ALM Rep Performance Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>ALM Rep Performance</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

youfull/objects/MailPlan_Order_Oppty__c.object
<CustomObject>
    <fields>
        <fullName>CMPGN_NR__c</fullName>
        <label>CMPGN_NR</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>MRKT_ID__c</fullName>
        <label>MRKT_ID</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Market__c</fullName>
        <label>Market</label>
        <referenceTo>Market__c</referenceTo>
        <relationshipLabel>MailPlan_Order_Opptys</relationshipLabel>
        <relationshipName>MailPlan_Order_Opptys</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>MailPlan_Order_Oppty</label>
    <nameField>
        <displayFormat>MPLN-{000000}</displayFormat>
        <label>Mail Plan Order Oppty Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>MailPlan_Order_Opptys</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

youfull/objects/Market__c.object
<CustomObject>
    <fields>
        <fullName>ALM_Rep_Indicator__c</fullName>
        <label>ALM Rep Indicator</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CMPGN_NR__c</fullName>
        <label>CMPGN_NR</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Mail_Plan_Enabled__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Mail Plan Enabled</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Market_Id__c</fullName>
        <externalId>true</externalId>
        <label>MRKT_ID</label>
        <length>15</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>NEXT_1_CMPGN_NR__c</fullName>
        <label>NEXT_1_CMPGN_NR</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PREV_1_CMPGN_NR__c</fullName>
        <label>PREV_1_CMPGN_NR</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Site_Maintenance_Enabled__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Site Maintenance Enabled</label>
        <type>Checkbox</type>
    </fields>
    <label>Market</label>
    <nameField>
        <label>Market Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Markets</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

youfull/classes/SiteHeaderControllerTest.cls
@isTest
public with sharing class SiteHeaderControllerTest 
{
	public static String acctNbr = '123456';
	
	public static testmethod void testSiteHeaderController()
    {
        TestDataHelper testData =   new TestDataHelper();
        
        // Creates Market Data
        Market__c mkt = testData.createMarket();
        User ldrUsr;
        User thisUser = [ select Id from User where Id = :UserInfo.getUserId() ];
        
        System.runAs ( thisUser ) {
            ldrUsr = testData.createLeaderUser(acctNbr);
            
            mkt.OwnerId = ldrUsr.Id;
            update  mkt;
        }
        
        // Creates Sales Org Data
        testData.createSalesOrgs();
        
        // Creates Contact Data
        Contact ct = testData.createContact(acctNbr,ldrUsr.Id);
        
        // Creates MailPlan data
        MailPlan_Order_Oppty__c mlplnOrdOppty = testData.creatMailPlans(mkt, ldrUsr.DFALT_ZONE_CD__c);
        
        //Creating ALM REP PERF Data
        List<ALM_Rep_Performance_1__c> lstCombObj = new List<ALM_Rep_Performance_1__c>();
        
        ALM_Rep_Performance_1__c rep1 = new ALM_Rep_Performance_1__c(
                                                Name = 'Test REP1', ACCT_NR__c = ct.ACCT_NR__c,
                                                Genealogy_Level__c = 0,
                                                CurrencyISOCode='USD',
                                                MRKT_ID__c=mkt.Market_ID__c,
                                                MRKT_ACCT_KEY__c = ct.Id,
                                                FLD_SLS_CMPGN_NR__c=Decimal.valueOf(mkt.CMPGN_NR__c),
                                                OPERTNL_CMPGN_NR__c = mkt.CMPGN_NR__c,
                                                REP_OMS_STUS_CD__c = '1', AVON_LOA_1_6_IND__c = 'Y',
                                                LDRSHP_LOA_NR__c=1, LDRSHP_TITL_LVL_NR__c = '1',
                                                ROOT_UPLN_ACCT_NR__c = ct.ACCT_NR__c,
                                                LFT_ND_ID__c = 1, RGT_ND_ID__c = 8, MailPlan_Order_Oppty__c = mlplnOrdOppty.Id
                                            );
        lstCombObj.add(rep1);
                                            
        ALM_Rep_Performance_1__c rep2 = new ALM_Rep_Performance_1__c(
                                                Name = 'Test REP2', ACCT_NR__c = ct.ACCT_NR__c,
                                                Genealogy_Level__c = 0,
                                                CurrencyISOCode='USD',
                                                MRKT_ID__c=mkt.Market_ID__c,
                                                MRKT_ACCT_KEY__c = ct.Id,
                                                FLD_SLS_CMPGN_NR__c=Decimal.valueOf(mkt.NEXT_1_CMPGN_NR__c),
                                                OPERTNL_CMPGN_NR__c = mkt.NEXT_1_CMPGN_NR__c,
                                                REP_OMS_STUS_CD__c = '1', AVON_LOA_1_6_IND__c = 'Y',
                                                LDRSHP_LOA_NR__c=1, LDRSHP_TITL_LVL_NR__c = '1',
                                                ROOT_UPLN_ACCT_NR__c = ct.ACCT_NR__c,
                                                LFT_ND_ID__c = 1, RGT_ND_ID__c = 8, MailPlan_Order_Oppty__c = mlplnOrdOppty.Id
                                            );
        lstCombObj.add(rep2);
        //insert rep1;
        
        ALM_Rep_Performance_1__c rep3 = new ALM_Rep_Performance_1__c(
                                                Name = 'Test REP3', ACCT_NR__c = ct.ACCT_NR__c,
                                                Genealogy_Level__c = 0,
                                                CurrencyISOCode='USD',
                                                MRKT_ID__c=mkt.Market_ID__c,
                                                MRKT_ACCT_KEY__c = ct.Id,
                                                FLD_SLS_CMPGN_NR__c=Decimal.valueOf(mkt.PREV_1_CMPGN_NR__c),
                                                OPERTNL_CMPGN_NR__c = mkt.PREV_1_CMPGN_NR__c,
                                                REP_OMS_STUS_CD__c = '1', AVON_LOA_1_6_IND__c = 'Y',
                                                LDRSHP_LOA_NR__c=1, LDRSHP_TITL_LVL_NR__c = '1',
                                                ROOT_UPLN_ACCT_NR__c = ct.ACCT_NR__c,
                                                LFT_ND_ID__c = 1, RGT_ND_ID__c = 8, MailPlan_Order_Oppty__c = mlplnOrdOppty.Id
                                            );
        lstCombObj.add(rep3);
        insert lstCombObj;
        
        // Create Report Config Data
        testData.createReportConfig();
        
        PageReference pageRef = Page.YOUHome;
        pageRef.getParameters().put('prior', 'prior');
        pageRef.getParameters().put('acctKey', 'XX');
        Test.setCurrentPage(pageRef);  
        
        System.runAs(ldrUsr){
            SiteHeaderController ctlr = new SiteHeaderController();
            
            ctlr.init();
            
            ctlr.getReportLinks();
            ctlr.getReportLinks(mkt.Market_Id__c, ldrUsr.Profile.Name, ldrUsr.LDRSHP_TITL_LVL_NBR__c, true);
        }
        
        System.runAs ( thisUser ) {
            ldrUsr.TRNDSTTR_IND__c = null;
            update ldrUsr;
            
            mkt.Mail_Plan_Enabled__c = false;
            mkt.Site_Maintenance_Enabled__c = true;
            update  mkt;
        }
        
        System.runAs(ldrUsr){
            SiteHeaderController ctlr = new SiteHeaderController();
            
            ctlr.init();
            ctlr.showEarningOpportunity();
            ctlr.getControllerRef();
        }
        
        //For Testing Mail Plan Unable market
        mkt.Mail_Plan_Enabled__c = true;
        update mkt;
        System.runAs(ldrUsr){
            SiteHeaderController ctlr = new SiteHeaderController();
            
            ctlr.init();
            ctlr.showEarningOpportunity();
            ctlr.getControllerRef();
            List<Sobject> lst_CombinedObj = MailPlanUtils.getRepPerf_MailPlan(mkt.ALM_Rep_Indicator__c, acctNbr, mkt.Market_Id__c);
            ctlr.getMailPlanCampaign(lst_CombinedObj);
        }
        
        
           
    }
}