youfull/objects/ALM_Rep_Performance_1__c.object
<CustomObject>
    <fields>
        <fullName>LFT_ND_ID__c</fullName>
        <label>Sort</label>
        <precision>12</precision>
        <scale>6</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>MRKT_ACCT_KEY__c</fullName>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>ALM Rep Performance</relationshipLabel>
        <relationshipName>ALM_Rep_Performance_1</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>MRKT_ID__c</fullName>
        <externalId>true</externalId>
        <label>Market Id</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>MailPlan_Order_Oppty__c</fullName>
        <description>Lookup to corresponding record of MailPlan_Order_Oppty</description>
        <inlineHelpText>Lookup to corresponding record of MailPlan_Order_Oppty</inlineHelpText>
        <label>MailPlan_Order_Oppty</label>
        <referenceTo>MailPlan_Order_Oppty__c</referenceTo>
        <relationshipLabel>ALM Rep Performance</relationshipLabel>
        <relationshipName>ALM_Rep_Performance</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>RGT_ND_ID__c</fullName>
        <label>Right Node Id</label>
        <precision>12</precision>
        <scale>6</scale>
        <type>Number</type>
    </fields>
    <label>ALM Rep Performance</label>
    <nameField>
        <label>ALM Rep Performance Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>ALM Rep Performance</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

youfull/objects/Landing_Page_Config__c.object
<CustomObject>
    <fields>
        <fullName>Market__c</fullName>
        <label>Market</label>
        <referenceTo>Market__c</referenceTo>
        <relationshipLabel>Landing Page Config</relationshipLabel>
        <relationshipName>Landing_Page_Config</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Landing Page Config</label>
    <nameField>
        <label>Landing Page Config Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Landing Page Config</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

youfull/objects/MailPlan_Order_Oppty__c.object
<CustomObject>
    <fields>
        <fullName>CMPGN_NR__c</fullName>
        <label>CMPGN_NR</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>MRKT_ID__c</fullName>
        <label>MRKT_ID</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Market__c</fullName>
        <label>Market</label>
        <referenceTo>Market__c</referenceTo>
        <relationshipLabel>MailPlan_Order_Opptys</relationshipLabel>
        <relationshipName>MailPlan_Order_Opptys</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>MailPlan_Order_Oppty</label>
    <nameField>
        <displayFormat>MPLN-{000000}</displayFormat>
        <label>Mail Plan Order Oppty Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>MailPlan_Order_Opptys</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

youfull/objects/Market__c.object
<CustomObject>
    <fields>
        <fullName>CMPGN_NR__c</fullName>
        <label>CMPGN_NR</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Mail_Plan_Enabled__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Mail Plan Enabled</label>
        <type>Checkbox</type>
    </fields>
    <label>Market</label>
    <nameField>
        <label>Market Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Markets</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

youfull/classes/Test_ComponentController.cls
/***************************************************************************
 Name          : Test_ComponentController
 Created By    : Barkha Jain (JDC)
 Description   : Test class for ComponentController
 Created Date  : Nov 6, 2013                
****************************************************************************/
@isTest
private class Test_ComponentController {
	static Market__c mkt;
    static String mrktId = 'DE';
    static User usr;
    static ALM_Rep_Performance_1__c rep;
    
	//----------------------------------------------------------------------------
    // Method Name  : testComponentController
    // Description  : Method for Test Coverage of Class : ComponentController
    //----------------------------------------------------------------------------
    static testMethod void testComponentController() {
    	createTestData();
    	
        PageReference pg = new PageReference('/apex/ELRisingStars');
        Test.setCurrentPage(pg);
        ApexPages.currentPage().getParameters().put('mpCampaign', mkt.CMPGN_NR__c);
        ApexPages.currentPage().getParameters().put('acctkey', '1234');
        
        Test.startTest();
        system.runAs(usr){  
        	ComponentController ctrl = new ComponentController();
        	Pagereference result = ctrl.isValidPage();
        	//verify result
        	system.assertNotEquals(null, result.getParameters().get('errId'));
        }
        
        //insert ALM_Rep_Performance_1__c record	
        insert rep;
        
        system.runAs(usr){	
        	ComponentController ctrl = new ComponentController();
        	
        	rep = [select Id, MailPlan_Order_Oppty__r.CMPGN_NR__c from ALM_Rep_Performance_1__c where Id =:rep.Id limit 1];
        	//test getMailPlanCampaign method
        	try{
        		ctrl.getMailPlanCampaign(new List<ALM_Rep_Performance_1__c>{rep});
        	}catch(Exception e){}
        }
        Test.stopTest();
    }
    
    //----------------------------------------------------------------------------
    // Method to create test data
    //----------------------------------------------------------------------------
    private static void createTestData(){
        TestDataHelper.createALMGlobalSetting(true);
        //creating test user
        usr = TestDataHelper.createUser('1234', 'XZ1', 'Avon Leader', false);
        usr.MRKT_ID__c = mrktId;
        usr.MRKT_ID_ACCT_NR_KEY__c = mrktId + '1234';
        insert usr;
                        
        System.runAs(usr){
            mkt = TestDataHelper.createMarket(mrktId, false);
            mkt.Mail_Plan_Enabled__c = true;
            insert mkt;
        }
        
        Account acc = TestDataHelper.createAccount('Test Account', 'USD', true);
    	Contact c = TestDataHelper.createContact('1234', acc.Id, false);
    	c.MRKT_ACCT_KEY__c = mrktId + '1234';
    	insert c;
    	
    	MailPlan_Order_Oppty__c mplan = TestDataHelper.createMPOrderOpp(mkt.Id, mkt.CMPGN_NR__c, 'N', System.today().addDays(1+10), 
    											'M1', 'XZ1', 'M', false);
    
    	rep = TestDataHelper.createRepPerformance(c.Id, mkt, '1234', false);	
    	rep.MailPlan_Order_Oppty__c = mplan.Id;
    	rep.LFT_ND_ID__c = 0;
	    rep.RGT_ND_ID__c = 5;
	    
	    Landing_Page_Config__c config = TestDataHelper.createLandingPageConfig(mkt.Id, 'All', 'All', true);
	    TestDataHelper.createLadingPageComponent(config.Id, 'ELRisingStars', true);
       
    }
}