youfull/objects/ALM_Rep_Performance_1__c.object
<CustomObject>
    <fields>
        <fullName>ACCT_NR__c</fullName>
        <label>Account Number</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>G1_ACTV_BASE_CNT__c</fullName>
        <label>G1_ACTV_BASE_CNT</label>
        <precision>13</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>LDRSHP_TITL_LVL_DESC__c</fullName>
        <label>Badge Title</label>
        <picklist>
            <picklistValues>
                <fullName>Candidate</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Advance Unit Leader</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Senior Executive Unit Leader 5</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Unit Leader</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Executive Unit Leader</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Non Leader</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Senior Executive Unit Leader 1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Senior Executive Unit Leader 2</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Senior Executive Unit Leader 3</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Senior Executive Unit Leader 4</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Title Level 0</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Title Level 1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Title Level 2</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Title Level 3</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Title Level 4</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Title Level 5</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Title Level 6</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Title Level 7</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Title Level 8</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Title Level 9</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Title Level 10</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Title Level 11</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Title Level 12</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Title Level 13</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Title Level 14</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>LDR_TYP__c</fullName>
        <label>LDR_TYP</label>
        <length>5</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>LOA_NR__c</fullName>
        <label>LOA</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>MLPLN_CD__c</fullName>
        <label>Mail Plan</label>
        <length>5</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>MRKT_ACCT_KEY__c</fullName>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>ALM Rep Performance</relationshipLabel>
        <relationshipName>ALM_Rep_Performance_1</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>MRKT_ID__c</fullName>
        <externalId>true</externalId>
        <label>Market Id</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>REP_APPT_CMPGN_NR__c</fullName>
        <label>Appointment Campaign</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>RSNG_STR_IND__c</fullName>
        <label>Rising Star Indicator</label>
        <length>1</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SLS_ZONE_CD__c</fullName>
        <label>Zone</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>UPLN_SLS_ZONE_CD__c</fullName>
        <label>Upline/Sponsor Zone Number</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ZONE_MGR_NAME__c</fullName>
        <label>Zone Manager</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>ALM Rep Performance</label>
    <nameField>
        <label>ALM Rep Performance Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>ALM Rep Performance</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

youfull/classes/Controller_SLCoachingRecord.cls
/***************************************************************************
 Name          : Controller_SLCoachingRecord
 Created By    : Barkha Jain 
 Description   : Controller for CoachingRecord page
 Created Date  : 20 Dec, 2013                
****************************************************************************/
public class Controller_SLCoachingRecord{
    public User currentUser {get; set;}
    public Contact contactUser {get; set;}
    public ALM_Rep_Performance_1__c almRep {get; set;}
    
    public Controller_SLCoachingRecord(){
        init();
    }
    
    private void init(){
     currentUser = [Select Name, MRKT_TAG_1_HDR_TXT__c, MRKT_ID__c, MLPLN_CD__c, USER_CNTRY_CD__c, 
                    LastName, LanguageLocaleKey, FirstName, MRKT_ID_ACCT_NR_KEY__c, DFALT_ZONE_CD__c, 
                    DFALT_DIV_NM__c, ACCT_NR__c, Profile.Name, LDRSHP_TITL_LVL_NBR__c 
                    From User where Id = :UserInfo.getUserId()]; 
     
     for(Contact con : [Select Name, MRKT_ID__c,LDR_TYP__c, MLPLN_CD__c, MRKT_ACCT_KEY__c, LOA_NR__c, LDRSHP_TITL_LVL_DESC__c,
                        SLS_ZONE_CD__c, ACCT_NR__c, REP_APPT_CMPGN_NR__c, REP_EMAIL_ADDR_TXT__c, REP_LANG_CD__c
                        From Contact where MRKT_ACCT_KEY__c =:currentUser.MRKT_ID_ACCT_NR_KEY__c]){
        contactUser = con;  
     }
     
     for(ALM_Rep_Performance_1__c rep : [Select RSNG_STR_IND__c, ACCT_NR__c, ZONE_MGR_NAME__c, G1_ACTV_BASE_CNT__c, UPLN_SLS_ZONE_CD__c 
                                         From ALM_Rep_Performance_1__c
                                         where ACCT_NR__c =:currentUser.ACCT_NR__c limit 1]){
        almRep = rep;
     }                  
    } 
    
    public PageReference doNothing(){return null;}  
    
    
}