youfull/objects/ALM_Rep_Performance_1__c.object
<CustomObject>
    <fields>
        <fullName>ACCT_NR__c</fullName>
        <label>Account Number</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>LDRSHP_TITL_LVL_NR__c</fullName>
        <label>Badge Title (Achieved Title)</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>MRKT_ACCT_KEY__c</fullName>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>ALM Rep Performance</relationshipLabel>
        <relationshipName>ALM_Rep_Performance_1</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>MailPlan_Order_Oppty__c</fullName>
        <description>Lookup to corresponding record of MailPlan_Order_Oppty</description>
        <inlineHelpText>Lookup to corresponding record of MailPlan_Order_Oppty</inlineHelpText>
        <label>MailPlan_Order_Oppty</label>
        <referenceTo>MailPlan_Order_Oppty__c</referenceTo>
        <relationshipLabel>ALM Rep Performance</relationshipLabel>
        <relationshipName>ALM_Rep_Performance</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>ALM Rep Performance</label>
    <nameField>
        <label>ALM Rep Performance Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>ALM Rep Performance</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

youfull/objects/Genealogy_Field_Detail__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <customSettingsVisibility>Public</customSettingsVisibility>
    <label>Genealogy Field Detail</label>
</CustomObject>

youfull/objects/Leader_Title__c.object
<CustomObject>
    <fields>
        <fullName>LDRSHP_TITL_LVL_NR__c</fullName>
        <label>Title Level Number</label>
        <picklist>
            <picklistValues>
                <fullName>UQ</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>-2</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>0</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>3</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>4</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>5</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>21</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>6</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>7</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>8</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>9</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>10</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Market__c</fullName>
        <label>Market</label>
        <referenceTo>Market__c</referenceTo>
        <relationshipLabel>Leader Titles</relationshipLabel>
        <relationshipName>Leader_Titles</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Leader Title</label>
    <nameField>
        <displayFormat>LDT-{000000}</displayFormat>
        <label>Leader Title Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Leader Titles</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

youfull/objects/MailPlan_Order_Oppty__c.object
<CustomObject>
    <fields>
        <fullName>CMPGN_NR__c</fullName>
        <label>CMPGN_NR</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Market__c</fullName>
        <label>Market</label>
        <referenceTo>Market__c</referenceTo>
        <relationshipLabel>MailPlan_Order_Opptys</relationshipLabel>
        <relationshipName>MailPlan_Order_Opptys</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>MailPlan_Order_Oppty</label>
    <nameField>
        <displayFormat>MPLN-{000000}</displayFormat>
        <label>Mail Plan Order Oppty Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>MailPlan_Order_Opptys</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

youfull/objects/Market__c.object
<CustomObject>
    <fields>
        <fullName>ALM_Rep_Indicator__c</fullName>
        <label>ALM Rep Indicator</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CMPGN_NR__c</fullName>
        <label>CMPGN_NR</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Genealogy_Overlay_Section__c</fullName>
        <label>Genealogy Overlay Section</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Market_Id__c</fullName>
        <externalId>true</externalId>
        <label>MRKT_ID</label>
        <length>15</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Market</label>
    <nameField>
        <label>Market Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Markets</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

youfull/classes/Test_GenealogyOverlayInfo.cls
/***************************************************************************
 Name          : Test_GenealogyOverlayInfo 
 Created By    : Barkha Jain (JDC)
 Description   : Test class for GenealogyOverlayInfo
 Created Date  : Oct 31, 2013                
****************************************************************************/
@isTest
private class Test_GenealogyOverlayInfo {
	static String marketAccountkey;
	static Market__c mrkt;
	
	//----------------------------------------------------------------------------
    // Method Name  : testGenealogyOverlayInfo
    // Description  : Method for Test Coverage of Class : GenealogyOverlayInfo
    //----------------------------------------------------------------------------
	private static testMethod void testGenealogyOverlayInfo(){
		createTestData();
		
		Test.startTest();
		String queryObject = mrkt.ALM_Rep_Indicator__c.replace('__c','__r');
		Integer cmpgnNo = Integer.valueOf(mrkt.CMPGN_NR__c);
		
		GenealogyOverlayInfo gObj = new GenealogyOverlayInfo();
		GenealogyOverlayInfo genOverlayInfo = new GenealogyOverlayInfo(mrkt.Id, queryObject, true, cmpgnNo, marketAccountkey, 'en_US', 'N');
		system.assertEquals(1, genOverlayInfo.overlayLeaderCount.size());
		Test.stopTest();
	}
	
	//----------------------------------------------------------------------------
    // Method Name  : createTestData
    // Description  : Method for creating dummy test data
    //----------------------------------------------------------------------------
	static void createTestData(){
		TestDataHelper.createALMGlobalSetting(true);
		User ldrUsr = TestDataHelper.createUser('1234', 'XZ1', 'Avon Leader', true);
		
		system.runAs(ldrUsr){
			mrkt = TestDataHelper.createMarket('DE', false);
			mrkt.Genealogy_Overlay_Section__c = 'field1';
			insert mrkt;
		}
		marketAccountkey = mrkt.Market_Id__c + ldrUsr.ACCT_NR__c;
		
		Leader_Title__c leaderTitle = TestDataHelper.createLeaderTitle(mrkt.Id, 'DE', true);
		
		Account acc = TestDataHelper.createAccount('Test Account', 'USD', true);
	    Contact c = TestDataHelper.createContact('1234', acc.Id, false);
	    c.MRKT_ACCT_KEY__c = marketAccountkey;
	    insert c;
	    
	    MailPlan_Order_Oppty__c mplan = TestDataHelper.createMPOrderOpp(mrkt.Id, '4', 'N', System.today().addDays(1+10), 
        											'M1', 'XZ1', 'M', false);
	    
	    ALM_Rep_Performance_1__c rep = TestDataHelper.createRepPerformance(c.Id, mrkt, '1234', false);	
	    rep.MailPlan_Order_Oppty__c = mplan.Id;
	    insert rep;
	    
	    Genealogy_Field_Detail__c gFieldDetail = TestDataHelper.createGenealogyFieldDetail('field1', 'Number', 1, 
	    																		'Overlay', 'ALM_Rep_Performance_1:LDRSHP_TITL_LVL_NR__c', '1', true);
	}
}