youfull/objects/ALM_Rep_Performance_1__c.object
<CustomObject>
    <fields>
        <fullName>CHK_NRT_INVC_IS_ACTIVE__c</fullName>
        <defaultValue>false</defaultValue>
        <label>CHK_NRT_INVC_IS_ACTIVE</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>CHK_NRT_IS_ACTIVE_APPT__c</fullName>
        <defaultValue>false</defaultValue>
        <label>CHK_NRT_IS_ACTIVE_APPT</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>CHK_NRT_SBMTD_IS_ACTIVE__c</fullName>
        <defaultValue>false</defaultValue>
        <label>CHK_NRT_SBMTD_IS_ACTIVE</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>MRKT_KEY__c</fullName>
        <label>Market</label>
        <referenceTo>Market__c</referenceTo>
        <relationshipLabel>ALM Rep Performance</relationshipLabel>
        <relationshipName>ALM_Rep_Performance_1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>NRT_INVC_IS_ACTIVE__c</fullName>
        <description>Rep considered active based on the NRT invoiced data?</description>
        <formula>If ( CDW_Is_Active__c 
, 1 
, If ( 
(MRKT_KEY__r.NRT_ACTIVE_USES_NET__c) 
, IF((NRT_DLY_INVC_AWRD_SLS_AMT__c + NRT_DLY_INVC_RTURN_AWRD_SLS_AMT__c) &gt; 0 
, 1 
, 0 
) 
, IF(NRT_DLY_INVC_AWRD_SLS_AMT__c &gt; 0 
, 1 
, 0 
) 
) 
)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>NRT Invoice Is Active</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>NRT_IS_ACTIVE_APPT__c</fullName>
        <formula>IF(NRT_IS_ACTIVE__c &amp;&amp; (LOA_NR__c == 0), 1, 0)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>NRT IS Active Appt</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>NRT_SBMTD_IS_ACTIVE__c</fullName>
        <formula>IF(  (NRT_INVC_IS_ACTIVE__c ==0)
   , IF(MRKT_KEY__r.NRT_HAS_SUBMTD_AMT__c 
          , IF ( MRKT_KEY__r.NRT_ACTIVE_USES_NET__c 
                    , IF((NRT_SUBMTD_AWRD_SLS_AMT__c + NRT_SUBMTD_RTURN_AWRD_SLS_AMT__c &gt; 0)
                         , 1
                         , 0
                       )
                    , IF ( (NRT_SUBMTD_AWRD_SLS_AMT__c &gt; 0)
                           , 1
                           , 0
                      )
             )         
          , IF( (NRT_SUBMTD_AWRD_ORDER_CNT__c &gt; 0) 
                      , 1
                      , 0
               )
      )
    
   , 0 
  )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>NRT Submitted is Active</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>SLS_ORG_SUMRY_KEY__c</fullName>
        <description>Look-up to the Sales Org Summary Object</description>
        <label>SLS ORG SUMRY KEY</label>
        <referenceTo>Sales_Org_Summary__c</referenceTo>
        <relationshipLabel>ALM Rep Performance</relationshipLabel>
        <relationshipName>ALM_Rep_Performance</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>ALM Rep Performance</label>
    <nameField>
        <label>ALM Rep Performance Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>ALM Rep Performance</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

youfull/objects/Market__c.object
<CustomObject>
    <fields>
        <fullName>Batch_Load_In_Process__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Flag to be set by CDW when starting the nightly batch and reset after its complete.</description>
        <inlineHelpText>Flag to be set by CDW when starting the nightly batch and reset after its complete.</inlineHelpText>
        <label>Batch Load In Process</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Market_Id__c</fullName>
        <externalId>true</externalId>
        <label>MRKT_ID</label>
        <length>15</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>NRT_Enabled__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Flag to determine, if this market is participating in NRT or not.</description>
        <label>NRT Enabled</label>
        <type>Checkbox</type>
    </fields>
    <label>Market</label>
    <nameField>
        <label>Market Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Markets</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

youfull/objects/Sales_Org_Summary__c.object
<CustomObject>
    <fields>
        <fullName>MRKT_KEY__c</fullName>
        <label>Market</label>
        <referenceTo>Market__c</referenceTo>
        <relationshipLabel>Sales Org Summary</relationshipLabel>
        <relationshipName>Sales_Org_Summary</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SLS_ORG_SUMRY_KEY__c</fullName>
        <description>Sales Org Summary Key.  Format: MRKT_ID+CMPGN_NR+ORG_TYPE+ORG_NAME</description>
        <externalId>true</externalId>
        <label>SLS_ORG_SUMRY_KEY__c</label>
        <length>100</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Sales Org Summary</label>
    <nameField>
        <label>Sales Org Summary Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sales Org Summaries</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

youfull/classes/NRT_ALM_SalesOrgSummaryRollupBatch.cls
global without sharing class NRT_ALM_SalesOrgSummaryRollupBatch  implements Database.Batchable<Sobject>{
	
	/**
		
	**/
	
	public class AlmCounts
	{
		public Decimal submitedCnt{get;set;}
		public Decimal invoicedCount{get;set;}
		public Decimal activeCount{get;set;}
	}
	global Database.QueryLocator start(Database.BatchableContext BC)
	{
		set<String> marketKeys = new set<String>();
		for(Market__c m : [Select Market_Id__c 
		                     from Market__c 
		                    where Batch_Load_In_Process__c = false 
		                      and NRT_Enabled__c = true])  
		{
			marketKeys.add(m.Id);
		}
		return Database.getQueryLocator([Select Id
		                                   From Sales_Org_Summary__c 
		                                  where Sales_Org_Summary__c.MRKT_KEY__c in :marketKeys]);
	}
	global void execute(Database.BatchableContext BC, List<Sales_Org_Summary__c> sos)
	{ 
		map<string, AlmCounts> SalesOrgSummaryCounts = new map<string, AlmCounts>();
		set<String> marketKeys = new set<String>();
		for(Market__c m : [Select Market_Id__c from Market__c where Batch_Load_In_Process__c = false and NRT_Enabled__c = true])  
		{
			marketKeys.add(m.Market_Id__c);
		}
			
		
		//NRT_SBMTD_ACTIVE_CNT 
		for(AggregateResult r1 :[select sum(NRT_SBMTD_IS_ACTIVE__c) submitedCnt
		                              , sum(NRT_INVC_IS_ACTIVE__c) invoicedCount
		                              , sum(NRT_IS_ACTIVE_APPT__c) activeCount
		                              , SLS_ORG_SUMRY_KEY__c
		                           from ALM_Rep_Performance_1__c 
		                          where SLS_ORG_SUMRY_KEY__c in :sos
		                          group by SLS_ORG_SUMRY_KEY__c])
	   {
	   		AlmCounts cnt = new AlmCounts(); 
	   		string sosId = (String)r1.get('SLS_ORG_SUMRY_KEY__c');
	   		cnt.submitedCnt = (Decimal)r1.get('submitedCnt');
	   		cnt.invoicedCount = (Decimal)r1.get('invoicedCount');
	   		cnt.activeCount = (Decimal)r1.get('activeCount');
	   		
	   		SalesOrgSummaryCounts.put(sosId, cnt);
	   }  
	   
	   list<Sales_Org_Summary__c> sosUpdateList = new  list<Sales_Org_Summary__c>();
	   for(Sales_Org_Summary__c sos1 : [Select Id
	                                        , NRT_SBMTD_ACTIVE_CNT__c
	                                        , NRT_INVC_ACTIVE_CNT__c
	                                        , NRT_ACTIVE_APPT_CNT__c
	                                        , SLS_ORG_SUMRY_KEY__c
	                                     from Sales_Org_Summary__c
	                                    where Id in :SalesOrgSummaryCounts.keySet()]) 
	  {
	  	  if(SalesOrgSummaryCounts.containsKey(sos1.SLS_ORG_SUMRY_KEY__c))
	  	  {
	  	     AlmCounts cnt = SalesOrgSummaryCounts.get(sos1.SLS_ORG_SUMRY_KEY__c);
	  	     sos1.NRT_ACTIVE_APPT_CNT__c += cnt.activeCount;
	  	     sos1.NRT_INVC_ACTIVE_CNT__c += cnt.invoicedCount;
	  	     sos1.NRT_SBMTD_ACTIVE_CNT__c += cnt.submitedCnt;
	  	  }
	  	     
	  	  sosUpdateList.add(sos1);
	  }
	  
	  //Set the counts on the Sales Org Summary Records
	  if(sosUpdateList.size() > 0)
	    update sosUpdateList;
	    
	  //reset all the ALM_Rep_Performance_1__c records in this batch so that they don't reprocess
	  list<ALM_Rep_Performance_1__c> repList = new list<ALM_Rep_Performance_1__c>();
	  for(ALM_Rep_Performance_1__c a :[Select Id
	  										, NRT_SBMTD_IS_ACTIVE__c
		                              		, NRT_INVC_IS_ACTIVE__c
		                              		, NRT_IS_ACTIVE_APPT__c 
		                                 from ALM_Rep_Performance_1__c 
		                                where SLS_ORG_SUMRY_KEY__c in :sos])
	  {
	  		a.CHK_NRT_SBMTD_IS_ACTIVE__c = true;
		    a.CHK_NRT_INVC_IS_ACTIVE__c = true;
		    a.CHK_NRT_IS_ACTIVE_APPT__c = true;
		    repList.add(a);
	  }
	  
	  if(repList.Size() > 0)
	  	update repList;
	  
	}
	
	global void finish(Database.BatchableContext BC){	
		
	}
	/*
	@isTest(seeAllData=true)
	static void runTest()
	{
		SchedulableContext sc;
		NRT_ALM_SalesOrgSummaryRollup nrt = new NRT_ALM_SalesOrgSummaryRollup();
		nrt.execute(sc);
		
	}
	*/
	
}