youfull/objects/ALM_Global_Settings__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <customSettingsVisibility>Protected</customSettingsVisibility>
    <description>Holds global settings that apply across the entire application.</description>
    <label>ALM Global Settings</label>
</CustomObject>

youfull/objects/ALM_Rep_Performance_1__c.object
<CustomObject>
    <fields>
        <fullName>ACCT_NR__c</fullName>
        <label>Account Number</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>LDRSHP_TITL_LVL_NR__c</fullName>
        <label>Badge Title (Achieved Title)</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>LOA_NR__c</fullName>
        <label>LOA</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>MRKT_ACCT_KEY__c</fullName>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>ALM Rep Performance</relationshipLabel>
        <relationshipName>ALM_Rep_Performance_1</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>MRKT_CMPGN_SLS_ZONE_CD__c</fullName>
        <label>Market Campaign / Zone (Cluster)</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>MRKT_ID__c</fullName>
        <externalId>true</externalId>
        <label>Market Id</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <label>ALM Rep Performance</label>
    <nameField>
        <label>ALM Rep Performance Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>ALM Rep Performance</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

youfull/objects/Market__c.object
<CustomObject>
    <fields>
        <fullName>CMPGN_NR__c</fullName>
        <label>CMPGN_NR</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Market_Currency_Symbol__c</fullName>
        <description>it denotes the currency symbol to be used in Coaching record page.</description>
        <label>Market Currency Symbol</label>
        <length>2</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Market_Id__c</fullName>
        <externalId>true</externalId>
        <label>MRKT_ID</label>
        <length>15</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>NRT_Enabled__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Flag to determine, if this market is participating in NRT or not.</description>
        <label>NRT Enabled</label>
        <type>Checkbox</type>
    </fields>
    <label>Market</label>
    <nameField>
        <label>Market Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Markets</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

youfull/objects/Order_1__c.object
<CustomObject>
    <description>Used to sum up the NRT orders from WebMethods. Order_1 to refer to ALM_Rep_Performance_1 custom object</description>
    <fields>
        <fullName>ACCT_NR__c</fullName>
        <label>Acct. No.</label>
        <length>35</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>MRKT_ID__c</fullName>
        <label>MRKT_ID</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <label>Order</label>
    <nameField>
        <label>Order Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Orders</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

youfull/objects/Sales_Org_Summary__c.object
<CustomObject>
    <fields>
        <fullName>LOA_NR__c</fullName>
        <label>LOA</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>MRKT_ACCT_KEY__c</fullName>
        <externalId>true</externalId>
        <inlineHelpText>MRKT_ACCT_KEY</inlineHelpText>
        <label>Sales Org Manager Key</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <label>Sales Org Summary</label>
    <nameField>
        <label>Sales Org Summary Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sales Org Summaries</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

youfull/classes/Test_NRT_Overlay_Summary_Ctl.cls
/***************************************************************************
 Name          : Test_NRT_Overlay_Summary_Ctl 
 Modified By   : Parul Gupta (JDC)
 Description   : Test class for NRT_Overlay_Summary_Ctl
 Modified Date : Nov 7, 2013                
****************************************************************************/
@isTest
private  class Test_NRT_Overlay_Summary_Ctl {
	
	public static String mktIdKey = 'XX';
	static Market__c mrkt;
	static User ldrUsr;
	static Account testAcct;
	static Contact con1;
	static ALM_Rep_Performance_1__c rep1;
	static Sales_Org_Summary__c sos;
	static Order_1__c  order1;
	
	//---------------------------------------------------------------------------
    // Method Name  : runGeneralCoverage
    // Description  : Method for Test Coverage for NRT_Overlay_Summary_Ctl
    //---------------------------------------------------------------------------
    static testMethod void runGeneralCoverage() {
    	
    	createBaseData();    	
		System.runAs(ldrUsr)
	    {
	    	ApexPages.currentPage().getParameters().put('mpCampaign', '201313');
	    	NRT_Overlay_Summary_Ctl clone = new NRT_Overlay_Summary_Ctl();
	    	clone.getNrtTimestamp();
	    	clone.getNrtEnabled();
	    	rep1.MRKT_CMPGN_SLS_ZONE_CD__c = mrkt.Market_Id__c+'201313'+'1';
		    rep1.LDRSHP_TITL_LVL_NR__c = '1';
		    rep1.LOA_NR__c = 0;
		    update rep1;
		    
	    	NRT_Overlay_Summary_Ctl.refreshData(rep1.ACCT_NR__c
									           ,mrkt.Market_Id__c
									           ,(Decimal.ValueOf(201313))
									           ,'', false, false);
		   
		   
		   	NRT_Overlay_Summary_Ctl.refreshData(rep1.ACCT_NR__c
									          ,mrkt.Market_Id__c
									          ,(Decimal.ValueOf(201313))
									          ,'1', true, true);	    
	    }
    }
    
    static void createBaseData(){
    	// Creating market data
    	mrkt = TestDataHelper.createMarket(mktIdKey, false);
        mrkt.Market_Currency_Symbol__c = '₱';
    	mrkt.CMPGN_NR__c = '201313';
    	mrkt.NRT_Enabled__c = true;
        insert  mrkt;
        
        // Create Leader User 
        ldrUsr = TestDataHelper.createUser('1234', 'XZ1', 'Avon Leader', false);
     	ldrUsr.MRKT_ID__c = mktIdKey;
     	insert ldrUsr;
     	
        mrkt.OwnerId = ldrUsr.Id;
        update  mrkt;
        		
        ALM_Global_Settings__c setting = TestDataHelper.createALMGlobalSetting(true);
        
        // Creating Account and contact data
        testAcct = TestDataHelper.createAccount('Test Account', 'USD', true);        
              
       	con1 = TestDataHelper.createContact('1234', testAcct.id, false);
        con1.MRKT_ACCT_KEY__c = mrkt.Market_Id__c + '1234';
        con1.ownerId = ldrUsr.Id;
        insert con1;
        
        // Creating ALM Rep Performance
        rep1 = TestDataHelper.createALMRepPerformance('1234', null, '1234',
    										0, con1.Id,  
    										mrkt.Market_ID__c,
    										Decimal.valueOf(mrkt.CMPGN_NR__c),
    										mrkt.CMPGN_NR__c,  
    										1, 8, true);
 		
 		// Create Sales Org Summary
 		sos = TestDataHelper.createSalesOrSummaries('Test SOS', null, mrkt.Id, 
    									 		null, mrkt.CMPGN_NR__c, true);
      	
      	// Create Order
      	order1 = TestDataHelper.createOrder('1234', mrkt,
    									rep1.Id, sos.Id,
    									true);
	}
    
}