youfull/objects/ALM_Rep_Performance_1__c.object
<CustomObject>
    <fields>
        <fullName>MRKT_KEY__c</fullName>
        <label>Market</label>
        <referenceTo>Market__c</referenceTo>
        <relationshipLabel>ALM Rep Performance</relationshipLabel>
        <relationshipName>ALM_Rep_Performance_1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>NXT_TITL_LVL_KEY__c</fullName>
        <label>Next Title</label>
        <referenceTo>Leader_Title__c</referenceTo>
        <relationshipLabel>ALM Rep Performance</relationshipLabel>
        <relationshipName>ALM_Rep_Performance</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>ALM Rep Performance</label>
    <nameField>
        <label>ALM Rep Performance Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>ALM Rep Performance</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

youfull/objects/Leader_Title__c.object
<CustomObject>
    <fields>
        <fullName>LDRSHP_TITL_TYPE_NR__c</fullName>
        <label>Title Type Number</label>
        <picklist>
            <picklistValues>
                <fullName>1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>3</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>4</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>5</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Market__c</fullName>
        <label>Market</label>
        <referenceTo>Market__c</referenceTo>
        <relationshipLabel>Leader Titles</relationshipLabel>
        <relationshipName>Leader_Titles</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Leader Title</label>
    <nameField>
        <displayFormat>LDT-{000000}</displayFormat>
        <label>Leader Title Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Leader Titles</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

youfull/objects/Market__c.object
<CustomObject>
    <label>Market</label>
    <nameField>
        <label>Market Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Markets</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

youfull/objects/SL_KPIConfig__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <customSettingsVisibility>Public</customSettingsVisibility>
    <description>Definition of a KPI for SalesLeaders, includes mappings to the Goal fields (on Leader_Title) and the Actual fields (on ALM_Rep_Performance)</description>
    <label>SL_KPIConfig</label>
</CustomObject>

youfull/objects/SL_Market_KPIConfig__c.object
<CustomObject>
    <description>This is used to link a particular KPI to a Market and Leader Title Type for a given Context.</description>
    <fields>
        <fullName>Context__c</fullName>
        <label>Context</label>
        <picklist>
            <picklistValues>
                <fullName>Title Achievement</fullName>
            </picklistValues>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <fields>
        <fullName>Leader_Title_Type__c</fullName>
        <label>Leader Title Type</label>
        <picklist>
            <picklistValues>
                <fullName>1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>3</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>4</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>5</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Market__c</fullName>
        <label>Market</label>
        <referenceTo>Market__c</referenceTo>
        <relationshipName>MarketSLKPIConfigs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SL_KPIConfigName__c</fullName>
        <label>Zone KPI Configuration</label>
        <picklist>
            <picklistValues>
                <fullName>Personal Volume</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>G1 Actives</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Incr G1 Actives</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>G1 Sales</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Incr G1 Sales</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>G1-3 Actives</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Total Unit Sales</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Blocked Total Unit Sales</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Executive Volume</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Downline Volume</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Titled Legs</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>SortOrder__c</fullName>
        <label>SortOrder</label>
        <picklist>
            <picklistValues>
                <fullName>1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>3</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>4</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>5</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>6</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>7</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>8</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>9</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>10</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>11</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>12</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>13</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>14</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>15</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>16</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>17</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>18</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>19</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>20</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>21</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>22</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>23</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>24</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>25</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>26</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>27</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>28</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>29</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>30</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>SL_Market_KPIConfig</label>
    <nameField>
        <label>Custom Object Label Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>SL_Market_KPIConfigs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

youfull/classes/Util_KPIConfig.cls
/***************************************************************************
 Name          : Util_KPIConfig 
 Description   : Demo version of Utility Class to support the Sales Leader KPIs
 Created By    : Fay Salwen 
 Created Date  : Dec 26, 2013                
****************************************************************************/

public with sharing class Util_KPIConfig{
    
    //==============================================================================================//
    //Constructor
    //==============================================================================================//
    public Util_KPIConfig() {  
        
    }   
    
    //==============================================================================================//
    //Return all the custom setting (SL_ZoneKPIConfig__c) data/rows for a given representative
    //==============================================================================================//
    public static List<SL_KPIConfig__c> getKPIConfigsForRepPerformanceAndContext(ALM_Rep_Performance_1__c repPerf, String context){
        return getKPIConfigsForMarketAndTitleTypeAndContext(repPerf.MRKT_KEY__c, repPerf.NXT_TITL_LVL_KEY__r.LDRSHP_TITL_TYPE_NR__c, context);
    }

    //==============================================================================================//
    //Return all the custom setting (SL_ZoneKPIConfig__c) data/rows for a given Market, Title Type, and Context
    //Logic used to get the required data is:
    //   1. Fetch the SL_MarketKPIConfig__c records with the given contectId and markert Id
    //   2. Use the data from above point, to get the related custom setting data with same CONFIG_NAME
    //==============================================================================================//
    public static List<SL_KPIConfig__c> getKPIConfigsForMarketAndTitleTypeAndContext(String marketId, String titleType, String context){

        String logMessage = 'POC_SL_Utility_KPIConfig::getKPIConfigsForMarketAndTitleTypeAndContext::Method Parameters::marketId = '
                            + marketId + ', titleType = ' + titleType + ', context = ' + context;
        
        ALMLogUtils.log(logMessage);
        String strQuery = 'Select SL_KPIConfigName__c, SortOrder__c, Market__c, Leader_Title_Type__c, Context__c From SL_Market_KPIConfig__c Where Leader_Title_Type__c = \''+titleType+'\' AND Context__c includes (\'' +context+ '\') AND Market__c=\''+marketId +'\'order by SortOrder__c';
        System.debug('strQuery:'+strQuery);
        List<SL_Market_KPIConfig__c> marketConfigs;
        try{
            marketConfigs = Database.query(strQuery);
            System.debug('marketConfigs:' + marketConfigs);
        }catch(Exception ex){
            ALMLogUtils.log(ex);
        }
        
        Map<String,SL_KPIConfig__c> mapKPIConfigs = SL_KPIConfig__c.getAll();
        System.debug('mapKPIConfigs:' + mapKPIConfigs);
        
        List<SL_KPIConfig__c> lstKPIConfigs = new List<SL_KPIConfig__c>();
        
        for(SL_Market_KPIConfig__c marketConfig: marketConfigs){
                System.debug('marketConfig.SL_KPIConfigName__c:'+marketConfig.SL_KPIConfigName__c);
                if(mapKPIConfigs.get(marketConfig.SL_KPIConfigName__c) != null){
                    lstKPIConfigs.add(mapKPIConfigs.get(marketConfig.SL_KPIConfigName__c) );
                }   
        }
        
        return lstKPIConfigs;       
    } 
}