youfull/objects/ALM_Rep_Performance_1__c.object
<CustomObject>
    <fields>
        <fullName>ACCT_NR__c</fullName>
        <label>Account Number</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>FLD_SLS_CMPGN_NR__c</fullName>
        <label>Campaign</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Genealogy_Level__c</fullName>
        <label>Genealogy Level</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>MRKT_ACCT_KEY__c</fullName>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>ALM Rep Performance</relationshipLabel>
        <relationshipName>ALM_Rep_Performance_1</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>MRKT_ID__c</fullName>
        <externalId>true</externalId>
        <label>Market Id</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>OPERTNL_CMPGN_NR__c</fullName>
        <label>Campaign</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Personal_Performance_Key__c</fullName>
        <description>MRKT_CMPGN_ACCT_KEY</description>
        <inlineHelpText>MRKT_CMPGN_ACCT_KEY</inlineHelpText>
        <label>Personal Performance Key</label>
        <length>50</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>ALM Rep Performance</label>
    <nameField>
        <label>ALM Rep Performance Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>ALM Rep Performance</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

youfull/objects/Business_Plan__c.object
<CustomObject>
    <fields>
        <fullName>Acct_Nr__c</fullName>
        <label>Acct_Nr</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Business_Plan_Parameter__c</fullName>
        <label>Business Plan Parameter</label>
        <referenceTo>Business_Plan_Parameter__c</referenceTo>
        <relationshipLabel>Business Plans</relationshipLabel>
        <relationshipName>Business_Plans</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>CMPGN_NR__c</fullName>
        <label>Creation Campaign</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Campaign_Numbers__c</fullName>
        <label>Campaign Numbers</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Current_campaign__c</fullName>
        <label>Current campaign</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>FLWUP_MTG_60__c</fullName>
        <label>Follow Up Meetings - 60 days</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>IsDeleted__c</fullName>
        <defaultValue>false</defaultValue>
        <label>IsDeleted</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Is_BP_Saved__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is BP Saved</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Key_Learnings__c</fullName>
        <label>Key Learnings</label>
        <length>500</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>LDRSHP_TITL_ACTN2__c</fullName>
        <label>Leadership Title Advancement - Action 2</label>
        <length>500</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Long_Term_Dreams__c</fullName>
        <label>Long Term Dreams</label>
        <length>500</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Market_Id__c</fullName>
        <label>Market Id</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Mrkt_Id_Acct_Nr_Key__c</fullName>
        <description>Mrkt_Id_Acct_Nr_Key</description>
        <externalId>true</externalId>
        <inlineHelpText>Mrkt_Id_Acct_Nr_Key</inlineHelpText>
        <label>Business Plan Key</label>
        <length>50</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>NEXT_1_CMPGN_NR__c</fullName>
        <label>Creation campaign + 1</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>NEXT_2_CMPGN_NR__c</fullName>
        <label>Creation campaign + 2</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>NEXT_3_CMPGN_NR__c</fullName>
        <label>Creation campaign + 3</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>NEXT_4_CMPGN_NR__c</fullName>
        <label>Creation campaign + 4</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>NEXT_5_CMPGN_NR__c</fullName>
        <label>Creation campaign + 5</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>NEXT_6_CMPGN_NR__c</fullName>
        <label>Creation campaign + 6</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PREV_1_CMPGN_NR__c</fullName>
        <label>Prior campaign</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PRSNL_DEV_PLN_ACTN3__c</fullName>
        <label>Personal Development Plan - Action 3</label>
        <length>500</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Personal_Achievement__c</fullName>
        <label>Personal Achievement</label>
        <length>500</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>RECR_ACTN1__c</fullName>
        <label>Recruiting - Action 1</label>
        <length>500</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>RSNG_STR_DEV_ACTN2__c</fullName>
        <label>Rising Stars Development - Action 2</label>
        <length>500</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Short_Term_Goals__c</fullName>
        <label>Short Term Goals</label>
        <length>500</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>TOP_SLR_ACTN3__c</fullName>
        <label>Top Seller Title Advancement - Action 3</label>
        <length>500</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Unit_Achievement__c</fullName>
        <label>Unit Achievement</label>
        <length>500</length>
        <type>LongTextArea</type>
    </fields>
    <label>Business Plan</label>
    <nameField>
        <displayFormat>BP-{0000000}</displayFormat>
        <label>Business Plan Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Business Plans</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

youfull/objects/Business_Plan_Parameter__c.object
<CustomObject>
    <fields>
        <fullName>Market_Id__c</fullName>
        <label>Market Id</label>
        <referenceTo>Market__c</referenceTo>
        <relationshipLabel>Business Plan Parameters</relationshipLabel>
        <relationshipName>Business_Plan_Parameters</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Business Plan Parameter</label>
    <nameField>
        <label>Business Plan Parameter  Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Business Plan Parameters</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

youfull/objects/Calendar__c.object
<CustomObject>
    <fields>
        <fullName>CMPGN_END_DT__c</fullName>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>CMPGN_NR__c</fullName>
        <label>Campaign Number</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>CMPGN_STRT_DT__c</fullName>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>MRKT_ID__c</fullName>
        <label>Market ID</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Market__c</fullName>
        <label>Market</label>
        <referenceTo>Market__c</referenceTo>
        <relationshipLabel>Calendar</relationshipLabel>
        <relationshipName>Calendar</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Calendar</label>
    <nameField>
        <label>Calendar Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Calendar</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

youfull/objects/Leader_Title__c.object
<CustomObject>
    <fields>
        <fullName>MRKT_ID__c</fullName>
        <label>Market Id</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Market__c</fullName>
        <label>Market</label>
        <referenceTo>Market__c</referenceTo>
        <relationshipLabel>Leader Titles</relationshipLabel>
        <relationshipName>Leader_Titles</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Leader Title</label>
    <nameField>
        <displayFormat>LDT-{000000}</displayFormat>
        <label>Leader Title Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Leader Titles</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

youfull/objects/Market__c.object
<CustomObject>
    <fields>
        <fullName>ALM_Rep_Indicator__c</fullName>
        <label>ALM Rep Indicator</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Allow_Freeform_Email__c</fullName>
        <description>Profile allowed to send freeform emails</description>
        <inlineHelpText>Profile allowed to send freeform emails</inlineHelpText>
        <label>Allow Freeform Email</label>
        <picklist>
            <picklistValues>
                <fullName>Avon Leader</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Avon Zone Manager</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Avon Division Manager</fullName>
            </picklistValues>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <fields>
        <fullName>Business_Plan_KPIs__c</fullName>
        <description>This field decides which KPIs need to be shown in the 90DBP</description>
        <inlineHelpText>This field decides which KPIs need to be shown in the 90DBP</inlineHelpText>
        <label>Business Plan KPIs</label>
        <length>3200</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>CMPGN_END_DT__c</fullName>
        <label>CMPGN_END_DT</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>CMPGN_NR__c</fullName>
        <label>CMPGN_NR</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CMPGN_STRT_DT__c</fullName>
        <label>CMPGN_STRT_DT</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Is_ALMPLUS_Enabled__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Check to enable/disable ALM+ functionality</description>
        <inlineHelpText>Check to enable/disable ALM+ functionality</inlineHelpText>
        <label>Is ALM+ Enabled</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Market_Currency_Symbol__c</fullName>
        <description>it denotes the currency symbol to be used in Coaching record page.</description>
        <label>Market Currency Symbol</label>
        <length>2</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Market_Id__c</fullName>
        <externalId>true</externalId>
        <label>MRKT_ID</label>
        <length>15</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>NEXT_1_CMPGN_NR__c</fullName>
        <label>NEXT_1_CMPGN_NR</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PREV_1_CMPGN_NR__c</fullName>
        <label>PREV_1_CMPGN_NR</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>X90_Day_Camp_CNT__c</fullName>
        <label>90 Day Campaign Count</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Market</label>
    <nameField>
        <label>Market Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Markets</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

youfull/objects/Sales_Leader_History__c.object
<CustomObject>
    <description>This hold up to 7 prior Campaigns&apos; worth of performance and leadership summary data for a Sales Leader or Sales Representative.</description>
    <fields>
        <fullName>ACCT_NR__c</fullName>
        <label>Acct. No.</label>
        <length>35</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>FLD_SLS_CMPGN_NR__c</fullName>
        <label>Campaign Number</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Sales Leader History</label>
    <nameField>
        <label>Sales Leader History Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sales Leader Histories</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

youfull/classes/Test_BusinessPlanController.cls
/**************************************************************************************
 Name         : Test_BusinessPlanController 
 Modified By  : Barkha Jain (JDC)
 Description  : Test class for BusinessPlanControllerNew
 Created Date : Nov 15, 2013     
***************************************************************************************/
@isTest
private class Test_BusinessPlanController {

    static String mktIdKey = '62';
    static String acctNr = '123456';
    static String sURL = '';
    static Market__c mrkt;
    static User testUsr;
    static Leader_Title__c title;
    static Contact con1;
    
    //----------------------------------------------------------------------------
    // Method Name  : testBusinessPlan
    // Description  : Method for Test Coverage of Class : BusinessPlanController
    //----------------------------------------------------------------------------  
    static testMethod void testBusinessPlan() {
        testCreateDataBusinessPlan();
        
        Business_Plan_Parameter__c testBPpar;
        Business_Plan__c businessPlan;
        
        PageReference pageRef1 = Page.BusinessPlan;
        pageRef1.getParameters().put('repDetailAcctNbr', acctNr); 
        pageRef1.getParameters().put('acctkey', acctNr); 
        test.setCurrentPage(pageRef1);
        
        String sUrl1 = Apexpages.currentPage().getURL();
        if(sUrl1.contains('businessplan')) {
            sUrl1 = sUrl1.replace('businessplan', 'BusinessPlan');
        }
        pageRef1 = new PageReference(sUrl1);
        Test.setCurrentPageReference(pageRef1);
        
        test.startTest();
        System.runAs(testUsr) {
            BusinessPlanControllerNew bpCntr1 = new BusinessPlanControllerNew();
            //Create Object: Business_Plan_Parameter__c
            testBPpar = TestDataHelper.createBusinessPlanParameter(mrkt.Id, true);
            
            //Without Creating Business_Plan__c
            bpCntr1.BPAction();
            bpCntr1.callRepDetails();
            system.assertEquals(bpCntr1.isBusinessplan, true);
            
            //Create Object: Business_Plan__c
            businessPlan = TestDataHelper.createBusinessPlan(mrkt.Market_Id__c, testUsr, testBPpar.Id, true);
            
            //After Creating Business_Plan__c and Business_Plan_Parameter__c
            bpCntr1.BPAction();
            bpCntr1.callRepDetails();
            system.assertEquals(bpCntr1.isBusinessplan, true);
        }
        
        ApexPages.currentPage().getParameters().put('AccKey', acctNr);
        System.runAs(testUsr) {
            BusinessPlanControllerNew bpCntr1 = new BusinessPlanControllerNew();
            bpCntr1.coachParam = 'Test';
            bpCntr1.BPAction();
            bpCntr1.callRepDetails();
            system.assertEquals(bpCntr1.isBusinessplan, true);
            
            BusinessPlanControllerNew ctrl = new BusinessPlanControllerNew(new CoachRecordController());
            ctrl.getControllerRef();   
            ctrl.dummy();         
        }
        
        test.stopTest();
    }
    
    //----------------------------------------------------------------------------
    // Method Name  : testBusinessPlanNew
    // Description  : Method for Test Coverage of Class : BusinessPlanController
    //----------------------------------------------------------------------------
    static testMethod void testBusinessPlanNew() {
        testCreateDataBusinessPlan();
        // Creating Business Plan data
        
        PageReference pageRef = Page.BusinessPlan;
        pageRef.getParameters().put('AccKey', acctNr);        
        Test.setCurrentPageReference(pageRef);
                        
        sUrl = Apexpages.currentPage().getURL();
        if (sUrl.contains('businessplan')) {
            sUrl = sUrl.replace('businessplan', 'BusinessPlan');
        }
        
        pageRef = new PageReference(sUrl);
        Test.setCurrentPageReference(pageRef);
        test.startTest();
        System.runAs(testUsr) {
            // Creating Business Plan Parameter data 
            Business_Plan_Parameter__c testBPpar = TestDataHelper.createBusinessPlanParameter(mrkt.Id, true);
            
            //Create Object: Sales_Leader_History__c
            List <Sales_Leader_History__c> salesLeaderList = new List <Sales_Leader_History__c>();
            Sales_Leader_History__c salesLeaderOne = TestDataHelper.createSalesLeaderHistory(con1.Id, false);
            salesLeaderOne.FLD_SLS_CMPGN_NR__c = 191202.0;
            salesLeaderList.add(salesLeaderOne);
            Sales_Leader_History__c salesLeaderTwo = TestDataHelper.createSalesLeaderHistory(con1.Id, false);
            salesLeaderTwo.FLD_SLS_CMPGN_NR__c = 191201.0;
            salesLeaderList.add(salesLeaderTwo);
            insert salesLeaderList;
            
            //Create Objet: Business_Plan__c            
            Business_Plan__c businessPlan = TestDataHelper.createBusinessPlan(mrkt.Market_Id__c, testUsr, testBPpar.Id, false);
            businessPlan.Mrkt_Id_Acct_Nr_Key__c = testUsr.MRKT_ID_ACCT_NR_KEY__c;
            businessPlan.Market_Id__c = mrkt.Market_Id__c;
            businessPlan.IsDeleted__c = false;
            businessPlan.Is_BP_Saved__c = true; 
            businessPlan.PRSNL_DEV_PLN_ACTN3__c = 'TEST_PLN3';
            businessPlan.TOP_SLR_ACTN3__c = 'TEST_TOP_SLR_3';
            businessPlan.Long_Term_Dreams__c = 'TEST_LONTRMDRM';
            businessPlan.RSNG_STR_DEV_ACTN2__c = 'TEST_RSNGSTAR_ACT';
            businessPlan.FLWUP_MTG_60__c = System.today(); 
            businessPlan.Personal_Achievement__c = 'TEST_PRSN_ACHV';
            businessPlan.LDRSHP_TITL_ACTN2__c = 'TEST_LDR_TITLE';
            businessPlan.Short_Term_Goals__c = 'TEST_SHRT_GL';
            businessPlan.Unit_Achievement__c = 'TEST_UNT_ACHV';
            businessPlan.Key_Learnings__c = 'TEST_KEY_LRNG';
            businessPlan.RECR_ACTN1__c = 'TEST_RECR_ACT_1'; 
            businessPlan.Campaign_Numbers__c = '191202.0;191203.0;191204.0;191205.0;191206.0;191207.0;191208.0;191209.0;191210.0;191211.0;191212.0';
            businessPlan.CMPGN_NR__c = '191203.0';
            businessPlan.Current_campaign__c = '191203.0'; 
            businessPlan.NEXT_1_CMPGN_NR__c = '191204.0'; 
            businessPlan.NEXT_2_CMPGN_NR__c = '191204.0'; 
            businessPlan.NEXT_3_CMPGN_NR__c = '191205.0'; 
            businessPlan.NEXT_4_CMPGN_NR__c = '191206.0'; 
            businessPlan.NEXT_5_CMPGN_NR__c='191207.0'; 
            businessPlan.NEXT_6_CMPGN_NR__c = '191208.0';
            businessPlan.Business_Plan_Parameter__c = testBPpar.Id; 
            insert businessPlan;
            
            BusinessPlanControllerNew bpCntr = new BusinessPlanControllerNew();
            bpCntr.isBlankPlan = true;            
            bpCntr.BPAction();          
            bpCntr.savePage();            
            bpCntr.shortTermGoals = 'short';
            bpCntr.longTermGoals = 'long';
            bpCntr.personalAcheivementPY = 'personal';
            bpCntr.unitAcheivementPY = 'unit';
            bpCntr.keyLearnings = 'key';
            bpCntr.recruiting_ActStr1 = 'testact';
            bpCntr.recruiting_ActStr2 = 'testact';
            bpCntr.recruiting_ActStr3 = 'testact';
            bpCntr.activity_ActStr1 = 'testact';
            bpCntr.activity_ActStr2 = 'testact';
            bpCntr.activity_ActStr3 = 'testact';
            bpCntr.topSeller_ActStr1 = 'testact';
            bpCntr.topSeller_ActStr2 = 'testact';
            bpCntr.topSeller_ActStr3 = 'testact';
            bpCntr.topSeller_Candidates = 'testact';
            bpCntr.leadership_ActStr1 = 'testact';
            bpCntr.leadership_ActStr2 = 'testact';
            bpCntr.leadership_ActStr3 = 'testact';
            bpCntr.leadership_Candidates = 'testact';
            bpCntr.perDev_ActStr1 = 'testact';
            bpCntr.perDev_ActStr2 = 'testact';
            bpCntr.perDev_ActStr3 = 'testact';
            bpCntr.perDev_ActStr4 = 'testact';
            bpCntr.perDev_ActStr5 = 'testact';
            bpCntr.perDev_ActStr6 = 'testact';
            bpCntr.rising_ActStr1 = 'testact';
            bpCntr.rising_ActStr2 = 'testact';
            bpCntr.rising_ActStr3 = 'testact';
            bpCntr.rising_Candidates = 'testact';
            bpCntr.followup30 = '08/01/2012';
            bpCntr.followup60 = '09/01/2012';
            bpCntr.followup90 = '10/01/2012';
            
            bpCntr.savePage();            
            bpCntr.BPAction();
            bpCntr.cancelChanges();            
            bpCntr.startNewPlan();            
            bpCntr.processPage();             
            bpCntr.savePage();          
            bpCntr.getOmniturePageName();
        }
        test.stopTest();
    }
    
    //----------------------------------------------------------------------------
    // Method to create test data
    //----------------------------------------------------------------------------
    static void testCreateDataBusinessPlan() {
        List<User> users = new List<User>();
        //Create and Insert Object : User
        testUsr = TestDataHelper.createUser(acctNr, 'XZ1', 'Avon Leader', false);
        testUsr.MRKT_ID_ACCT_NR_KEY__c = mktIdKey + acctNr;
        testUsr.MRKT_ID__c = mktIdKey;
        users.add(testUsr);
        User zmUsr = TestDataHelper.createUser(acctNr+'1', 'XZ1', 'Avon Mkt 62 Zone Manager', false);
        zmUsr.MRKT_ID__c = mktIdKey;
        users.add(zmUsr);
        User dmUsr = TestDataHelper.createUser(acctNr+'2', 'XZ1', 'Avon Mkt 62 Division Manager', false);
        dmUsr.MRKT_ID__c = mktIdKey;
        users.add(dmUsr);
        insert users;
        
        //Create and Insert Object : Market
        mrkt = TestDataHelper.createMarket(mktIdKey, false);
        mrkt.Allow_Freeform_Email__c = 'Avon Leader; Avon Division Manager';
        mrkt.Market_Currency_Symbol__c = '₱';
        mrkt.OwnerId = testUsr.Id;
        mrkt.Is_ALMPLUS_Enabled__c = true;
        mrkt.ALM_Rep_Indicator__c = 'ALM_Rep_Performance_1__c';
        mrkt.X90_Day_Camp_CNT__c = 6;
        mrkt.Business_Plan_KPIs__c = 'Personal_Volume_dollar;Personal_Appointments;Qualified_Personal_Appointments;G1_Removals;G1_Active_Representatives;G1_Activity_Rate;Total_Unit_Sales_dollor;';
        mrkt.CMPGN_NR__c = '191203';
        mrkt.NEXT_1_CMPGN_NR__c = '191204';
        mrkt.PREV_1_CMPGN_NR__c = '191202';
        mrkt.CMPGN_STRT_DT__c = date.valueOf('1912-04-02');
        mrkt.CMPGN_END_DT__c = date.valueOf('1912-04-30');
        insert mrkt;
        
        // Create Object: Leader Title
        title = TestDataHelper.createLeaderTitle(mrkt.Id, mrkt.Market_Id__c, true);
        
        //create Object: Calendar
        List <Calendar__c> calendars = new List <Calendar__c>();
        List <String> perPerfKeys = new List <String>();
        List <String> acctNbrLst = new List <String>();
        for (Integer i = 191201; i < 191212; i++) {
            //calendars
            Calendar__c tempFutCal = TestDataHelper.createCalendar(i, mrkt.Market_Id__c, 1912, mrkt.Id, false);
            calendars.add(tempFutCal);
            String ppkey = mrkt.Market_Id__c + String.valueOf(i) + '636363';
            acctNbrLst.add(String.valueOf(i) + '636363');
            perPerfKeys.add(ppkey);
        }
        
        for (Integer j = 191109; j < 191116; j++) {
            Calendar__c tempHistCal = TestDataHelper.createCalendar(j, mrkt.Market_Id__c, 1911, mrkt.Id, false);
            calendars.add(tempHistCal);
            String ppkey = mrkt.Market_Id__c + String.valueOf(j) + '636363';
            perPerfKeys.add(ppkey);
        }
        insert calendars;
        
        TestDataHelper.createALMGlobalSetting(true);
        //Create Object: Account
        Account acct = TestDataHelper.createAccount('Test Account', 'USD', true);
        
        //Create Object: Contact
        List <Contact> lstContact = new List <Contact>();
        con1 = TestDataHelper.createContact(mktIdKey, acct.Id, false);
        con1.OwnerId = testUsr.Id;
        con1.MRKT_ACCT_KEY__c = mktIdKey + testUsr.ACCT_NR__c;      
        lstContact.add(con1);
         
        Contact con2 = TestDataHelper.createContact(mktIdKey + '01', acct.Id, false);
        con2.OwnerId = testUsr.Id;
        lstContact.add(con2);
        Contact con3 = TestDataHelper.createContact('XX' + '02', acct.Id, false);
        con3.OwnerId = testUsr.Id;
        lstContact.add(con3);
        Contact con4 = TestDataHelper.createContact('XX' + '03', acct.Id, false);
        con4.OwnerId = testUsr.Id;
        lstContact.add(con4);
        
        insert lstContact;    
        
        // Insert ALM Rep Performance records for each contact for each campaign
        List <ALM_Rep_Performance_1__c> lstRepPerf = new List <ALM_Rep_Performance_1__c>();
        ALM_Rep_Performance_1__c rep1 = TestDataHelper.createRepPerformance(con1.Id, mrkt, mktIdKey, false);
        rep1.Name = 'Test REP1';
        rep1.ACCT_NR__c = mktIdKey;
        rep1.Genealogy_Level__c = 0;
        rep1.CurrencyISOCode = 'USD';
        rep1.MRKT_ID__c = mrkt.Market_ID__c;
        rep1.MRKT_ACCT_KEY__c = lstContact[0].Id;
        rep1.FLD_SLS_CMPGN_NR__c = Decimal.valueOf(mrkt.CMPGN_NR__c);
        rep1.OPERTNL_CMPGN_NR__c = mrkt.CMPGN_NR__c;
        rep1.Personal_Performance_Key__c = mrkt.Market_Id__c + mrkt.CMPGN_NR__c + mktIdKey;
        rep1.REP_OMS_STUS_CD__c = '1';
        rep1.AVON_LOA_1_6_IND__c = 'Y';
        rep1.LDRSHP_LOA_NR__c = 1;
        rep1.LDRSHP_TITL_LVL_NR__c = '1';
        rep1.ROOT_UPLN_ACCT_NR__c = mktIdKey;
        rep1.LFT_ND_ID__c = 1;
        rep1.RGT_ND_ID__c = 8;
        lstRepPerf.add(rep1);
        
        ALM_Rep_Performance_1__c rep2 = TestDataHelper.createRepPerformance(con1.Id, mrkt, mktIdKey, false);
        rep2.Name = 'Test REP1'; 
        rep2.ACCT_NR__c = mktIdKey + '01';
        rep2.UPLN_ACCT_NR__c = mktIdKey;
        rep2.Genealogy_Level__c = 1;
        rep2.CurrencyISOCode = 'USD';
        rep2.MRKT_ID__c = mrkt.Market_ID__c;
        rep2.MRKT_ACCT_KEY__c = lstContact[1].Id;
        rep2.FLD_SLS_CMPGN_NR__c = Decimal.valueOf(mrkt.CMPGN_NR__c);
        rep2.OPERTNL_CMPGN_NR__c = mrkt.CMPGN_NR__c;
        rep2.Personal_Performance_Key__c = mrkt.Market_Id__c + mrkt.CMPGN_NR__c + mktIdKey + '01';
        rep2.REP_OMS_STUS_CD__c = '1';
        rep2.AVON_LOA_1_6_IND__c = 'Y';
        rep2.LDRSHP_LOA_NR__c = 1;
        rep2.LDRSHP_TITL_LVL_NR__c = '1';
        rep2.ROOT_UPLN_ACCT_NR__c = mktIdKey;
        rep2.UPLN_ACCT_KEY__c = con1.Id;
        rep2.LFT_ND_ID__c = 0;
        rep2.RGT_ND_ID__c = 9;
        lstRepPerf.add(rep2);
        
        insert lstRepPerf;
        
        //Create Object: X90DBP_settings__c
        List <X90DBP_settings__c> x90DBPList = new List <X90DBP_settings__c>();
        X90DBP_settings__c x90DBPOne = TestDataHelper.createX90DBPSetting('X90DBP1', 'Personal_Volume_dollar', false);
        x90DBPOne.isHeader__c = 'true';
        x90DBPList.add(x90DBPOne);
        
        X90DBP_settings__c x90DBPTwo = TestDataHelper.createX90DBPSetting('X90DBP2', 'Personal_Appointments', false);
        x90DBPTwo.isFuture__c = 'false';
        x90DBPList.add(x90DBPTwo);
        
        X90DBP_settings__c x90DBPThree = TestDataHelper.createX90DBPSetting('X90DBP3', 'Qualified_Personal_Appointments', false);
        x90DBPList.add(x90DBPThree);
        
        X90DBP_settings__c x90DBPFour = TestDataHelper.createX90DBPSetting('X90DBP4', 'G1_Removals', false);
        x90DBPList.add(x90DBPFour);
        
        X90DBP_settings__c x90DBPFive = TestDataHelper.createX90DBPSetting('X90DBP5', 'G1_Active_Representatives', false);
        x90DBPList.add(x90DBPFive);
        
        X90DBP_settings__c x90DBPSix = TestDataHelper.createX90DBPSetting('X90DBP6', 'G1_Activity_Rate', false);
        x90DBPList.add(x90DBPSix);
        
        X90DBP_settings__c x90DBPSeven = TestDataHelper.createX90DBPSetting('X90DBP7', 'Total_Unit_Sales_dollor', false);
        x90DBPList.add(x90DBPSeven);
        insert x90DBPList;
                 
        //Create Object: Locale_Date_Format__c
        Locale_Date_Format__c locale = TestDataHelper.createLocaleDateFormat(true);
    }    
}