youfull/objects/ALM_Rep_Performance_1__c.object
<CustomObject>
    <fields>
        <fullName>ACCT_NR__c</fullName>
        <label>Account Number</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>FLD_SLS_CMPGN_NR__c</fullName>
        <label>Campaign</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Genealogy_Key__c</fullName>
        <externalId>true</externalId>
        <label>Genealogy Key</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>LDRSHP_TITL_LVL_NR_NUMBER__c</fullName>
        <description>LDRSHP_TITL_LVL_NR__c converted into a number</description>
        <formula>VALUE( LDRSHP_TITL_LVL_NR__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>LDRSHP_TITL_LVL_NR__c converted into a number</inlineHelpText>
        <label>Level Title Number</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>LDRSHP_TITL_LVL_NR__c</fullName>
        <label>Badge Title (Achieved Title)</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>LFT_ND_ID__c</fullName>
        <label>Sort</label>
        <precision>12</precision>
        <scale>6</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>MRKT_ID__c</fullName>
        <externalId>true</externalId>
        <label>Market Id</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>REP_OMS_STUS_CD__c</fullName>
        <inlineHelpText>1=Staff, 0=removed, -2=Recruit</inlineHelpText>
        <label>Rep Status</label>
        <length>5</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>RGT_ND_ID__c</fullName>
        <label>Right Node Id</label>
        <precision>12</precision>
        <scale>6</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>ROOT_UPLN_ACCT_NR__c</fullName>
        <label>Root Upline Account</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <label>ALM Rep Performance</label>
    <nameField>
        <label>ALM Rep Performance Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>ALM Rep Performance</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

youfull/objects/Leader_Title__c.object
<CustomObject>
    <fields>
        <fullName>LANG_CD__c</fullName>
        <label>Language</label>
        <picklist>
            <picklistValues>
                <fullName>en_US</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>fr</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ro</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>pl</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>hu</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ru</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>cs</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>es_MX</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>es</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>uk</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>sh</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>sk</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>en_MY</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>en_IN</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>bg</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>en_PH</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>en_GB</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>fr_CA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>en_CA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>en_AU</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>fi</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>pt_BR</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>sl</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ka</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>et</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>lv</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>lt</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>th</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>LCL_LDRSHP_TITL_LANG_DESC_TXT__c</fullName>
        <label>Title Description</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>LDRSHP_TITL_LVL_NR_NUMBER__c</fullName>
        <formula>VALUE( TEXT(LDRSHP_TITL_LVL_NR__c ))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Leader Title Level Num 2 Num</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>LDRSHP_TITL_LVL_NR__c</fullName>
        <label>Title Level Number</label>
        <picklist>
            <picklistValues>
                <fullName>UQ</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>-2</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>0</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>3</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>4</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>5</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>21</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>6</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>7</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>8</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>9</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>10</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>MRKT_ID__c</fullName>
        <label>Market Id</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Market__c</fullName>
        <label>Market</label>
        <referenceTo>Market__c</referenceTo>
        <relationshipLabel>Leader Titles</relationshipLabel>
        <relationshipName>Leader_Titles</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Leader Title</label>
    <nameField>
        <displayFormat>LDT-{000000}</displayFormat>
        <label>Leader Title Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Leader Titles</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

youfull/objects/Market__c.object
<CustomObject>
    <fields>
        <fullName>ALM_Rep_Indicator__c</fullName>
        <label>ALM Rep Indicator</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CMPGN_NR__c</fullName>
        <label>CMPGN_NR</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Mail_Plan_Enabled__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Mail Plan Enabled</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Market_Id__c</fullName>
        <externalId>true</externalId>
        <label>MRKT_ID</label>
        <length>15</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Mgr_Omniture_Suite_Name__c</fullName>
        <description>This Suite is used for ZM/DM Omniture tracking.</description>
        <label>Mgr Omniture Suite Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>NEXT_1_CMPGN_NR__c</fullName>
        <label>NEXT_1_CMPGN_NR</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Omniture_Suite_Name__c</fullName>
        <label>Omniture Suite Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PREV_1_CMPGN_NR__c</fullName>
        <label>PREV_1_CMPGN_NR</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <label>Market</label>
    <nameField>
        <label>Market Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Markets</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

youfull/objects/ZM_Report_Translation__c.object
<CustomObject>
    <fields>
        <fullName>Application_Context__c</fullName>
        <label>Application Context</label>
        <picklist>
            <picklistValues>
                <fullName>Quick Links</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Report Center</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>My Team Orders</fullName>
            </picklistValues>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <fields>
        <fullName>Language_Code__c</fullName>
        <label>Language Code</label>
        <picklist>
            <picklistValues>
                <fullName>en_PH</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>en_US</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ro</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>es</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>es_MX</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>en_GB</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>MRKT_ID__c</fullName>
        <description>To relate to the Market Object</description>
        <label>Market</label>
        <referenceTo>Market__c</referenceTo>
        <relationshipLabel>ZM Report Market Translations</relationshipLabel>
        <relationshipName>ZM_Report_Market_Translations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Market_Id__c</fullName>
        <label>Market Id</label>
        <picklist>
            <picklistValues>
                <fullName>62</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>66</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>100</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>999</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>55</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>23</fullName>
            </picklistValues>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <fields>
        <fullName>Report_Id__c</fullName>
        <label>Report Id</label>
        <length>18</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Report_Label__c</fullName>
        <label>Report Label</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Report_Role__c</fullName>
        <label>Report Role</label>
        <picklist>
            <picklistValues>
                <fullName>Zone</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Division</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Admin</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Training</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Standard Leader</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sales</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Report_URL__c</fullName>
        <label>Report URL</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Sort_Order__c</fullName>
        <label>Sort Order</label>
        <precision>3</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>ZM Report Market Translation</label>
    <nameField>
        <label>ZM Report Translation Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>ZM Report Market Translations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

youfull/classes/POC_Controller_TitleAdvancement.cls
/***************************************************************************
 Name          : POC_Controller_TitleAdvancement 
 Created By    : Fay Salwen 
 Description   : POC of Title Advancement Controller 
 Created Date  : Dec 20, 2013                
****************************************************************************/

public with sharing class POC_Controller_TitleAdvancement {
	
    private User currentUser;
    public String userProfile {get;set;}
    private Market__c market;
    private ALM_Rep_Performance_1__c repPerformance;
    
    private List<SelectOption> campaignList = new List<SelectOption>();    
    private List<SelectOption> titleList = new List<SelectOption>();
    private List<SelectOption> reportList = new List<SelectOption>();
    private List<SelectOption> searchTypeList = new List<SelectOption>();

    public String selectedCampaign {get; set;}
    public String selectedTitle {get; set;}
    public Id selectedReport {get; set;}
    public String selectedSearchType {get; set;}
    public String searchString {get; set;}
    
    private AnalyticReportParser reportParser;
 
	//==============================================================================================//
  	//Constructor
  	//==============================================================================================//
    public POC_Controller_TitleAdvancement() {   

        initializeData();  
        
        /*
        if (market.Mail_Plan_Enabled__c) {
        	List<Sobject> list = MailPlanUtils.getRepPerf_MailPlan(mkt.ALM_Rep_Indicator__c, usr.ACCT_NR__c, usr.MRKT_ID__c);  
        	this.selectedStandard = getMailPlanCampaign(lst_CombinedObj);
        }
        */
        
    }

	//==============================================================================================//
  	//Initialize the user, market, report, title data
  	//==============================================================================================//    
    private void initializeData() {
        // Initialize user
        currentUser = [SELECT Id, Profile.Name, MRKT_ID__c, ACCT_NR__c, DFALT_DIV_NM__c, DFALT_ZONE_CD__c, User.LanguageLocaleKey, UserRole.Name 
                from User WHERE Id = :UserInfo.getUserId() LIMIT 1];
        userProfile = currentUser.Profile.Name;
            
        // Initialize market
        this.market = [SELECT Id, Market_Id__c, PREV_1_CMPGN_NR__c, Mail_Plan_Enabled__c, CMPGN_NR__c, NEXT_1_CMPGN_NR__c,  
                       Omniture_Suite_Name__c, Mgr_Omniture_Suite_Name__c  FROM Market__c 
                        where Market_Id__c = :currentUser.MRKT_ID__c];
                        
        //Set the campaign number.  For now, just use operational.  Will need to be modified for Mailplan handling.
        this.selectedCampaign = this.market.CMPGN_NR__c;
       
		// Initialize repPerformance
		String genealogyKey = this.market.Market_Id__c + selectedCampaign + currentUser.ACCT_NR__c;
        system.debug('---------------- genealogyKey-------------------'+genealogyKey);
		this.repPerformance = [SELECT Id, ACCT_NR__c, FLD_SLS_CMPGN_NR__c, ROOT_UPLN_ACCT_NR__c, LFT_ND_ID__c, RGT_ND_ID__c, REP_OMS_STUS_CD__c, LDRSHP_TITL_LVL_NR_NUMBER__c
										From ALM_Rep_Performance_1__c
										Where Genealogy_Key__c = :genealogyKey limit 1];
		     
        // Initialize the list of reports
        for(ZM_Report_Translation__c z : [Select z.Sort_Order__c
                                               , z.Report_URL__c
                                               , z.Report_Label__c
                                               , z.Report_Id__c
                                               , z.Market_Id__c
                                               , z.Language_Code__c
                                               , z.Id
                                               , z.Application_Context__c
                                               , z.Report_Role__c 
                                            From ZM_Report_Translation__c z
                                           where Language_Code__c = :currentUser.LanguageLocaleKey
                                            and Market_Id__c includes(:currentUser.MRKT_ID__c)
                                            and Application_Context__c includes ('Title Advancement')
                                           order by sort_order__c]){
                                           	
            if(currentUser.Profile.Name == null || currentUser.Profile.Name.containsIgnoreCase(z.Report_Role__c))
                reportList.add(new SelectOption(z.Report_Id__c, z.Report_Label__c));
                 
        }
        
        //Initialize the list of titles
        titleList.add(new SelectOption('0,1,2,3,4', 'All Paid Titles'));
        for(Leader_Title__c t : [Select t.Market__c, t.LANG_CD__c, t.LDRSHP_TITL_LVL_NR__c, t.LDRSHP_TITL_LVL_NR_NUMBER__c, LCL_LDRSHP_TITL_LANG_DESC_TXT__c
        									From Leader_Title__c t
        									where LANG_CD__c = :currentUser.LanguageLocaleKey
        									and Market__c = :this.market.Id
        									order by Market__c, LANG_CD__c, LDRSHP_TITL_LVL_NR_NUMBER__c]) {
        	titleList.add(new SelectOption(t.LDRSHP_TITL_LVL_NR__c, t.LCL_LDRSHP_TITL_LANG_DESC_TXT__c));
       	}

    }
    
	//==============================================================================================//
  	//Dummy placeholder method
  	//==============================================================================================//
    public void doNothing(){ }

	//==============================================================================================//
  	//Use data on Market to provide a list of SelectOptions for prior, current, and next campaign
  	//==============================================================================================//    
	public List<SelectOption> getCampaignList() {      
        List<SelectOption> options = new List<SelectOption>();        
        options.add(new SelectOption(market.PREV_1_CMPGN_NR__c, market.PREV_1_CMPGN_NR__c)); // Prior
        options.add(new SelectOption(market.CMPGN_NR__c, market.CMPGN_NR__c)); 				 // Current
        options.add(new SelectOption(market.NEXT_1_CMPGN_NR__c, market.NEXT_1_CMPGN_NR__c)); // Next
        return options;
    }
    
	//==============================================================================================//
  	//Use cached data from Leader_Title__c to provide a list of SelectOptions for the different Leader Title levels
  	//==============================================================================================//    
	public List<SelectOption> getTitleList() {
        return titleList;
    }

	//==============================================================================================//
  	//Use cached data from ZM_Report_Translation__c to provide a list of SelectOptions to represent the different Reports
  	//==============================================================================================//          
    public List<SelectOption> getReportList() {
        return reportList;
    }
    
	//==============================================================================================//
  	//Provide a static list of SelectOptions for the search types, namely Name and Account
  	//==============================================================================================//    
	public List<SelectOption> getSearchTypeList() {      
        List<SelectOption> options = new List<SelectOption>();        
        options.add(new SelectOption('Full Name', 'Full Name'));
        options.add(new SelectOption('Account Number', 'Account Number'));
        return options;
    }
    
	//==============================================================================================//
  	//Get the list of parameters to be sent to the report for filtering
  	//==============================================================================================//    
	public List<String> getReportArgumentList() {
      List<String> arguments = new List<String>();
      arguments.add(this.market.Market_Id__c);
      arguments.add(this.selectedCampaign);
      arguments.add(this.currentUser.ACCT_NR__c);
      arguments.add(this.repPerformance.ROOT_UPLN_ACCT_NR__c);
      arguments.add(String.valueOf(this.repPerformance.LFT_ND_ID__c));
      arguments.add(String.valueOf(this.repPerformance.RGT_ND_ID__c));
      arguments.add('1');
      arguments.add(this.selectedTitle);
      if(searchString != null && searchString.trim() != ''){
      	arguments.add(selectedSearchType);
      	arguments.add(searchString);
      }
      return arguments;
	}
	
    //=================================================================//
    //Get report data through analytics api call
    //=================================================================//
    public PageReference getReportData() {
      IalmReportService reportCallout = almAnalyticsAPIImp.getInstance();
      String sfdcServerName = Apexpages.currentpage().getheaders().get('X-Salesforce-Forwarded-To');
      // URL.getSalesforceBaseUrl().toExternalForm()
      if(String.isBlank(sfdcServerName)) {
        sfdcServerName = 'prerelna1.pre.salesforce.com';
      }      
      System.debug('---------------- this.selectedReportID-------------------'+this.selectedReport);

      String json = reportCallout.getAnalyticsReportResponse(sfdcServerName, this.selectedReport, null, null);
      reportParser = new AnalyticReportParser(json);
      return null;
    }
  
    //=================================================================//
    //Get report data into apex:datatable
    //=================================================================//
    public Component.Apex.DataTable getReportDataTable(){
      /*if(reportParser != null){
      Component.Apex.DataTable tbl = reportParser.getVFDataTable();
      return tbl;
      }else{*/
        return null;
      //}
    }
    
}