youfull/objects/ALM_Rep_Performance_1__c.object
<CustomObject>
    <fields>
        <fullName>Genealogy_Key__c</fullName>
        <externalId>true</externalId>
        <label>Genealogy Key</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>MRKT_ID__c</fullName>
        <externalId>true</externalId>
        <label>Market Id</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>MailPlan_Order_Oppty__c</fullName>
        <description>Lookup to corresponding record of MailPlan_Order_Oppty</description>
        <inlineHelpText>Lookup to corresponding record of MailPlan_Order_Oppty</inlineHelpText>
        <label>MailPlan_Order_Oppty</label>
        <referenceTo>MailPlan_Order_Oppty__c</referenceTo>
        <relationshipLabel>ALM Rep Performance</relationshipLabel>
        <relationshipName>ALM_Rep_Performance</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SLS_ZONE_CD__c</fullName>
        <label>Zone</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>UPLN_ACCT_KEY__c</fullName>
        <description>Lookup field to contact to be clickable in reports</description>
        <label>Upline/Sponsor</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>ALM Rep Performance (Upline/Sponsor)</relationshipLabel>
        <relationshipName>ALM_Rep_Performance</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>ALM Rep Performance</label>
    <nameField>
        <label>ALM Rep Performance Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>ALM Rep Performance</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

youfull/objects/Code_Execution_Time__c.object
<CustomObject>
    <fields>
        <fullName>Called_From__c</fullName>
        <label>Called From</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Component_Name__c</fullName>
        <label>Component Name</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Component_Type__c</fullName>
        <label>Component Type</label>
        <length>128</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>End_Time__c</fullName>
        <label>End Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Start_Time__c</fullName>
        <label>Start Time</label>
        <required>true</required>
        <type>DateTime</type>
    </fields>
    <label>Code Execution Time</label>
    <nameField>
        <displayFormat>EXE-{0000}</displayFormat>
        <label>Code_Execution_Time Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Code Execution Time</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

youfull/objects/MailPlan_Order_Oppty__c.object
<CustomObject>
    <fields>
        <fullName>CMPGN_NR__c</fullName>
        <label>CMPGN_NR</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CURRNT_NEXT_CMPGN_PRFX_CD__c</fullName>
        <label>CURRNT_NEXT_CMPGN_PRFX_CD</label>
        <length>1</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>MLPLN_END_DT__c</fullName>
        <label>MLPLN_END_DT</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>MRKT_ID__c</fullName>
        <label>MRKT_ID</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Market__c</fullName>
        <label>Market</label>
        <referenceTo>Market__c</referenceTo>
        <relationshipLabel>MailPlan_Order_Opptys</relationshipLabel>
        <relationshipName>MailPlan_Order_Opptys</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>SLS_ZONE_CD__c</fullName>
        <label>SLS_ZONE_CD</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <label>MailPlan_Order_Oppty</label>
    <nameField>
        <displayFormat>MPLN-{000000}</displayFormat>
        <label>Mail Plan Order Oppty Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>MailPlan_Order_Opptys</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

youfull/objects/Market__c.object
<CustomObject>
    <fields>
        <fullName>Batch_Load_In_Process__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Flag to be set by CDW when starting the nightly batch and reset after its complete.</description>
        <inlineHelpText>Flag to be set by CDW when starting the nightly batch and reset after its complete.</inlineHelpText>
        <label>Batch Load In Process</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Batch_Load_Strt_Dt__c</fullName>
        <description>The date time when CDW started the batch process. This field is set by a workflow rule based on the flag value.</description>
        <label>Batch Load Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>CMPGN_NR__c</fullName>
        <label>CMPGN_NR</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>LAST_UPDT_DT__c</fullName>
        <label>LAST_UPDT_DT</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Mail_Plan_Enabled__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Mail Plan Enabled</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Market_Id__c</fullName>
        <externalId>true</externalId>
        <label>MRKT_ID</label>
        <length>15</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>NEXT_1_CMPGN_NR__c</fullName>
        <label>NEXT_1_CMPGN_NR</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>NRT_Enabled__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Flag to determine, if this market is participating in NRT or not.</description>
        <label>NRT Enabled</label>
        <type>Checkbox</type>
    </fields>
    <label>Market</label>
    <nameField>
        <label>Market Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Markets</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

youfull/classes/NRT_Utils.cls
global class NRT_Utils {
    /*
    @future
    global static void setAlmGroupSalesINdicator(set<String> genealogyKeys)
    {
         //collect the Ids for the parent records
         list<Id> parentAlmList2 = new list<Id>();
         list<Id> parentAlmList3 = new list<Id>();
         list<ALM_Rep_Performance_1__c> ggpAlmList = new list<ALM_Rep_Performance_1__c>();
         
         //get the first level parents
         for(ALM_Rep_Performance_1__c alm : [Select Id, UPLN_ACCT_KEY__c 
                                               from ALM_Rep_Performance_1__c
                                              where Genealogy_Key__c in :genealogyKeys])
              parentAlmList2.add(alm.UPLN_ACCT_KEY__c);
              
         //get the grand parents
         for(ALM_Rep_Performance_1__c alm : [Select Id, Group_Sales_Indicator__c, UPLN_ACCT_KEY__c 
                                               from ALM_Rep_Performance_1__c
                                              where Id in :parentAlmList2])
         {
              alm.Group_Sales_Indicator__c = true;
              parentAlmList3.add(alm.UPLN_ACCT_KEY__c);  
              
         } 
         
          //get the great-grand parents
         for(ALM_Rep_Performance_1__c alm : [Select Id, Group_Sales_Indicator__c, UPLN_ACCT_KEY__c 
                                               from ALM_Rep_Performance_1__c
                                              where Group_Sales_Indicator__c = false
                                                and Id in :parentAlmList3])
         {
              alm.Group_Sales_Indicator__c = true;
              ggpAlmList.add(alm);  
              
         }   
         
         if(ggpAlmList.size() > 0)
            update ggpAlmList;                           
    }
    
    global static void executeBatchOrderProcess(String caller)
    {
        Integer jobCount = 0;
        for(AsyncApexJob aj : [Select a.Status, a.CompletedDate, a.ApexClass.Name, a.ApexClassId 
                                 From AsyncApexJob a
                                where a.ApexClass.Name = 'ALM_BatchOrderProcessor'
                                  and Status != 'Completed'
                                  and Status != 'Aborted'])
           jobCount++;
           
        if(jobCount == 0)
        {
            for(Order_Stage__c os : [select Id from Order_Stage__c limit 1])
            {
                ALM_BatchOrderProcessor abp = new ALM_BatchOrderProcessor(caller);
                Database.executeBatch(abp,2000);
            }
        }
            
    }
    */
    global static Id logTransactionStart( String    calledFrom
                                          ,String   componentName
                                          ,String   componentType
                                          ,DateTime startTime)
    {
        Code_Execution_Time__c c = new Code_Execution_Time__c(Called_From__c = calledFrom
                                                             ,Component_Name__c = componentName
                                                             ,Component_Type__c = componentType
                                                             ,Start_Time__c = startTime);
        insert c;
        
        return c.Id;
            
    }
    
    global static void logTransactionEnd(Id codeExecutionTimeId
                                        ,DateTime   endTime)
    {
        Code_Execution_Time__c c = new Code_Execution_Time__c(Id = codeExecutionTimeId
                                                             ,End_Time__c = endTime);
        update c;
            
    }
    
    global static boolean isBatchLoadInProcess()
    {
        User u = [select Id, MRKT_ID__c from User where Id = :UserInfo.getUserId()];
        
        for(Market__c m : [Select Batch_Load_In_Process__c from Market__c where Market_Id__c = :u.MRKT_ID__c])
           return m.Batch_Load_In_Process__c;
           
        return null;
    }
    
    global static DateTime getBatchLoadStarted()
    {
        User u = [select Id, MRKT_ID__c from User where Id = :UserInfo.getUserId()];
        
        for(Market__c m : [Select Batch_Load_Strt_Dt__c from Market__c where Market_Id__c = :u.MRKT_ID__c])
           return m.Batch_Load_Strt_Dt__c;
           
        return null;
    }
    
    global static boolean isNrtEnabled()
    {
        User u = [select Id, MRKT_ID__c from User where Id = :UserInfo.getUserId()];
        
        for(Market__c m : [Select NRT_Enabled__c from Market__c where Market_Id__c = :u.MRKT_ID__c])
           return m.NRT_Enabled__c;
           
        return null;
    }
    
    /**
        * This method will return current campaign for MP/non MP market
        * This method accepts 2 parameters:
        * Market - it needs to have Mail_Plan_Enabled__c, CMPGN_NR__c, Market_Id__c field
        * User - It needs to have DFALT_ZONE_CD__c field
    **/
    global static string getCurrentCampaign(Market__c mkt, User usr)
    {
        String cmpgn = '';
        if(mkt.Mail_Plan_Enabled__c)       
        {
            try
            {
                //Date currDate = System.today();
                DateTime d = datetime.now();
                String timeStr = d.format('yyyy-MM-dd');
                
                String query_str = 'SELECT Id, CMPGN_NR__c, MRKT_ID__c, MLPLN_END_DT__c';
                
                query_str+=' FROM MailPlan_Order_Oppty__c';
                
                String whereClause = ' WHERE SLS_ZONE_CD__c=\''+usr.DFALT_ZONE_CD__c+'\' AND MRKT_ID__c=\''+mkt.Market_Id__c+'\' and CURRNT_NEXT_CMPGN_PRFX_CD__c=\'C\'';               
                whereClause+=' AND MLPLN_END_DT__c >= '+timeStr+' ORDER BY MLPLN_END_DT__c ';
                
                String limitClause = 'Limit 1';
                
                query_str = query_str+whereClause+limitClause;
                
                System.debug('\n ======= MailPlanUtil.query_str SL ======= \n'+query_str);
                List<MailPlan_Order_Oppty__c> lst_mpoo= Database.query(query_str);
                
                if (!lst_mpoo.isEmpty()) {
                    cmpgn = YOUUtil.getCampaignNumbrMailPlan((String)lst_mpoo[0].get('CMPGN_NR__c'));
                }
                else {
                    cmpgn = mkt.CMPGN_NR__c;
                }
            }
            catch(exception e)
            {
                System.debug('exception in class NRT_Utils method getCurrentCampaign --> '+e);
            }
        }
        else
        {
            cmpgn = mkt.CMPGN_NR__c;
        }
        
        return cmpgn;
    }
    
    /**
        * This method will return next campaign for MP/non MP market
        * This method accepts 2 parameters:
        * Market - it needs to have Mail_Plan_Enabled__c, NEXT_1_CMPGN_NR__c, Market_Id__c field
        * User - It needs to have DFALT_ZONE_CD__c field
    **/
    global static string getNextCampaign(Market__c mkt, User usr)
    {
        String cmpgn = '';
        if(mkt.Mail_Plan_Enabled__c)       
        {
            try
            {
                //Date currDate = System.today();
                DateTime d = datetime.now();
                String timeStr = d.format('yyyy-MM-dd');
                
                String query_str = 'SELECT Id, CMPGN_NR__c, MRKT_ID__c, MLPLN_END_DT__c';
                
                query_str+=' FROM MailPlan_Order_Oppty__c';
                
                String whereClause = ' WHERE SLS_ZONE_CD__c=\''+usr.DFALT_ZONE_CD__c+'\' AND MRKT_ID__c=\''+mkt.Market_Id__c+'\' and CURRNT_NEXT_CMPGN_PRFX_CD__c=\'N\'';               
                whereClause+=' AND MLPLN_END_DT__c >= '+timeStr+' ORDER BY MLPLN_END_DT__c ';
                
                String limitClause = 'Limit 1';
                
                query_str = query_str+whereClause+limitClause;
                
                System.debug('\n ======= MailPlanUtil.query_str SL ======= \n'+query_str);
                List<MailPlan_Order_Oppty__c> lst_mpoo= Database.query(query_str);
                
                if (!lst_mpoo.isEmpty()) {
                    cmpgn = YOUUtil.getCampaignNumbrMailPlan((String)lst_mpoo[0].get('CMPGN_NR__c'));
                }
                else {
                    cmpgn = mkt.NEXT_1_CMPGN_NR__c;
                }
            }
            catch(exception e)
            {
                System.debug('exception in class NRT_Utils method getCurrentCampaign --> '+e);
                cmpgn = mkt.NEXT_1_CMPGN_NR__c;
            }
        }
        else
        {
            cmpgn = mkt.NEXT_1_CMPGN_NR__c;
        }
        
        return cmpgn;
    }
    
    public static String getLastUpdatedTimeStamp(String marketId)
    {
        DateTime lastModifiedTs = System.now().addMinutes(-20);
        
        for(Market__c m : [select Batch_Load_Strt_Dt__c ,NRT_Enabled__c
                             from Market__c 
                            where Market_Id__c = :marketId 
                              and Batch_Load_In_Process__c = true
                              and Batch_Load_Strt_Dt__c < :lastModifiedTs])
        {
            lastModifiedTs = m.Batch_Load_Strt_Dt__c;
            if(!m.NRT_Enabled__c)
              return '';
        }
        
        return Label.NRT_Last_Updated_Label+' '+lastModifiedTs.format();
    }
    
    public static String getLastUpdatedTimeStampBatch(String marketId)
    {
        for(Market__c m : [select Batch_Load_Strt_Dt__c, LAST_UPDT_DT__c
                             from Market__c 
                            where Market_Id__c = :marketId ])
        {
            return Label.NRT_Last_Updated_Label+' '+m.LAST_UPDT_DT__c.format();
        }
        
        return marketId;
        //NRT_New_Order_Message
    }
}