youfull/objects/ALM_Rep_Performance_1__c.object
<CustomObject>
    <fields>
        <fullName>CHK_NRT_INVC_IS_ACTIVE__c</fullName>
        <defaultValue>false</defaultValue>
        <label>CHK_NRT_INVC_IS_ACTIVE</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>CHK_NRT_IS_ACTIVE_APPT__c</fullName>
        <defaultValue>false</defaultValue>
        <label>CHK_NRT_IS_ACTIVE_APPT</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>CHK_NRT_SBMTD_IS_ACTIVE__c</fullName>
        <defaultValue>false</defaultValue>
        <label>CHK_NRT_SBMTD_IS_ACTIVE</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>FLD_SLS_CMPGN_NR__c</fullName>
        <label>Campaign</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>MRKT_ID__c</fullName>
        <externalId>true</externalId>
        <label>Market Id</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>NRT_INVC_IS_ACTIVE__c</fullName>
        <description>Rep considered active based on the NRT invoiced data?</description>
        <formula>If ( CDW_Is_Active__c 
, 1 
, If ( 
(MRKT_KEY__r.NRT_ACTIVE_USES_NET__c) 
, IF((NRT_DLY_INVC_AWRD_SLS_AMT__c + NRT_DLY_INVC_RTURN_AWRD_SLS_AMT__c) &gt; 0 
, 1 
, 0 
) 
, IF(NRT_DLY_INVC_AWRD_SLS_AMT__c &gt; 0 
, 1 
, 0 
) 
) 
)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>NRT Invoice Is Active</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>NRT_IS_ACTIVE_APPT__c</fullName>
        <formula>IF(NRT_IS_ACTIVE__c &amp;&amp; (LOA_NR__c == 0), 1, 0)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>NRT IS Active Appt</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>NRT_SBMTD_IS_ACTIVE__c</fullName>
        <formula>IF(  (NRT_INVC_IS_ACTIVE__c ==0)
   , IF(MRKT_KEY__r.NRT_HAS_SUBMTD_AMT__c 
          , IF ( MRKT_KEY__r.NRT_ACTIVE_USES_NET__c 
                    , IF((NRT_SUBMTD_AWRD_SLS_AMT__c + NRT_SUBMTD_RTURN_AWRD_SLS_AMT__c &gt; 0)
                         , 1
                         , 0
                       )
                    , IF ( (NRT_SUBMTD_AWRD_SLS_AMT__c &gt; 0)
                           , 1
                           , 0
                      )
             )         
          , IF( (NRT_SUBMTD_AWRD_ORDER_CNT__c &gt; 0) 
                      , 1
                      , 0
               )
      )
    
   , 0 
  )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>NRT Submitted is Active</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>SLS_ORG_SUMRY_KEY__c</fullName>
        <description>Look-up to the Sales Org Summary Object</description>
        <label>SLS ORG SUMRY KEY</label>
        <referenceTo>Sales_Org_Summary__c</referenceTo>
        <relationshipLabel>ALM Rep Performance</relationshipLabel>
        <relationshipName>ALM_Rep_Performance</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SLS_ZONE_CD__c</fullName>
        <label>Zone</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <label>ALM Rep Performance</label>
    <nameField>
        <label>ALM Rep Performance Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>ALM Rep Performance</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

youfull/objects/Market__c.object
<CustomObject>
    <fields>
        <fullName>Batch_Load_In_Process__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Flag to be set by CDW when starting the nightly batch and reset after its complete.</description>
        <inlineHelpText>Flag to be set by CDW when starting the nightly batch and reset after its complete.</inlineHelpText>
        <label>Batch Load In Process</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Market_Id__c</fullName>
        <externalId>true</externalId>
        <label>MRKT_ID</label>
        <length>15</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>NRT_Enabled__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Flag to determine, if this market is participating in NRT or not.</description>
        <label>NRT Enabled</label>
        <type>Checkbox</type>
    </fields>
    <label>Market</label>
    <nameField>
        <label>Market Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Markets</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

youfull/objects/Sales_Org_Summary__c.object
<CustomObject>
    <fields>
        <fullName>FLD_SLS_CMPGN_NR__c</fullName>
        <label>Field Campaign Number</label>
        <length>6</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SLS_ORG_SUMRY_KEY__c</fullName>
        <description>Sales Org Summary Key.  Format: MRKT_ID+CMPGN_NR+ORG_TYPE+ORG_NAME</description>
        <externalId>true</externalId>
        <label>SLS_ORG_SUMRY_KEY__c</label>
        <length>100</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Sales Org Summary</label>
    <nameField>
        <label>Sales Org Summary Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sales Org Summaries</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

youfull/classes/NRT_ALM_SalesOrgSummaryRollup.cls
global class NRT_ALM_SalesOrgSummaryRollup implements Schedulable 
{ 
	/**
		
	**/
	global void execute (SchedulableContext ctx) 
	
	{ 
		map<string, Integer> SalesOrgSummaryActive = new map<string, Integer>();
		map<string, Integer> SalesOrgSummaryInvoiced = new map<string, Integer>();
		map<string, Integer> SalesOrgSummaryAppointment = new map<string, Integer>();
		//map<string, AlmCounts> SalesOrgSummaryCounts = new map<string, AlmCounts>();
		set<String> marketKeys = new set<String>();
		for(Market__c m : [Select Market_Id__c from Market__c where Batch_Load_In_Process__c = false and NRT_Enabled__c = true])  
		{
			marketKeys.add(m.Market_Id__c);
		}
		//NRT_SBMTD_ACTIVE_CNT 
		for(AggregateResult r1 :[select sum(NRT_SBMTD_IS_ACTIVE__c)  cnt
		                              , SLS_ORG_SUMRY_KEY__c
		                           from ALM_Rep_Performance_1__c 
		                          where NRT_SBMTD_IS_ACTIVE__c = 1 
		                            and CHK_NRT_SBMTD_IS_ACTIVE__c = false
		                            and MRKT_ID__c in :marketKeys
		                          group by SLS_ORG_SUMRY_KEY__c])
	   {
	   		string sosId = (String)r1.get('MRKT_ID__c') +(String)r1.get('FLD_SLS_CMPGN_NR__c')+ 'Z' +(String)r1.get('SLS_ZONE_CD__c');
	   		Integer cnt = (Integer)r1.get('cnt');
	   		if(SalesOrgSummaryActive.containsKey(sosId))
	   		{
	   			Integer x = SalesOrgSummaryActive.get(sosId);
	   			x += cnt;
	   			SalesOrgSummaryActive.put(sosId, x);
	   		}
	   		else
	   		{
	   			SalesOrgSummaryActive.put(sosId, cnt);
	   		}
	   } 
	   //NRT_INVC_ACTIVE_CNT 
		for(AggregateResult r1 :[select count(Id) cnt 
		                              , SLS_ORG_SUMRY_KEY__c 
		                           from ALM_Rep_Performance_1__c 
		                          where NRT_INVC_IS_ACTIVE__c = 1 
		                            and CHK_NRT_INVC_IS_ACTIVE__c = false
		                            and MRKT_ID__c in :marketKeys
		                          group by SLS_ORG_SUMRY_KEY__c])
	   {
	   		string sosId = (String)r1.get('MRKT_ID__c') +(String)r1.get('FLD_SLS_CMPGN_NR__c')+ 'Z' +(String)r1.get('SLS_ZONE_CD__c');
	   		Integer cnt = (Integer)r1.get('cnt');
	   		if(SalesOrgSummaryInvoiced.containsKey(sosId))
	   		{
	   			Integer x = SalesOrgSummaryInvoiced.get(sosId);
	   			x += cnt;
	   			SalesOrgSummaryInvoiced.put(sosId, x);
	   		}
	   		else
	   		{
	   			SalesOrgSummaryInvoiced.put(sosId, cnt);
	   		}
	   } 
	   //NRT_ACTIVE_APPT_CNT 
		for(AggregateResult r1 :[select count(Id) 
		                              , SLS_ORG_SUMRY_KEY__c
		                           from ALM_Rep_Performance_1__c 
		                          where NRT_IS_ACTIVE_APPT__c = 1
		                            and CHK_NRT_IS_ACTIVE_APPT__c = false
		                            and MRKT_ID__c in :marketKeys
		                          group by SLS_ORG_SUMRY_KEY__c])
	   {
	   		string sosId = (String)r1.get('MRKT_ID__c') +(String)r1.get('FLD_SLS_CMPGN_NR__c')+ 'Z' +(String)r1.get('SLS_ZONE_CD__c');
	   		Integer cnt = (Integer)r1.get('cnt');
	   		if(SalesOrgSummaryAppointment.containsKey(sosId))
	   		{
	   			Integer x = SalesOrgSummaryAppointment.get(sosId);
	   			x += cnt;
	   			SalesOrgSummaryAppointment.put(sosId, x);
	   		}
	   		else
	   		{
	   			SalesOrgSummaryAppointment.put(sosId, cnt);
	   		}
	   } 
	   
	   //==============================
	   //Negative amounts
	   
	  for(AggregateResult r1 :[select count(Id)  cnt
		                              , SLS_ORG_SUMRY_KEY__c
		                           from ALM_Rep_Performance_1__c 
		                          where NRT_SBMTD_IS_ACTIVE__c = 0 
		                            and CHK_NRT_SBMTD_IS_ACTIVE__c = false
		                            and MRKT_ID__c in :marketKeys
		                          group by SLS_ORG_SUMRY_KEY__c])
	   {
	   		string sosId = (String)r1.get('MRKT_ID__c') +(String)r1.get('FLD_SLS_CMPGN_NR__c')+ 'Z' +(String)r1.get('SLS_ZONE_CD__c');
	   		Integer cnt = (Integer)r1.get('cnt');
	   		if(SalesOrgSummaryActive.containsKey(sosId))
	   		{
	   			Integer x = SalesOrgSummaryActive.get(sosId);
	   			x -= cnt;
	   			SalesOrgSummaryActive.put(sosId, x);
	   		}
	   		else
	   		{
	   			SalesOrgSummaryActive.put(sosId, 0-cnt);
	   		}
	   } 
	   //NRT_INVC_ACTIVE_CNT 
		for(AggregateResult r1 :[select count(Id) cnt 
		                              , SLS_ORG_SUMRY_KEY__c 
		                           from ALM_Rep_Performance_1__c 
		                          where NRT_INVC_IS_ACTIVE__c =0 
		                            and CHK_NRT_INVC_IS_ACTIVE__c = false
		                            and MRKT_ID__c in :marketKeys
		                          group by SLS_ORG_SUMRY_KEY__c])
	   {
	   		string sosId = (String)r1.get('MRKT_ID__c') +(String)r1.get('FLD_SLS_CMPGN_NR__c')+ 'Z' +(String)r1.get('SLS_ZONE_CD__c');
	   		Integer cnt = (Integer)r1.get('cnt');
	   		if(SalesOrgSummaryInvoiced.containsKey(sosId))
	   		{
	   			Integer x = SalesOrgSummaryInvoiced.get(sosId);
	   			x -= cnt;
	   			SalesOrgSummaryInvoiced.put(sosId, x);
	   		}
	   		else
	   		{
	   			SalesOrgSummaryInvoiced.put(sosId, 0-cnt);
	   		}
	   } 
	   //NRT_ACTIVE_APPT_CNT 
		for(AggregateResult r1 :[select count(Id) 
		                              , SLS_ORG_SUMRY_KEY__c
		                           from ALM_Rep_Performance_1__c 
		                          where NRT_IS_ACTIVE_APPT__c = 0
		                            and CHK_NRT_IS_ACTIVE_APPT__c = false
		                            and MRKT_ID__c in :marketKeys
		                          group by SLS_ORG_SUMRY_KEY__c])
	   {
	   		string sosId = (String)r1.get('MRKT_ID__c') +(String)r1.get('FLD_SLS_CMPGN_NR__c')+ 'Z' +(String)r1.get('SLS_ZONE_CD__c');
	   		Integer cnt = (Integer)r1.get('cnt');
	   		if(SalesOrgSummaryAppointment.containsKey(sosId))
	   		{
	   			Integer x = SalesOrgSummaryAppointment.get(sosId);
	   			x -= cnt;
	   			SalesOrgSummaryAppointment.put(sosId, x);
	   		}
	   		else
	   		{
	   			SalesOrgSummaryAppointment.put(sosId, 0-cnt);
	   		}
	   } 
	   
	   list<Sales_Org_Summary__c> sosUpdateList = new  list<Sales_Org_Summary__c>();
	   for(Sales_Org_Summary__c sos : [Select Id
	                                        , NRT_SBMTD_ACTIVE_CNT__c
	                                        , NRT_INVC_ACTIVE_CNT__c
	                                        , NRT_ACTIVE_APPT_CNT__c
	                                        , SLS_ORG_SUMRY_KEY__c
	                                     from Sales_Org_Summary__c
	                                    where SLS_ORG_SUMRY_KEY__c in :SalesOrgSummaryAppointment.keySet()
	                                       or SLS_ORG_SUMRY_KEY__c in :SalesOrgSummaryInvoiced.keySet()
	                                       or SLS_ORG_SUMRY_KEY__c in :SalesOrgSummaryActive.keySet()]) 
	  {
	  	  if(SalesOrgSummaryAppointment.containsKey(sos.SLS_ORG_SUMRY_KEY__c))
	  	     sos.NRT_ACTIVE_APPT_CNT__c += SalesOrgSummaryAppointment.get(sos.SLS_ORG_SUMRY_KEY__c);
	  	  
	  	  if(SalesOrgSummaryInvoiced.containsKey(sos.SLS_ORG_SUMRY_KEY__c))
	  	     sos.NRT_INVC_ACTIVE_CNT__c += SalesOrgSummaryInvoiced.get(sos.SLS_ORG_SUMRY_KEY__c);
	  	     
	  	  if(SalesOrgSummaryActive.containsKey(sos.SLS_ORG_SUMRY_KEY__c))
	  	     sos.NRT_SBMTD_ACTIVE_CNT__c += SalesOrgSummaryActive.get(sos.SLS_ORG_SUMRY_KEY__c);
	  	     
	  	  sosUpdateList.add(sos);
	  }
	  
	  //Set the counts on the Sales Org Summary Records
	  if(sosUpdateList.size() > 0)
	    update sosUpdateList;
	    
	  //flip the flags to false on the ALM Records
	  list<ALM_Rep_Performance_1__c> almRepUpdateList = new list<ALM_Rep_Performance_1__c>();
	  for(ALM_Rep_Performance_1__c rep : [select Id
	                                            , CHK_NRT_IS_ACTIVE_APPT__c
	                                            , CHK_NRT_INVC_IS_ACTIVE__c
	                                            , CHK_NRT_SBMTD_IS_ACTIVE__c
	                                         from ALM_Rep_Performance_1__c
	                                        where CHK_NRT_SBMTD_IS_ACTIVE__c = false
	                                           or CHK_NRT_INVC_IS_ACTIVE__c = false
	                                           or CHK_NRT_IS_ACTIVE_APPT__c = false])
	  {
		  rep.CHK_NRT_SBMTD_IS_ACTIVE__c = true;
		  rep.CHK_NRT_INVC_IS_ACTIVE__c = true;
	      rep.CHK_NRT_IS_ACTIVE_APPT__c = true;
	    
	      almRepUpdateList.add(rep);
	  }
	  
	  if(almRepUpdateList.size() > 0)
	    update almRepUpdateList;
	}

}