youfull/objects/ALM_Rep_Performance_1__c.object
<CustomObject>
    <fields>
        <fullName>ACCT_NR__c</fullName>
        <label>Account Number</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>AVON_LOA_1_6_IND__c</fullName>
        <label>Avon LOA 1-6 Indicator</label>
        <length>1</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>FLD_SLS_CMPGN_NR__c</fullName>
        <label>Campaign</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Genealogy_Key__c</fullName>
        <externalId>true</externalId>
        <label>Genealogy Key</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Genealogy_Level__c</fullName>
        <label>Genealogy Level</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>LDRSHP_LOA_NR__c</fullName>
        <label>Leadership LOA</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>LDRSHP_RPT_SLS_ZONE_CD__c</fullName>
        <label>Reporting Zone</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>LDRSHP_TITL_LVL_NR__c</fullName>
        <label>Badge Title (Achieved Title)</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>LFT_ND_ID__c</fullName>
        <label>Sort</label>
        <precision>12</precision>
        <scale>6</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>MRKT_ACCT_KEY__c</fullName>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>ALM Rep Performance</relationshipLabel>
        <relationshipName>ALM_Rep_Performance_1</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>MRKT_ID__c</fullName>
        <externalId>true</externalId>
        <label>Market Id</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>MRKT_KEY__c</fullName>
        <label>Market</label>
        <referenceTo>Market__c</referenceTo>
        <relationshipLabel>ALM Rep Performance</relationshipLabel>
        <relationshipName>ALM_Rep_Performance_1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>OPERTNL_CMPGN_NR__c</fullName>
        <label>Campaign</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Personal_Performance_Key__c</fullName>
        <description>MRKT_CMPGN_ACCT_KEY</description>
        <inlineHelpText>MRKT_CMPGN_ACCT_KEY</inlineHelpText>
        <label>Personal Performance Key</label>
        <length>50</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>REP_OMS_STUS_CD__c</fullName>
        <inlineHelpText>1=Staff, 0=removed, -2=Recruit</inlineHelpText>
        <label>Rep Status</label>
        <length>5</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>RGT_ND_ID__c</fullName>
        <label>Right Node Id</label>
        <precision>12</precision>
        <scale>6</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>ROOT_UPLN_ACCT_NR__c</fullName>
        <label>Root Upline Account</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>RTURN_NET_SLS_AMT__c</fullName>
        <label>Return Net Sales</label>
        <precision>15</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>SLS_ZONE_CD__c</fullName>
        <label>Zone</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <label>ALM Rep Performance</label>
    <nameField>
        <label>ALM Rep Performance Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>ALM Rep Performance</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

youfull/objects/Market__c.object
<CustomObject>
    <fields>
        <fullName>ALM_Rep_Indicator__c</fullName>
        <label>ALM Rep Indicator</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Allow_Freeform_Email__c</fullName>
        <description>Profile allowed to send freeform emails</description>
        <inlineHelpText>Profile allowed to send freeform emails</inlineHelpText>
        <label>Allow Freeform Email</label>
        <picklist>
            <picklistValues>
                <fullName>Avon Leader</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Avon Zone Manager</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Avon Division Manager</fullName>
            </picklistValues>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <fields>
        <fullName>Batch_Load_In_Process__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Flag to be set by CDW when starting the nightly batch and reset after its complete.</description>
        <inlineHelpText>Flag to be set by CDW when starting the nightly batch and reset after its complete.</inlineHelpText>
        <label>Batch Load In Process</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>CMPGN_NR__c</fullName>
        <label>CMPGN_NR</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Is_ALMPLUS_Enabled__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Check to enable/disable ALM+ functionality</description>
        <inlineHelpText>Check to enable/disable ALM+ functionality</inlineHelpText>
        <label>Is ALM+ Enabled</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Market_Currency_Symbol__c</fullName>
        <description>it denotes the currency symbol to be used in Coaching record page.</description>
        <label>Market Currency Symbol</label>
        <length>2</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Market_Id__c</fullName>
        <externalId>true</externalId>
        <label>MRKT_ID</label>
        <length>15</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>NEXT_1_CMPGN_NR__c</fullName>
        <label>NEXT_1_CMPGN_NR</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <label>Market</label>
    <nameField>
        <label>Market Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Markets</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

youfull/objects/Sales_Org_Summary__c.object
<CustomObject>
    <fields>
        <fullName>ACTV_REP_CNT__c</fullName>
        <label>Act. Reps Invoiced</label>
        <precision>13</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>ACTV_REP_DIV_RNK__c</fullName>
        <label>Act. Reps Division Rank</label>
        <precision>13</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>ACTV_REP_PLAN_SPPY_CNT__c</fullName>
        <label>Act. Reps SPPY Plan</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>ACTV_REP_SPPY_CNT__c</fullName>
        <label>Act. Reps PY</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>APPT_CNT__c</fullName>
        <label>Appointments Actual</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>FLD_SLS_CMPGN_NR__c</fullName>
        <label>Field Campaign Number</label>
        <length>6</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>LOA1_NET_SLS_DIV_RNK__c</fullName>
        <label>LOA1 Sales Division Rank</label>
        <precision>13</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>LOA_1_6_NET_SLS_AMT__c</fullName>
        <label>LOA1-6 Sales Actual</label>
        <precision>13</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>LOA_1_6_NET_SLS_DIV_RNK__c</fullName>
        <label>LOA1-6 Sales Division Rank</label>
        <precision>13</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>LOA_1_6_NET_SLS_PLAN_SPPY_AMT__c</fullName>
        <label>LOA1-6 Sales SPPY Plan</label>
        <precision>13</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>LOA_1_6_NET_SLS_SPPY_AMT__c</fullName>
        <label>LOA1-6 sales sppy Actual</label>
        <precision>13</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>MRKT_ACCT_KEY__c</fullName>
        <externalId>true</externalId>
        <inlineHelpText>MRKT_ACCT_KEY</inlineHelpText>
        <label>Sales Org Manager Key</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>MRKT_KEY__c</fullName>
        <label>Market</label>
        <referenceTo>Market__c</referenceTo>
        <relationshipLabel>Sales Org Summary</relationshipLabel>
        <relationshipName>Sales_Org_Summary</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>NET_SLS_DIV_RNK__c</fullName>
        <label>Net sales division rank</label>
        <precision>13</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>NET_SLS_PLAN_SPPY_AMT__c</fullName>
        <label>Net sales sppy plan</label>
        <precision>15</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>NET_SLS_SPPY_AMT__c</fullName>
        <label>Net Sales PY</label>
        <precision>15</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>OPERTNL_CMPGN_NR__c</fullName>
        <label>Operational Campaign Number</label>
        <length>6</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>RMOVL_CNT__c</fullName>
        <label>Removals Actuals</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>RMOVL_PLAN_CNT__c</fullName>
        <label>removals plan</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>RMOVL_PLAN_SPPY_CNT__c</fullName>
        <label>removals sppy plan</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>RMOVL_SPPY_CNT__c</fullName>
        <label>removals sppy actual</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>RNSTMT_CNT__c</fullName>
        <label>Actual Reinstatements</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>RNSTMT_DIV_RNK__c</fullName>
        <label>reinstatements division rank</label>
        <precision>13</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>RNSTMT_PLAN_CNT__c</fullName>
        <label>Reinstatements Plan</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>RNSTMT_SPPY_CNT__c</fullName>
        <label>reinstatements sppy actual</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>RTURN_NET_SLS_AMT__c</fullName>
        <label>Actual Returns</label>
        <precision>13</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>RTURN_NET_SLS_PLAN_SPPY_AMT__c</fullName>
        <label>returned sales sppy plan</label>
        <precision>13</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>SLS_ORG_DESC_TXT__c</fullName>
        <label>Area</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>TITLD_STF_CNT__c</fullName>
        <label>count of Unit leader and above actual</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>TITLD_STF_DIV_RNK__c</fullName>
        <label>count of Unit leader and above DR</label>
        <precision>13</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>TITL_0_STF_CNT__c</fullName>
        <label>candidates - count</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>TITL_0_STF_DIV_RNK__c</fullName>
        <label>candidates - division rank</label>
        <precision>13</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>TITL_0_STF_PLAN_CNT__c</fullName>
        <label># of Candidates Plan</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>TITL_0_STF_PLAN_SPPY_CNT__c</fullName>
        <label>candidates - sppy plan</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>UPR_CNT__c</fullName>
        <label>Actual UPR</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>UPR_DIV_RNK_CNT__c</fullName>
        <label>UPR division rank</label>
        <precision>13</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>UPR_PLAN_CNT__c</fullName>
        <label>UPR (unit per rep) plan</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>UPR_PLAN_SPPY_CNT__c</fullName>
        <label>UPR (unit per rep) sppy plan</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Sales Org Summary</label>
    <nameField>
        <label>Sales Org Summary Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sales Org Summaries</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

youfull/classes/Test_ALMAppointmentServiceSoap.cls
@isTest
private class Test_ALMAppointmentServiceSoap {
    
    public static String mktIdKey = 'XX';
    static testMethod void runtest() {
            
        
        TestDataHelper testData =   new TestDataHelper();
        
         // Creating market data
		Market__c mrkt = testData.createMarket();
        mrkt.Market_Id__c = 'XX';
    	mrkt.Allow_Freeform_Email__c = 'Avon Leader; Avon Division Manager';
    	mrkt.Market_Currency_Symbol__c = '₱';
    	mrkt.Batch_Load_In_Process__c = false;
    	mrkt.NEXT_1_CMPGN_NR__c = '1234';
        mrkt.CMPGN_NR__c = '3456';
    	update  mrkt;
    	 
    	// Creating user data
    	User ldrUsr = testData.createLeaderUser(mktIdKey);
        ldrUsr.MRKT_ID__c = mrkt.Market_Id__c;
        ldrUsr.IsActive = true;
        update ldrUsr;
        
        // Updating market data
        mrkt.OwnerId = ldrUsr.Id;
        mrkt.Is_ALMPLUS_Enabled__c = true;
        mrkt.ALM_Rep_Indicator__c = 'ALM_Rep_Performance_1__c';
        update  mrkt;
        
        // Creating Account data
         Account testAcct = new Account(Name='Test Acount');
         insert testAcct;
        
        // Creating Contact data
        List<Contact> lstContact = new List<Contact>();
        Contact con1    = new Contact(  AccountId=testAcct.Id, ACCT_NR__c=mktIdKey,
                                            Email='test1@avon.com',FirstName=mktIdKey+'First1',LastName=mktIdKey+'Last1',HomePhone='9999999999',
                                            LDRSHP_PRGRM_IND__c='Y',LDRSHP_RPT_SLS_ZONE_CD__c='XZ1',
                                            MRKT_ACCT_KEY__c=mrkt.Market_Id__c+mktIdKey, MRKT_ID__c=mrkt.Market_Id__c,
                                            PATD_CERTFCTN_LVL_A_IND__c='Y',PATD_CERTFCTN_LVL_D_IND__c='Y',
                                            PATD_CERTFCTN_LVL_P_IND__c='Y',PATD_CERTFCTN_LVL_T_IND__c='Y',
                                            REP_ADDR_STR_2_TXT__c='Address 2',REP_ADDR_STR_3_TXT__c='Address 3',
                                            REP_ADDR_STR_4_TXT__c='Address 4',REP_APPT_DT__c=System.today(),
                                            REP_LANG_CD__c='en_US',SLS_ZONE_CD__c='XZ1',REP_MOBILE_PHON_NR__c = '1234546789',
                                            OwnerId=ldrUsr.Id
                                          );
    	insert con1;
    	
    	
        ALM_Rep_Performance_1__c rep1 = new ALM_Rep_Performance_1__c(
                                                Name = 'Test REP1', 
                                                ACCT_NR__c = mktIdKey,
                                                Genealogy_Level__c = 0,
                                                CurrencyISOCode='USD',
                                                MRKT_ID__c=mrkt.Market_ID__c,
                                                MRKT_ACCT_KEY__c = con1.Id,
                                                MRKT_KEY__c = mrkt.Id,
                                                FLD_SLS_CMPGN_NR__c=Decimal.valueOf(mrkt.CMPGN_NR__c),
                                                OPERTNL_CMPGN_NR__c =mrkt.CMPGN_NR__c,
                                                Personal_Performance_Key__c = mrkt.Market_Id__c + mrkt.CMPGN_NR__c + mktIdKey,
                                                REP_OMS_STUS_CD__c = '1', AVON_LOA_1_6_IND__c = 'Y',
                                                LDRSHP_LOA_NR__c=1, LDRSHP_TITL_LVL_NR__c = '1',
                                                ROOT_UPLN_ACCT_NR__c = mktIdKey,
                                                LFT_ND_ID__c = 1, RGT_ND_ID__c = 8,
                                                Genealogy_Key__c = mrkt.Market_ID__c+mrkt.CMPGN_NR__c+mktIdKey,
                                                SLS_ZONE_CD__c = 'ttt'
                                            );
      insert rep1;
      
      String salesOrgSummaryKey = rep1.MRKT_ID__c + rep1.OPERTNL_CMPGN_NR__c + 'Z' + rep1.SLS_ZONE_CD__c;
      
      Sales_Org_Summary__c sos = New Sales_Org_Summary__c (  ACTV_REP_CNT__c=300, UPR_CNT__c=8
                                                           , SLS_ORG_DESC_TXT__c='601'
                                                           , TITLD_STF_CNT__c=8
                                                           , RTURN_NET_SLS_PLAN_SPPY_AMT__c=1550.00
                                                           , TITL_0_STF_CNT__c=8
                                                           , UPR_DIV_RNK_CNT__c=100
                                                           , RNSTMT_DIV_RNK__c=100
                                                           , UPR_PLAN_SPPY_CNT__c=9
                                                           , RMOVL_PLAN_CNT__c=6
                                                           , LOA_1_6_NET_SLS_DIV_RNK__c=100
                                                           , RTURN_NET_SLS_AMT__c=1500.00
                                                           , RMOVL_SPPY_CNT__c=8
                                                           , LOA_1_6_NET_SLS_PLAN_SPPY_AMT__c=1000.00
                                                           , RMOVL_PLAN_SPPY_CNT__c=8
                                                           , NET_SLS_SPPY_AMT__c=1555000.00
                                                           , LOA_1_6_NET_SLS_SPPY_AMT__c=1000.00
                                                           , RNSTMT_PLAN_CNT__c=5
                                                           , RMOVL_CNT__c=9
                                                           , TITLD_STF_DIV_RNK__c=100
                                                           , RNSTMT_CNT__c=2
                                                           , ACTV_REP_PLAN_SPPY_CNT__c=1500
                                                           , NET_SLS_DIV_RNK__c=100
                                                           , TITL_0_STF_PLAN_SPPY_CNT__c=9
                                                           , APPT_CNT__c=9
                                                           , TITL_0_STF_PLAN_CNT__c=9
                                                           , TITL_0_STF_DIV_RNK__c=100
                                                           , LOA_1_6_NET_SLS_AMT__c=30000.00
                                                           , UPR_PLAN_CNT__c=9
                                                           , OPERTNL_CMPGN_NR__c='201303'
                                                           , ACTV_REP_DIV_RNK__c=100
                                                           , RNSTMT_SPPY_CNT__c=7
                                                           , LOA1_NET_SLS_DIV_RNK__c=100
                                                           , ACTV_REP_SPPY_CNT__c=1600
                                                           , LOA1_NET_SLS_AMT__c=1000.00
                                                           , RMOVL_DIV_RNK__c=100
                                                           , LOA1_NET_SLS_SPPY_AMT__c=1000.00
                                                           , NET_SLS_PLAN_SPPY_AMT__c=1555000.00
                                                           , LOA1_NET_SLS_PLAN_SPPY_AMT__c=1000.00
                                                           , TITLD_STF_SPPY_CNT__c=9
                                                           , TITL_0_STF_SPPY_CNT__c=9
                                                           , APPT_DIV_RNK__c=100
                                                           , UPR_SPPY_CNT__c=9
                                                           , APPT_PLAN_CNT__c=12
                                                           , LOA_1_6_NET_SLS_PLAN_AMT__c=322000.00
                                                           , RTURN_NET_SLS_DIV_RNK__c=100
                                                           , Analysis_Done__c=false
                                                           , RTURN_NET_SLS_SPPY_AMT__c=1550.00
                                                           , APPT_PLAN_SPPY_CNT__c=15
                                                           , NET_SLS_PLAN_AMT__c=500000.00
                                                           , RNSTMT_PLAN_SPPY_CNT__c=7
                                                           , APPT_SPPY_CNT__c=15
                                                           , ACTV_REP_PLAN_CNT__c=200
                                                           , LOA1_NET_SLS_PLAN_AMT__c=100000.00
                                                           , TITLD_STF_PLAN_SPPY_CNT__c=9
                                                           , RTURN_NET_SLS_PLAN_AMT__c=1500.00
                                                           , TITLD_STF_PLAN_CNT__c=9
                                                           , SLS_ORG_SUMRY_KEY__c = salesOrgSummaryKey); 
        
      insert sos;
        
     
    
	    ALMAppointmentServiceSoap.Appointment a = new ALMAppointmentServiceSoap.Appointment();
	    a.ACCT_NR = '06968021';
	    a.Appointment_Campaign='201210';
	    a.Appointment_Date= System.Today();
	    a.DOB=System.Today().addYears(21);
	    a.Email='rama.chintalapati@avon.com';
	    a.Error_Message='';
	    a.Error_Type='';   
	    a.First_Name='Rama'; 
	    a.Has_Errors=false;
	    a.Home_Phone='111111111';
	    a.Last_Name='Chintalapati';
	    a.Mailplan_NR='1';
	    a.Mobile='2222222222';
	    a.MRKT_SLS_ORG_KEY='2';    
	    a.MRKT_ID='XX';
	    a.MRKT_SLS_ORG_KEY='1';
	    a.Phone='3333333333'; 
	    a.Rep_Status='1';
	    a.Response_Salesforce_Id=''; 
	    a.UPLN_ACCT_NR=mktIdKey; 
	    a.Zone='1';
	    
	    list<ALMAppointmentServiceSoap.Appointment> aList = new list<ALMAppointmentServiceSoap.Appointment>();
	    aList = ALMAppointmentServiceSoap.upsertOrderObject(new list<ALMAppointmentServiceSoap.Appointment>{a},'TEST');
	    
	    //System.Assert('UPLINE_ACCOUNT_NOT_FOUND' == a.Error_Type);
	    
	    a.UPLN_ACCT_NR = mktIdKey;
	    a.ACCT_NR = '06968022';
	    a.Error_Type = '';
	    
	    aList = ALMAppointmentServiceSoap.upsertOrderObject(new list<ALMAppointmentServiceSoap.Appointment>{a}, 'NATHAN');
	    System.debug('::::rep1:::>:'+rep1);
	    System.Debug(':::aList::::>'+aList);
//	    System.AssertEquals('DUPLICATE_VALUE',a.Error_Type);
	    
	    ALM_Rep_Performance_1__c rep2 = new ALM_Rep_Performance_1__c(
                                                Name = 'Test REP1', 
                                                ACCT_NR__c = mktIdKey,
                                                Genealogy_Level__c = 0,
                                                CurrencyISOCode='USD',
                                                MRKT_ID__c=mrkt.Market_ID__c,
                                                MRKT_ACCT_KEY__c = con1.Id,
                                                MRKT_KEY__c = mrkt.Id,
                                                FLD_SLS_CMPGN_NR__c=Decimal.valueOf(mrkt.CMPGN_NR__c),
                                                OPERTNL_CMPGN_NR__c =mrkt.CMPGN_NR__c,
                                                Personal_Performance_Key__c = mrkt.Market_Id__c + mrkt.NEXT_1_CMPGN_NR__c + mktIdKey,
                                                REP_OMS_STUS_CD__c = '1', AVON_LOA_1_6_IND__c = 'Y',
                                                LDRSHP_LOA_NR__c=1, LDRSHP_TITL_LVL_NR__c = '1',
                                                ROOT_UPLN_ACCT_NR__c = mktIdKey,
                                                LFT_ND_ID__c = 1, RGT_ND_ID__c = 8,
                                                Genealogy_Key__c = mrkt.Market_ID__c+mrkt.NEXT_1_CMPGN_NR__c+mktIdKey,
                                                SLS_ZONE_CD__c = 'ttt'
                                            );
      insert rep2;
	    aList = ALMAppointmentServiceSoap.upsertOrderObject(new list<ALMAppointmentServiceSoap.Appointment>{a}, 'NATHAN');
	    System.Debug(':::::::>Error_Type::::::>' + a.Error_Type);
//	    System.AssertEquals('DUPLICATE_VALUE',a.Error_Type);
	    
       a.UPLN_ACCT_NR=mktIdKey+'x';
       aList = ALMAppointmentServiceSoap.upsertOrderObject(new list<ALMAppointmentServiceSoap.Appointment>{a}, 'NATHAN');
       
       a.UPLN_ACCT_NR=null;
       aList = ALMAppointmentServiceSoap.upsertOrderObject(new list<ALMAppointmentServiceSoap.Appointment>{a}, 'NATHAN');
       
       a.UPLN_ACCT_NR=mktIdKey;
       aList = ALMAppointmentServiceSoap.upsertOrderObject(new list<ALMAppointmentServiceSoap.Appointment>{a}, 'NATHAN');
       
       a.Last_Name=null;
       aList = ALMAppointmentServiceSoap.upsertOrderObject(new list<ALMAppointmentServiceSoap.Appointment>{a}, 'NATHAN');
       
       a.Last_Name='boogieman';
       a.Rep_Status= 'owhataschmuckliam';
       aList = ALMAppointmentServiceSoap.upsertOrderObject(new list<ALMAppointmentServiceSoap.Appointment>{a}, 'NATHAN');
       
       a.Rep_Status= '1';
       a.ACCT_NR='11111'; 
       a.UPLN_ACCT_NR=mktIdKey; 
       aList = ALMAppointmentServiceSoap.upsertOrderObject(new list<ALMAppointmentServiceSoap.Appointment>{a}, 'NATHAN');
       
       a.UPLN_ACCT_NR='11111';
       a.ACCT_NR='2222';//add appointemnt to appointemnt  
       aList = ALMAppointmentServiceSoap.upsertOrderObject(new list<ALMAppointmentServiceSoap.Appointment>{a}, 'NATHAN');
       
       mrkt.Batch_Load_In_Process__c = true;
       update mrkt;//test batch load in process
       a.UPLN_ACCT_NR=mktIdKey;
       aList = ALMAppointmentServiceSoap.upsertOrderObject(new list<ALMAppointmentServiceSoap.Appointment>{a}, 'NATHAN');
       
       mrkt.Batch_Load_In_Process__c = false;
       update mrkt;//test batch load in process
       
       
	    
    }
}