youfull/objects/ALM_Rep_Performance_1__c.object
<CustomObject>
    <fields>
        <fullName>FLD_SLS_CMPGN_NR__c</fullName>
        <label>Campaign</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>MRKT_CMPGN_ROOT_UPLN_ACCT__c</fullName>
        <label>Market/Campaign Upline Account(Cluster)</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>MRKT_CMPGN_SLS_ZONE_CD__c</fullName>
        <label>Market Campaign / Zone (Cluster)</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>MRKT_ID__c</fullName>
        <externalId>true</externalId>
        <label>Market Id</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ROOT_UPLN_ACCT_NR__c</fullName>
        <label>Root Upline Account</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SLS_ZONE_CD__c</fullName>
        <label>Zone</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <label>ALM Rep Performance</label>
    <nameField>
        <label>ALM Rep Performance Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>ALM Rep Performance</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

youfull/classes/TestBatch.cls
global with sharing class TestBatch implements Database.Batchable<sObject>,Database.Stateful{
  global Database.QueryLocator start(Database.BatchableContext BC){
        String query='';
        query +=' select Id, MRKT_ID__c, SLS_ZONE_CD__c, FLD_SLS_CMPGN_NR__c, ROOT_UPLN_ACCT_NR__c, MRKT_CMPGN_SLS_ZONE_CD__c, MRKT_CMPGN_ROOT_UPLN_ACCT__c from ALM_Rep_Performance_1__c where MRKT_CMPGN_SLS_ZONE_CD__c=null or MRKT_CMPGN_ROOT_UPLN_ACCT__c=null';
        return Database.getQueryLocator(query);
    }
    
    global void execute(Database.BatchableContext BC, List<sObject> scope){
        List<ALM_Rep_Performance_1__c> almRecords=new List<ALM_Rep_Performance_1__c>();
        for(Sobject sobj:scope){
        	ALM_Rep_Performance_1__c almInstance=(ALM_Rep_Performance_1__c)sobj;
        	if(almInstance.MRKT_CMPGN_ROOT_UPLN_ACCT__c==null){
        		almInstance.MRKT_CMPGN_ROOT_UPLN_ACCT__c=almInstance.MRKT_ID__c + almInstance.FLD_SLS_CMPGN_NR__c + almInstance.ROOT_UPLN_ACCT_NR__c;
        	}
        	else if (almInstance.MRKT_CMPGN_SLS_ZONE_CD__c ==null){
        	   almInstance.MRKT_CMPGN_SLS_ZONE_CD__c=almInstance.MRKT_ID__c + almInstance.FLD_SLS_CMPGN_NR__c + almInstance.SLS_ZONE_CD__c;
        	}
        	else if(almInstance.MRKT_ID__c==null || almInstance.FLD_SLS_CMPGN_NR__c==null || almInstance.SLS_ZONE_CD__c==null || almInstance.ROOT_UPLN_ACCT_NR__c==null){
        		almInstance.MRKT_CMPGN_SLS_ZONE_CD__c='ERROR';
        		almInstance.MRKT_CMPGN_ROOT_UPLN_ACCT__c='ERROR';
        	}
        	almRecords.add(almInstance);
        }
        
        update almRecords;
    }
    
    global void finish(Database.BatchableContext BC){

    }
}