youfull/objects/ALM_Global_Settings__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <customSettingsVisibility>Protected</customSettingsVisibility>
    <description>Holds global settings that apply across the entire application.</description>
    <label>ALM Global Settings</label>
</CustomObject>

youfull/objects/ALM_Rep_Performance_1__c.object
<CustomObject>
    <fields>
        <fullName>ACCT_NR__c</fullName>
        <label>Account Number</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>FLD_SLS_CMPGN_NR__c</fullName>
        <label>Campaign</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>LCL_TOP_SLR_LVL_KEY__c</fullName>
        <label>Seller Title</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>LDRSHP_TITL_LVL_NR__c</fullName>
        <label>Badge Title (Achieved Title)</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>MRKT_ID__c</fullName>
        <externalId>true</externalId>
        <label>Market Id</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>MailPlan_Order_Oppty__c</fullName>
        <description>Lookup to corresponding record of MailPlan_Order_Oppty</description>
        <inlineHelpText>Lookup to corresponding record of MailPlan_Order_Oppty</inlineHelpText>
        <label>MailPlan_Order_Oppty</label>
        <referenceTo>MailPlan_Order_Oppty__c</referenceTo>
        <relationshipLabel>ALM Rep Performance</relationshipLabel>
        <relationshipName>ALM_Rep_Performance</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>ALM Rep Performance</label>
    <nameField>
        <label>ALM Rep Performance Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>ALM Rep Performance</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

youfull/objects/Incentive__c.object
<CustomObject>
    <fields>
        <fullName>CMPGN_NR__c</fullName>
        <label>CMPGN_NR</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>LANG_CD__c</fullName>
        <label>LANG_CD</label>
        <picklist>
            <picklistValues>
                <fullName>en_US</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>fr</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ro</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>pl</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>hu</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ru</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>cs</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>es_MX</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>es</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>uk</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>sh</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>sk</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>en_MY</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>en_IN</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>bg</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>en_PH</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>en_GB</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>fr_CA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>en_CA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>en_AU</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>fi</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>pt_BR</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>sl</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ka</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>et</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>lv</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>lt</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>th</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>MRKT_ID__c</fullName>
        <label>MRKT ID</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Market__c</fullName>
        <label>Market</label>
        <referenceTo>Market__c</referenceTo>
        <relationshipLabel>Incentives</relationshipLabel>
        <relationshipName>Incentives</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>Personal</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Team</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Incentive</label>
    <nameField>
        <label>Incentive Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Incentives</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

youfull/objects/MailPlan_Order_Oppty__c.object
<CustomObject>
    <fields>
        <fullName>CMPGN_NR__c</fullName>
        <label>CMPGN_NR</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>MRKT_ID__c</fullName>
        <label>MRKT_ID</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Market__c</fullName>
        <label>Market</label>
        <referenceTo>Market__c</referenceTo>
        <relationshipLabel>MailPlan_Order_Opptys</relationshipLabel>
        <relationshipName>MailPlan_Order_Opptys</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>MailPlan_Order_Oppty</label>
    <nameField>
        <displayFormat>MPLN-{000000}</displayFormat>
        <label>Mail Plan Order Oppty Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>MailPlan_Order_Opptys</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

youfull/objects/Market__c.object
<CustomObject>
    <fields>
        <fullName>CMPGN_NR__c</fullName>
        <label>CMPGN_NR</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Mail_Plan_Enabled__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Mail Plan Enabled</label>
        <type>Checkbox</type>
    </fields>
    <label>Market</label>
    <nameField>
        <label>Market Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Markets</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

youfull/objects/Seller_Status__c.object
<CustomObject>
    <fields>
        <fullName>LANG_CD__c</fullName>
        <label>Language</label>
        <picklist>
            <picklistValues>
                <fullName>en_US</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>fr</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ro</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ru</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>pl</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>cs</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>es_MX</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>uk</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>sk</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>sh</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>en_MY</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>en_IN</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>bg</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>en_PH</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>en_GB</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>en_AU</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>fi</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>pt_BR</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>fr_CA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>en_CA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>sl</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ka</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>et</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>lv</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>lt</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>th</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>LCL_TOP_SLR_LVL_KEY__c</fullName>
        <externalId>true</externalId>
        <label>Top Seller Code</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>MRKT_ID__c</fullName>
        <label>Market id</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Market__c</fullName>
        <label>Market</label>
        <referenceTo>Market__c</referenceTo>
        <relationshipName>Seller_Status</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Top Seller</label>
    <nameField>
        <displayFormat>SS-{0000000}</displayFormat>
        <label>Seller Status Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Top Seller</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

youfull/classes/Test_IncentivesController.cls
/***************************************************************************
 Name         : Test_IncentivesController
 Created By   : Saurabh Gupta (JDC)
 Description  : Test class for IncentivesController
 Created Date : Nov. 01, 2013                
****************************************************************************/

@isTest
private class Test_IncentivesController {

	//----------------------------------------------------------------------------
    // Method Name  : testIncentivesController
    // Description  : Method for Test Coverage of Class : IncentivesController
    //----------------------------------------------------------------------------  
    public static testmethod void testIncentivesController() {
    	String mktIdKey = '62';
        
        //Create ALM_Global_Settings__c
        ALM_Global_Settings__c almGlobal = TestDataHelper.createALMGlobalSetting(true);
        
        //Create market
        Market__c marketOne = TestDataHelper.createMarket(mktIdKey, false);
        marketOne.CMPGN_NR__c = '1';
        marketOne.Mail_Plan_Enabled__c = true;
        insert marketOne;
        
        //Create User
        List <User> usrList = new List <User>();
        User testUsr = TestDataHelper.createUser('1111', 'XZ1', 'Avon Leader', false);
        testUsr.ACCT_NR__c = '1111';
        testUsr.MRKT_ID__c = mktIdKey;
        testUsr.MRKT_ID_ACCT_NR_KEY__c = testUsr.MRKT_ID__c + '1111';
        usrList.add(testUsr);
        
        User testUsrOne = TestDataHelper.createUser('11117', 'XZ2', 'Avon Leader', false);
        testUsrOne.MRKT_ID__c = mktIdKey;
        usrList.add(testUsrOne);
        
        insert usrList;
        
        //Create Object: Account
        Account acct = TestDataHelper.createAccount('Test Account', 'USD', true);
        
        //Create Object: Contact
	    Contact con = TestDataHelper.createContact('1111', acct.Id, true);
        
        //Create Object: Incentive__c
        List <Incentive__c> incentiveList = new List <Incentive__c>();
        Incentive__c incentiveOne = TestDataHelper.createIncentive(String.valueOf(marketOne.Id), marketOne.CMPGN_NR__c, false);
        incentiveList.add(incentiveOne);
        
        Incentive__c incentiveTwo = TestDataHelper.createIncentive(String.valueOf(marketOne.Id), marketOne.CMPGN_NR__c, false);
        incentiveTwo.Type__c = 'personal';
        incentiveList.add(incentiveTwo);
        
        insert incentiveList;
        
        //Create Object: MailPlan_Order_Oppty__c
        MailPlan_Order_Oppty__c mailPlanOrder = TestDataHelper.createMPOrderOpp(String.valueOf(marketOne.Id), '4', 'N', System.today().addDays(1+10), 
                                                                                'M' + 1, 'XZ1', 'M' + 1, true);
                                                                                
        //Create Object: ALM_Rep_Performance_1__c
        List <ALM_Rep_Performance_1__c> almRepList = new List <ALM_Rep_Performance_1__c>();
        ALM_Rep_Performance_1__c almRepPerform = TestDataHelper.createRepPerformance(String.valueOf(con.Id), marketOne, '1111', false);
	    almRepPerform.ACCT_NR__c = '1111';
	    almRepPerform.MRKT_ID__c = mktIdKey;
	    almRepPerform.FLD_SLS_CMPGN_NR__c = 1.0;
	    almRepPerform.LCL_TOP_SLR_LVL_KEY__c = '1';
	    almRepPerform.MailPlan_Order_Oppty__c = mailPlanOrder.Id;
	    almRepList.add(almRepPerform);
    	
    	insert almRepList;
    	
    	//Create Object: Seller_Status__c
    	List <Seller_Status__c> sellerStatusList = TestDataHelper.createSellerStatusList(String.valueOf(marketOne.Id), false);
    	sellerStatusList[0].MRKT_ID__c = testUsr.MRKT_ID__c;
    	sellerStatusList[0].LCL_TOP_SLR_LVL_KEY__c = '1';
    	sellerStatusList[0].LANG_CD__c = testUsr.LanguageLocaleKey;
    	
    	insert sellerStatusList;
    	
    	PageReference pageRefOne = Page.Incentives;
        pageRefOne.getParameters().put(ALMConstants.IMPERSON_PARAM_NAME, '1111');
        Test.setCurrentPageReference(pageRefOne);
        
    	System.runAs(testUsr) {
    		Test.startTest();
	    	ComponentController compCntrl = new ComponentController();
	    	
	    	IncentivesController incentCntrl = new IncentivesController();
	    	Test.stopTest();
    	}
    	
    }
    
    //----------------------------------------------------------------------------
    // Method Name  : testIncentivesControllerOne
    // Description  : Method for Test Coverage of Class : IncentivesController
    //----------------------------------------------------------------------------  
    public static testmethod void testIncentivesControllerOne() {
    	String mktIdKey = '123456';
        
        //Create ALM_Global_Settings__c
        ALM_Global_Settings__c almGlobal = TestDataHelper.createALMGlobalSetting(true);
        
        //Create market
        Market__c marketOne = TestDataHelper.createMarket(mktIdKey, false);
        marketOne.CMPGN_NR__c = '1';
        marketOne.Mail_Plan_Enabled__c = true;
        insert marketOne;
        
        //Create User
        List <User> usrList = new List <User>();
        User testUsr = TestDataHelper.createUser(mktIdKey, 'XZ1', 'Avon Leader', false);
        testUsr.ACCT_NR__c = mktIdKey;
        testUsr.MRKT_ID_ACCT_NR_KEY__c = testUsr.MRKT_ID__c + '1111';
        usrList.add(testUsr);
        
        User testUsrOne = TestDataHelper.createUser(mktIdKey + '7', 'XZ2', 'Avon Leader', false);
        testUsrOne.ACCT_NR__c = mktIdKey;
        usrList.add(testUsrOne);
        
        insert usrList;
        
        //Create Object: Account
        Account acct = TestDataHelper.createAccount('Test Account', 'USD', true);
        
        //Create Object: Contact
	    Contact con = TestDataHelper.createContact(mktIdKey, acct.Id, true);
        
        //Create Object: Incentive__c
        List <Incentive__c> incentiveList = new List <Incentive__c>();
        Incentive__c incentiveOne = TestDataHelper.createIncentive(String.valueOf(marketOne.Id), marketOne.CMPGN_NR__c, false);
        incentiveList.add(incentiveOne);
        
        Incentive__c incentiveTwo = TestDataHelper.createIncentive(String.valueOf(marketOne.Id), marketOne.CMPGN_NR__c, false);
        incentiveTwo.Type__c = 'personal';
        incentiveList.add(incentiveTwo);
        
        insert incentiveList;
        
        //Create Object: MailPlan_Order_Oppty__c
        MailPlan_Order_Oppty__c mailPlanOrder = TestDataHelper.createMPOrderOpp(String.valueOf(marketOne.Id), '4', 'N', System.today().addDays(1+10), 
                                                                                'M' + 1, 'XZ1', 'M' + 1, true);
                                                                                
        //Create Object: ALM_Rep_Performance_1__c
        List <ALM_Rep_Performance_1__c> almRepList = new List <ALM_Rep_Performance_1__c>();
        ALM_Rep_Performance_1__c almRepPerform = TestDataHelper.createRepPerformance(String.valueOf(con.Id), marketOne, mktIdKey, false);
	    almRepPerform.ACCT_NR__c = mktIdKey;
	    almRepPerform.MRKT_ID__c = mktIdKey + '7';
	    almRepPerform.FLD_SLS_CMPGN_NR__c = 1.0;
	    almRepPerform.LCL_TOP_SLR_LVL_KEY__c = '1';
	    almRepPerform.MailPlan_Order_Oppty__c = mailPlanOrder.Id;
	    almRepPerform.LDRSHP_TITL_LVL_NR__c = '111';
	    almRepList.add(almRepPerform);
    	
    	insert almRepList;
    	
    	PageReference pageRefOne = Page.Incentives;
        pageRefOne.getParameters().put(ALMConstants.IMPERSON_PARAM_NAME, '1111');
        Test.setCurrentPageReference(pageRefOne);
        
    	System.runAs(testUsr) {
    		Test.startTest();
	    	ComponentController compCntrl = new ComponentController();
	    	
	    	IncentivesController incentCntrl = new IncentivesController();
	    	Test.stopTest();
    	}
    }
}