youfull/objects/Branch_Summary__c.object
<CustomObject>
    <fields>
        <fullName>ACCT_NR__c</fullName>
        <label>Account Nr</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>BRNCH_SCTN_CD__c</fullName>
        <label>Branch Name</label>
        <length>75</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Branch_Summary_Key__c</fullName>
        <externalId>true</externalId>
        <label>Branch Summary key</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>CMPGN_NR__c</fullName>
        <label>Campaign Number</label>
        <precision>6</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>MRKT_ID__c</fullName>
        <label>Market ID</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <label>Branch Summary</label>
    <nameField>
        <label>Branch Summary Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Branch_Summaries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

youfull/objects/Market__c.object
<CustomObject>
    <fields>
        <fullName>CMPGN_NR__c</fullName>
        <label>CMPGN_NR</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Market_Id__c</fullName>
        <externalId>true</externalId>
        <label>MRKT_ID</label>
        <length>15</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Market</label>
    <nameField>
        <label>Market Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Markets</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

youfull/classes/Test_MTRTextSearchController.cls
/***************************************************************************
 Name         : Test_MTRTextSearchController 
 Created By   : Parul Gupta (JDC)
 Description  : Test class for MTRTextSearchController
 Created Date : Oct 25, 2013                
****************************************************************************/
@isTest
private class Test_MTRTextSearchController {

    //---------------------------------------------------------------------------
    // Method Name  : testMTRTextSearchController
    // Description  : Method for Test Coverage of controller MTRTextSearchController
    //---------------------------------------------------------------------------
    static testMethod void testMTRTextSearchController () {
        MTRTextSearchController cont = new MTRTextSearchController();
       
        Market__c mkt = TestDataHelper.createMarket('99', true);  
        Branch_Summary__c branch = new Branch_Summary__c(CMPGN_NR__c=201306, 
                    ACCT_NR__c='1234567890', MRKT_ID__c=mkt.Market_Id__c, BRNCH_SCTN_CD__c='test',
                    Branch_Summary_Key__c = '992013061234567890');
        insert branch;
        
        cont.AccountNum = '1234567890';
        cont.InternalCampaignId= '201306';
        cont.MarketId = mkt.Market_Id__c;
        cont.GetBranches(201306);
        cont.RefreshBranches();
        cont.InternalCampaignId= 'CMPGN201305_201306';
        cont.RefreshBranches();
        cont.BranchSearchCampaignId = '201306';
        cont.RefreshBranches();
        cont.BranchSearchCampaignId= 'CMPGN201305_201306';
        cont.RefreshBranches();
    }
}