youfull/objects/Business_Plan__c.object
<CustomObject>
    <fields>
        <fullName>Business_Plan_Parameter__c</fullName>
        <label>Business Plan Parameter</label>
        <referenceTo>Business_Plan_Parameter__c</referenceTo>
        <relationshipLabel>Business Plans</relationshipLabel>
        <relationshipName>Business_Plans</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Market_Id__c</fullName>
        <label>Market Id</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Mrkt_Id_Acct_Nr_Key__c</fullName>
        <description>Mrkt_Id_Acct_Nr_Key</description>
        <externalId>true</externalId>
        <inlineHelpText>Mrkt_Id_Acct_Nr_Key</inlineHelpText>
        <label>Business Plan Key</label>
        <length>50</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Business Plan</label>
    <nameField>
        <displayFormat>BP-{0000000}</displayFormat>
        <label>Business Plan Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Business Plans</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

youfull/objects/Business_Plan_Parameter__c.object
<CustomObject>
    <fields>
        <fullName>Market_Id__c</fullName>
        <label>Market Id</label>
        <referenceTo>Market__c</referenceTo>
        <relationshipLabel>Business Plan Parameters</relationshipLabel>
        <relationshipName>Business_Plan_Parameters</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Business Plan Parameter</label>
    <nameField>
        <label>Business Plan Parameter  Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Business Plan Parameters</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

youfull/classes/Test_RecordBuilder.cls
/***************************************************************************
 Name          : Test_RecordBuilder
 Created By    : Barkha Jain (JDC)
 Description   : Test class for RecordBuilder
 Created Date  : Nov 6, 2013                
****************************************************************************/
@isTest
private class Test_RecordBuilder {
	
	//----------------------------------------------------------------------------
    // Method Name  : testRecordBuilder
    // Description  : Method for Test Coverage of Class : RecordBuilder
    //----------------------------------------------------------------------------
    static testMethod void testRecordBuilder() {
    	User usr = TestDataHelper.createUser('1234', 'XZ1', 'Avon Leader', false);
    	usr.LDRSHP_TITL_LVL_NBR__c = '1';
    	insert usr;
    	
    	Business_Plan_Parameter__c pParam = new Business_Plan_Parameter__c(Name = 'Test Param');
    	Business_Plan__c bp = new Business_Plan__c(Mrkt_Id_Acct_Nr_Key__c = 'DE1234', Market_Id__c = 'DE' );
    	
        System.runAs(usr){
        	insert pParam;
        	
        	bp.Business_Plan_Parameter__c = pParam.Id;
        	insert bp;
        }
        
        Test.startTest();
        Map<String, String> fieldValues = RecordBuilder.buildRecord(bp.Id);
        //verify result
        system.assert(fieldValues.get('Mrkt_Id_Acct_Nr_Key__c') == 'DE1234');
        Test.stopTest();
    }
}