youfull/objects/CDW_Market_Report__c.object
<CustomObject>
    <fields>
        <fullName>Branch__c</fullName>
        <description>Branch</description>
        <label>Branch</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>FileName__c</fullName>
        <description>R+&lt;MRKT_ID&gt;+_+&lt;ACCT_NR&gt;+_BR_+&lt;CMPGN&gt;.xls</description>
        <label>FileName</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Market__c</fullName>
        <label>Market</label>
        <referenceTo>Market__c</referenceTo>
        <relationshipLabel>CDW Market Reports (Market2)</relationshipLabel>
        <relationshipName>CDW_Market_Reports1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Profile__c</fullName>
        <description>Select Profile</description>
        <label>Profile</label>
        <picklist>
            <picklistValues>
                <fullName>Avon Leader</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Avon Zone Manager</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Avon Division Manager</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Avon Sales Leader - Spanish</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Report_Code__c</fullName>
        <description>Report code, e.g. &apos;BR&apos; for the branch report</description>
        <inlineHelpText>Report code, e.g. &apos;BR&apos; for the branch report</inlineHelpText>
        <label>Report Code</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>User_Type_Index__c</fullName>
        <description>E.g. &apos;R&apos; for representative</description>
        <inlineHelpText>E.g. &apos;R&apos; for representative</inlineHelpText>
        <label>User Type Index</label>
        <length>5</length>
        <type>Text</type>
    </fields>
    <label>CDW Market Report</label>
    <nameField>
        <label>CDW Market Reports Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CDW Market Reports</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

youfull/objects/MailPlan_Order_Oppty__c.object
<CustomObject>
    <fields>
        <fullName>CMPGN_NR__c</fullName>
        <label>CMPGN_NR</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>MRKT_ID__c</fullName>
        <label>MRKT_ID</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Market__c</fullName>
        <label>Market</label>
        <referenceTo>Market__c</referenceTo>
        <relationshipLabel>MailPlan_Order_Opptys</relationshipLabel>
        <relationshipName>MailPlan_Order_Opptys</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>MailPlan_Order_Oppty</label>
    <nameField>
        <displayFormat>MPLN-{000000}</displayFormat>
        <label>Mail Plan Order Oppty Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>MailPlan_Order_Opptys</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

youfull/objects/Market__c.object
<CustomObject>
    <fields>
        <fullName>CMPGN_NR__c</fullName>
        <label>CMPGN_NR</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Is_ALMPLUS_Enabled__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Check to enable/disable ALM+ functionality</description>
        <inlineHelpText>Check to enable/disable ALM+ functionality</inlineHelpText>
        <label>Is ALM+ Enabled</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Lead_Purge_Min__c</fullName>
        <label>Lead Purge Min Age</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Legal_Purge_Age__c</fullName>
        <description>Unit is in hours. After the specified hours are elapsed, the leads associated to this market will be deleted after applying few other conditions which are specified in Legal_Purge_SOQL_Condition field on this market record.</description>
        <inlineHelpText>Unit is in hours. After the specified hours are elapsed, the leads associated to this market will be deleted after applying few other conditions which are specified in Legal_Purge_SOQL_Condition field on this market record.</inlineHelpText>
        <label>Legal Purge Age</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Mail_Plan_Enabled__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Mail Plan Enabled</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Market_Id__c</fullName>
        <externalId>true</externalId>
        <label>MRKT_ID</label>
        <length>15</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Mgr_Omniture_Suite_Name__c</fullName>
        <description>This Suite is used for ZM/DM Omniture tracking.</description>
        <label>Mgr Omniture Suite Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>NEXT_1_CMPGN_NR__c</fullName>
        <label>NEXT_1_CMPGN_NR</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Omniture_Suite_Name__c</fullName>
        <label>Omniture Suite Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PREV_1_CMPGN_NR__c</fullName>
        <label>PREV_1_CMPGN_NR</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <label>Market</label>
    <nameField>
        <label>Market Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Markets</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

youfull/objects/Sales_Org_Summary__c.object
<CustomObject>
    <fields>
        <fullName>MRKT_KEY__c</fullName>
        <label>Market</label>
        <referenceTo>Market__c</referenceTo>
        <relationshipLabel>Sales Org Summary</relationshipLabel>
        <relationshipName>Sales_Org_Summary</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SLS_ORG_DESC_TXT__c</fullName>
        <label>Area</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SLS_ORG_LVL_DESC_TXT__c</fullName>
        <label>Sales Org Type</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ZONE_MGR__c</fullName>
        <label>Zone Manager</label>
        <referenceTo>User</referenceTo>
        <relationshipLabel>Zone Summary</relationshipLabel>
        <relationshipName>Zone_Summary</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Sales Org Summary</label>
    <nameField>
        <label>Sales Org Summary Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sales Org Summaries</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

youfull/objects/ZM_Report_Translation__c.object
<CustomObject>
    <fields>
        <fullName>Application_Context__c</fullName>
        <label>Application Context</label>
        <picklist>
            <picklistValues>
                <fullName>Quick Links</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Report Center</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>My Team Orders</fullName>
            </picklistValues>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <fields>
        <fullName>Is_Mail_Plan_Specific__c</fullName>
        <label>Is_Mail_Plan_Specific</label>
        <length>1</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Language_Code__c</fullName>
        <label>Language Code</label>
        <picklist>
            <picklistValues>
                <fullName>en_PH</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>en_US</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ro</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>es</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>es_MX</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>en_GB</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>MRKT_ID__c</fullName>
        <description>To relate to the Market Object</description>
        <label>Market</label>
        <referenceTo>Market__c</referenceTo>
        <relationshipLabel>ZM Report Market Translations</relationshipLabel>
        <relationshipName>ZM_Report_Market_Translations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Market_Id__c</fullName>
        <label>Market Id</label>
        <picklist>
            <picklistValues>
                <fullName>62</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>66</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>100</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>999</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>55</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>23</fullName>
            </picklistValues>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <fields>
        <fullName>Report_Id__c</fullName>
        <label>Report Id</label>
        <length>18</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Report_Label__c</fullName>
        <label>Report Label</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Report_Role__c</fullName>
        <label>Report Role</label>
        <picklist>
            <picklistValues>
                <fullName>Zone</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Division</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Admin</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Training</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Standard Leader</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sales</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Report_URL__c</fullName>
        <label>Report URL</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Sort_Order__c</fullName>
        <label>Sort Order</label>
        <precision>3</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>ZM Report Market Translation</label>
    <nameField>
        <label>ZM Report Translation Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>ZM Report Market Translations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

youfull/classes/ALM_Controller_ReportCenter.cls
/***************************************************************************
 Name          : ALM_Controller_ReportCenter 
 Description   : Clone of ReportCenter
 Created By    : Parul Gupta 
 Created Date  : 14 Feb, 2013                
****************************************************************************/
public class ALM_Controller_ReportCenter {

    public Boolean redirectOnly {get; set;}
    public Boolean multipleZones {get; set;}
    public Boolean isALMPlusEnabled {get; set;}
    public String type {get; set;}
    public String templateReportURL {get; set;}
    public String sfdcURL {get; set;}
    public Id selectedStandardReport {get; set;}
    private Id selectedLeadReport {get; set;}
    public String selectedPersonalReport {get; set;}
    public String selectedOfflineReport {get; set;}
    public String userProfile {get;set;}
    public String selectedZone {get; set;}
    public String selectedStdZone {get; set;}
    public String selectedStandardCampaign {get; set;}
    public String selectedPersonalCampaign {get; set;}
    public String selectedOfflineCampaign {get; set;}
    public String thrShldAge {get; set;}
    public String test {get; set;}
    public boolean DispCampaign {get; set;}
    private List<SelectOption> standardReportList = new List<SelectOption>();
    private List<SelectOption> LeadReportList = new List<SelectOption>();
    private List<SelectOption> personalReportList = new List<SelectOption>();
    private List<SelectOption> offlineReportList = new List<SelectOption>();
    private Map<Id,CDW_Market_Report__c> offlineReportMap = new Map<Id,CDW_Market_Report__c>();
    public Map<String, String> mapForReportFilter{get;set;}
    private List<SelectOption> zoneList = new List<SelectOption>();
    private Market__c market;
    private User currentUser;
    private String mp;
    
    /*public String selectedClosed {get; set;}
    public String selectedCampaign {get; set;}
    public String selectedEligible {get; set;}
    public String selectedLdType {get; set;}
    private List<SelectOption> closedList = new List<SelectOption>();
    private List<SelectOption> campaignList1 = new List<SelectOption>();
    private List<SelectOption> eligibleList = new List<SelectOption>();
    private List<SelectOption> ldTypeList = new List<SelectOption>();*/
    
    public String omniSuitName {get; set;} //variable added by Raktim for Omniture - on 23rd Sept, 2013

    public ALM_Controller_ReportCenter() {
        this.type = 'Report'; // For now, only dealing with reports
        String reportName = ApexPages.CurrentPage().getParameters().get('report');
        initializeData(reportName); 
        
        this.selectedPersonalCampaign = market.CMPGN_NR__c;
        this.selectedOfflineCampaign = market.CMPGN_NR__c;
        this.selectedStandardCampaign = ApexPages.CurrentPage().getParameters().get('campaign');
        
        system.debug ('after initialize');
        
       // If campaign is not specified, default to current
        if (this.selectedStandardCampaign == null) {
           
            if(!market.Mail_Plan_Enabled__c){
            this.selectedStandardCampaign = market.CMPGN_NR__c;            
            }else{
            //Added by Milon on 7/9/2013
            String  mailPlanCampaignNumbr = '';
            if (currentUser.Profile.Name.contains('Division')){
            	//Changed by Milon on 10/17
                //MailPlanUtils mp = new MailPlanUtils(market);//changed by swarnava:added argument
                //MailPlan_Order_Oppty__c mop =   mp.getMailPlanForDivManager(currentUser);
                //mailPlanCampaignNumbr = mop.CMPGN_NR__c;
                mailPlanCampaignNumbr = market.CMPGN_NR__c;
            }else {
            	
            	if (currentUser.Profile.Name.contains('Sales')) {
            		
            	}
            	else {
            		mailPlanCampaignNumbr = market.CMPGN_NR__c;
                   String zones = getZones(market.Id);
                   mailPlanCampaignNumbr =  MailPlanUtils.getMailPlanCampaignZMDM(zones, currentUser.MRKT_ID__c);
            	}
            }
            
           if(mailPlanCampaignNumbr == market.CMPGN_NR__c)
           this.selectedStandardCampaign = market.CMPGN_NR__c;
           else if(mailPlanCampaignNumbr == market.NEXT_1_CMPGN_NR__c)
           this.selectedStandardCampaign = market.NEXT_1_CMPGN_NR__c;
           else
           this.selectedStandardCampaign = market.CMPGN_NR__c;
           }
        }
        system.debug ('at the end of get default campaign');
        
        this.redirectOnly = (selectedStandardReport != null) && (selectedStandardCampaign != null);
        System.debug('Selected campaign: ' + selectedStandardCampaign + ' and reportName: ' + reportName + ' and reportId: ' + selectedStandardReport);
    }
    
    /*
    ***  MF 2/17 - Not needed at this point.  Zonelist is shown if the list > 1.  This shouldn't
    be the case for SL
    public boolean isSalesLeader{ 
    	get{
	    	if(currentUser.Profile.Name.contains('Standard Leader')
	    	|| currentUser.Profile.Name.contains('Sales Leader')){
	            return true;
	    	}else{
	    		return false;
	    	}
    	}set;
    } */
    
    private void initializeData(String selectedReportName) {
    	
    	// Initialize user/person
    	currentUser = [SELECT Id, Profile.Name, MRKT_ID__c, 
							DFALT_DIV_NM__c, DFALT_ZONE_CD__c,
							ACCT_NR__c, LanguageLocaleKey,
							UserRole.Name
                       		FROM User 
                       		WHERE Id = :UserInfo.getUserId() 
                       		LIMIT 1];    
  		
  		/*userProfile = currentUser.Profile.Name;
        if(userProfile.contains('Zone Manager')){
            userProfile='ZM';
        }
        else if(userProfile.contains('Division Manager')){
            userProfile='DM';
        }*/
        
        
        if(!currentUser.Profile.Name.contains('Standard Leader')
        && !currentUser.Profile.Name.contains('Sales Leader')){       	
	        
	        // Initialize zones
	        initializeZoneList();
	        if (currentUser.Profile.Name.contains('Division')) {
	            multipleZones = true;
	            selectedZone = currentUser.DFALT_DIV_NM__c;
	        } else {	            
	            selectedZone = currentUser.DFALT_ZONE_CD__c;
	        }
	        System.debug('zoneList:'+zoneList);
	        if(zoneList.size() > 1){
	            multipleZones = true;
	        }
	        	            
        }
            
        // Initialize campaign
        // 'Mgr_Omniture_Suite_Name__c' field included in SOQL - by Raktim on 8th Oct 2013
        this.market = [SELECT Id,Market_Id__c, PREV_1_CMPGN_NR__c, Mail_Plan_Enabled__c,CMPGN_NR__c, NEXT_1_CMPGN_NR__c, Is_ALMPLUS_Enabled__c, Lead_Purge_Min__c, Legal_Purge_Age__c,  
                       Omniture_Suite_Name__c, Mgr_Omniture_Suite_Name__c  FROM Market__c 
                        where Market_Id__c = :currentUser.MRKT_ID__c];
       
         //is lead enabled
        isALMPlusEnabled = this.market.Is_ALMPLUS_Enabled__c;
       
        // Initialize template URL
        templateReportURL = URL.getSalesforceBaseUrl().toExternalForm() +'/$REPORT?pv0=$CAMPAIGN';
        
        //variable populated from market. Omniture Change - on 23rd Sept, 2013
        //omniSuitName = market.Omniture_Suite_Name__c;
        omniSuitName = market.Mgr_Omniture_Suite_Name__c; // modified by Raktim - on 8th Oct, 2013
        
        //thresold age
        /*if(isALMPlusEnabled)
            thrShldAge = String.valueOf(this.market.Legal_Purge_Age__c - this.market.Lead_Purge_Min__c);
        else
            thrShldAge =  null;
        
        sfdcURL = URL.getSalesforceBaseUrl().toExternalForm();
        mapForReportFilter = new Map<String, String>();
        mapForReportFilter.put('All','00OJ0000000YM89');
        mapForReportFilter.put('Rep','00OJ0000000YQm8');
        mapForReportFilter.put('Customer','00OJ0000000YUGu');
        
        ldTypeList.add(new SelectOption('00OJ0000000YM89','All'));
        ldTypeList.add(new SelectOption('00OJ0000000YQm8','Rep'));
        ldTypeList.add(new SelectOption('00OJ0000000YUGu','Customer'));*/
        
        
        // Initialize reports
        /****
         * Retrieve Reports from the translation table
         **/
        mp=(this.market.Mail_Plan_Enabled__c?'Y':'N');    //Added by swarnava:Mail Plan
        
		system.debug('profile name = ' + currentUser.Profile.Name);
        
        for(ZM_Report_Translation__c z : [Select z.Sort_Order__c
                                               , z.Report_URL__c
                                               , z.Report_Label__c
                                               , z.Report_Id__c
                                               , z.Market_Id__c
                                               , z.Language_Code__c
                                               , z.Id
                                               , z.Application_Context__c
                                               , z.Report_Role__c 
                                            From ZM_Report_Translation__c z
                                           where Language_Code__c = :currentUser.LanguageLocaleKey
                                            and Market_Id__c includes(:currentUser.MRKT_ID__c)
                                            and Application_Context__c includes ('Report Center','Lead')
                                            and Is_Mail_Plan_Specific__c IN (null,:mp)      //changed by swarnava:Mail Plan 
                                           order by sort_order__c])
        {
        	
        	system.debug('z report role = ' + z.Report_Role__c);
            if(currentUser.Profile.Name == null || currentUser.Profile.Name.containsIgnoreCase(z.Report_Role__c))
                standardReportList.add(new SelectOption(z.Report_URL__c, z.Report_Label__c));   
                system.debug ('add to standard report list' + z.Report_Label__c);
        }
    
      /*eligibleList.add(new SelectOption('0',System.Label.No));
        eligibleList.add(new SelectOption('1',System.Label.Yes));
        
        closedList.add(new SelectOption('0',System.Label.No));
        closedList.add(new SelectOption('1',System.Label.Yes));*/
        
             
        for(Report r : [SELECT Id, OwnerId, Name, Description, DeveloperName 
                          FROM Report 
                         WHERE OwnerId = :currentUser.Id ORDER BY Name]) {
            personalReportList.add(new SelectOption(r.Id, r.Name));
        }
         
        // Initialize market reports
        list<CDW_Market_Report__c>marketReports = new list<CDW_Market_Report__c>();
       
        if (currentUser.Profile.Name.contains('Zone')) {
	        for(CDW_Market_Report__c  mr : [SELECT Name, Branch__c, FileName__c, Market__c, Market__r.Market_Id__c, Profile__c, Report_Code__c, User_Type_Index__c 
	                                          FROM CDW_Market_Report__c 
	                                         WHERE User_Type_Index__c = 'Z' AND Market__r.Market_Id__c = :currentUser.MRKT_ID__c ORDER BY Name])
	           marketReports.add(mr);
        }
           
        if (currentUser.Profile.Name.contains('Division')) {
            for(CDW_Market_Report__c mr2 : [SELECT Name, Branch__c, FileName__c, Market__c, Market__r.Market_Id__c, Profile__c, Report_Code__c, User_Type_Index__c 
                                              FROM CDW_Market_Report__c
                                             WHERE User_Type_Index__c = 'D' AND Market__r.Market_Id__c = :currentUser.MRKT_ID__c ORDER BY Name])
            marketReports.add(mr2);
        }
        
        if (currentUser.Profile.Name.contains('Sales')) {
            for(CDW_Market_Report__c mr3 : [SELECT Name, Branch__c, FileName__c, Market__c, Market__r.Market_Id__c, Profile__c, Report_Code__c, User_Type_Index__c 
                                              FROM CDW_Market_Report__c
                                             WHERE User_Type_Index__c = 'S' AND Market__r.Market_Id__c = :currentUser.MRKT_ID__c ORDER BY Name])
            marketReports.add(mr3);
        }
        String filename;
        for (CDW_Market_Report__c report : marketReports) {
            filename = report.User_Type_Index__c + '$ZONE_' + report.Report_Code__c + '_$CAMPAIGN_' + currentUser.LanguageLocaleKey;
            offlineReportList.add(new SelectOption(report.Id+':'+filename, report.Name));
            //offlineReportMap.put(report.Id, report);
        }
        system.debug ('end of inialize');
    }
    
    // New Method - Omniture Addition
    public String getOmniturePageName()      
    {  
        return ALMPlusUtils.generateOmniturePageName('ZM_ReportCenter', null, currentUser.Profile.Name);         
    } //this is for getting page name mapping for omniture
    
    private void initializeZoneList() {
        
        ZM_UtilityClass util = new ZM_UtilityClass();
        util.SetVariable();
        zoneList = util.getZoneList();
    }
    
    public void doNothing()
    {

    }
        
    public List<SelectOption> getStandardReportList() {
        return standardReportList;
    }
    
    /*public List<SelectOption> getLeadReportList() {
        return leadReportList;
    }
    
    public Id getSelectedLeadReport() {
        return selectedLeadReport;
    }
    
    public void setSelectedLeadReport(Id leadReport) {
        selectedLeadReport = leadReport;
    }*/
    
    public List<SelectOption> getPersonalReportList() {
        return personalReportList;
    }
    
    public Boolean getShowPersonalReport() {
        return personalReportList.size() > 0;
    }
    
    public List<SelectOption> getOfflineReportList() {
        return offlineReportList;
    }

    public List<SelectOption> getZoneList() {
        return zoneList;
        
    }
    
    /*public List<SelectOption> getLdTypeList() {
        return ldTypeList;
    }
    
    public List<SelectOption> getClosedList() {
        return closedList;
    }
    
    public List<SelectOption> getEligibleList() {
        return eligibleList;
    }*/
            
    public List<SelectOption> getCampaignList() {
        
        List<SelectOption> options = new List<SelectOption>();
        
        options.add(new selectoption(market.PREV_1_CMPGN_NR__c, market.PREV_1_CMPGN_NR__c)); // Prior
        options.add(new selectoption(market.CMPGN_NR__c, market.CMPGN_NR__c)); // Current
        options.add(new selectoption(market.NEXT_1_CMPGN_NR__c, market.NEXT_1_CMPGN_NR__c)); // Next
        return options;
    }
    
    /*public List<SelectOption> getLeadCampaignList() {
        
        List<SelectOption> options = new List<SelectOption>();
        
        options.add(new selectoption(market.CMPGN_NR__c, market.CMPGN_NR__c)); // Current
        options.add(new selectoption(market.PREV_1_CMPGN_NR__c, market.PREV_1_CMPGN_NR__c)); // Prior
        //options.add(new selectoption(market.NEXT_1_CMPGN_NR__c, market.NEXT_1_CMPGN_NR__c)); // Next
        return options;
    }*/

    public String getReportURL() {
        String reportURL = templateReportURL;
        if (selectedStandardReport != null) {
            reportURL.replace('$REPORT', selectedStandardReport);
        }
        if (selectedStandardCampaign != null) {
            reportURL.replace('$REPORT', selectedStandardCampaign);
        }
        System.debug('URL for redirect is: ' + reportURL);
        return reportURL;
    }
    public PageReference redirectToStandardReport()
    {
        PageReference p = new PageReference(selectedStandardReport);
        p.getParameters().put('pv0', selectedStandardCampaign);
        p.getParameters().put('pv1', selectedStdZone);
        p.setRedirect(true);
        return p;
        
    }
    
    public PageReference selectedPersonalReport()
    {
        PageReference p = new PageReference(URL.getSalesforceBaseUrl().toExternalForm()+'/'+selectedPersonalReport);
        p.getParameters().put('pv0', selectedStandardCampaign);
        p.getParameters().put('pv1', selectedStdZone);
        
        p.setRedirect(true);
        return p;
    }
    
    public PageReference openOfflineReport()
    {
        
        
        string reportId = selectedOfflineReport.split(':')[0];
        string filename = selectedOfflineReport.split(':')[1];
        //ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.INFO, 'reportId: '+reportId +'  filename: '+filename ));
        //return null;
        string fileUrl = getAttachmentURL(reportId, filename);
        
        if(fileUrl == null || fileUrl == '')
          return null;
        PageReference p = new PageReference(fileUrl);
        p.setRedirect(true);
        return p;
    }
    
    public String getAttachmentId(CDW_Market_Report__c marketReport, String campaign) {   
        Id attachmentId;        
        String fileName = marketReport.User_Type_Index__c + selectedZone + '_' + 
                marketReport.Report_Code__c + '_' + campaign + '_' + currentUser.LanguageLocaleKey; //TODO: make the naming convention configuration driven!
                        
        List<Attachment> attachments = new List<Attachment>();
        for(Attachment a : [  select Id from Attachment
                                where Name like :fileName 
                                and Parent.Id = :marketReport.Id 
                                order by CreatedDate desc
                                limit 1])
            attachments.add(a);
                
        if (attachments.size() > 0) {
            attachmentId = attachments[0].Id;
        }
        
        System.debug('File name: ' + fileName + ' and Attachment Id: ' + attachmentId);         
        return attachmentId;                     
    }
    
    @RemoteAction
    public static String getAttachmentId(String reportId, String filename) {   
        Id attachmentId;
        filename += '%';
                                
        List<Attachment> attachments = [select Id from Attachment
                where Name like :filename
                and Parent.Id = :reportId 
                order by CreatedDate desc
                limit 1];
                
        if (attachments.size() > 0) {
            attachmentId = attachments[0].Id;
        }
        
        System.debug('File name: ' + filename + ' and Attachment Id: ' + attachmentId);         
        return attachmentId;                     
    }   
    
    @RemoteAction
    public static String getAttachmentURL(String reportId, String filename) {
        String attachmentURL = '';
        Id attachmentId = getAttachmentId(reportId, filename);
        if (attachmentId != null) {
            attachmentURL = '/servlet/servlet.FileDownload?file=' + attachmentId;
        }
        System.debug('===================== In ReportCenterController.getAttachmentURL(). URL for attachment is: ' + attachmentURL);
        return attachmentURL;
    }
    
    public String getZones(Id id)
    {
        String zones = '';
        list<Sales_Org_Summary__c> lstSLSOrgs= [ select SLS_ORG_DESC_TXT__c 
                                                   from Sales_Org_Summary__c 
                                                   where ZONE_MGR__c=:Userinfo.getUserId() 
                                                   and MRKT_KEY__c = :id
                                                   and SLS_ORG_LVL_DESC_TXT__c = 'Z'
                                                   order by SLS_ORG_DESC_TXT__c asc ];   
        Set<String> uniqueSlsOrgDescSet = new Set<String>();
        if(lstSLSOrgs.size()>0)
        {
            for(Sales_Org_Summary__c slsOrg : lstSLSOrgs) {
                    uniqueSlsOrgDescSet.add(slsOrg.SLS_ORG_DESC_TXT__c);
            }   
        }
        
        for(String zoneName : uniqueSlsOrgDescSet) {
                zones += '\'' + zoneName + '\',';
        }
        zones = (zones.length() > 0) ? zones.left(zones.length() - 1) : '\'\'';
        System.debug('\n ######### USER ZONE LIST '+zones);
        return zones;
        
    }
    
   
}