youfull/objects/eTools_Widget__c.object
<CustomObject>
    <fields>
        <fullName>Market__c</fullName>
        <label>Market</label>
        <referenceTo>Market__c</referenceTo>
        <relationshipLabel>eTools_Widgets</relationshipLabel>
        <relationshipName>eTools_Widgets</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>eTools_Widget</label>
    <nameField>
        <label>eTools_Widget Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>eTools_Widgets</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

youfull/objects/Leader_Title__c.object
<CustomObject>
    <fields>
        <fullName>Market__c</fullName>
        <label>Market</label>
        <referenceTo>Market__c</referenceTo>
        <relationshipLabel>Leader Titles</relationshipLabel>
        <relationshipName>Leader_Titles</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Leader Title</label>
    <nameField>
        <displayFormat>LDT-{000000}</displayFormat>
        <label>Leader Title Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Leader Titles</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

youfull/objects/Market__c.object
<CustomObject>
    <fields>
        <fullName>EARN_ILLT_VIDEO_LNK_TYP__c</fullName>
        <label>Erng Illustrtor Video Lnk Typ</label>
        <picklist>
            <picklistValues>
                <fullName>Link</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Video-Windows</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Video-Quick Time</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Video-You Tube</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Widget</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Market_Id__c</fullName>
        <externalId>true</externalId>
        <label>MRKT_ID</label>
        <length>15</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Market</label>
    <nameField>
        <label>Market Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Markets</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

youfull/classes/Test_EarningCalController.cls
/***************************************************************************
 Name         : Test_EarningCalController
 Created By   : Saurabh Gupta (JDC)
 Description  : Test class for EarningCalController
 Created Date : Oct. 25, 2013                
****************************************************************************/

@isTest
private class Test_EarningCalController {  

    //----------------------------------------------------------------------------
    // Method Name  : testEarningCalController
    // Description  : Method for Test Coverage of Class : EarningCalController
    //----------------------------------------------------------------------------  
    public static testmethod void testEarningCalController() {
        String mktIdKey = 'TESTEARN1234';
        Market__c mrkt;
        
        //Create and Insert Object : User
        User testUsr = TestDataHelper.createUser(mktIdKey, 'XZ1', 'Avon Leader', true); 
        
        System.runAs(testUsr) {
            //Create and Insert Object : Market
            mrkt = TestDataHelper.createMarket(mktIdKey, false);
            mrkt.OwnerId = testUsr.Id;
            mrkt.EARN_ILLT_VIDEO_LNK_TYP__c = 'Link';
            insert mrkt;
        }
        
        //Create and Insert Object : eTools_Widget__c
        eTools_Widget__c eTools = TestDataHelper.createEToolsWidget(String.valueOf(mrkt.Id), mrkt.EARN_ILLT_VIDEO_LNK_TYP__c, true);
        
        List <Leader_Title__c> leaderTitleList = TestDataHelper.createLeaderTitlesList(mrkt.Id, mrkt.Market_Id__c, true);
        
        EarningCalController ctlr;
        
        System.runAs(testUsr) {
            ctlr = new EarningCalController();
            
            //eTools_Widget__c data is available
            ctlr.loadData();
            System.assertEquals(ctlr.lst_EstimtdErngLevel.size(), 9);
            System.assert(EarningCalController.mapEstimtdErng == null);
            
            EarningCalController.getData(0);
            EarningCalController.getPicture(0, false);
            System.assertEquals(ctlr.lst_EstimtdErngLevel.size(), 9);
            System.assertEquals(EarningCalController.mapEstimtdErng.size(), 9);
            
            EarningCalController.getData(1);
            EarningCalController.getPicture(1, false);
            System.assertEquals(ctlr.lst_EstimtdErngLevel.size(), 9);
            System.assertEquals(EarningCalController.mapEstimtdErng.size(), 9);
            
            EarningCalController.getData(4);
            EarningCalController.getPicture(4, false);
            System.assertEquals(ctlr.lst_EstimtdErngLevel.size(), 9);
            System.assertEquals(EarningCalController.mapEstimtdErng.size(), 9);
                        
            EarningCalController.getData(10);
            EarningCalController.getPicture(10, false);
        }   
        
        PageReference pageRef = Page.EarningCalculatorPage;
        pageRef.getParameters().put('repDetailAcctNbr', mktIdKey); 
        Test.setCurrentPage(pageRef);  
        
        System.runAs(testUsr) {
            ctlr = new EarningCalController();
            ctlr.loadData();
            
            ctlr.getOmniturePageName();
            ctlr.callRepDetails();       
        }
    }
}