youfull/objects/Geo_Level_1__c.object
<CustomObject>
    <fields>
        <fullName>MRKT_ID__c</fullName>
        <externalId>true</externalId>
        <label>MRKT_ID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Geo Level 1</label>
    <nameField>
        <label>Geo Level 1 Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Geo Level 1</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

youfull/objects/Geo_Level_2__c.object
<CustomObject>
    <fields>
        <fullName>Geo_Level_1__c</fullName>
        <label>Geo Level 1</label>
        <referenceTo>Geo_Level_1__c</referenceTo>
        <relationshipLabel>Geo Level 2</relationshipLabel>
        <relationshipName>Geo_Level_2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>MRKT_ID__c</fullName>
        <externalId>true</externalId>
        <label>MRKT_ID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Geo Level 2</label>
    <nameField>
        <label>Geo Level 2 Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Geo Level 2</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

youfull/objects/Geo_Level_3__c.object
<CustomObject>
    <fields>
        <fullName>Geo_Level_2__c</fullName>
        <label>Geo Level 2</label>
        <referenceTo>Geo_Level_2__c</referenceTo>
        <relationshipLabel>Geo Level 3</relationshipLabel>
        <relationshipName>Geo_Level_3</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>MRKT_ID__c</fullName>
        <externalId>true</externalId>
        <label>MRKT_ID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Geo Level 3</label>
    <nameField>
        <label>Geo Level 3 Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Geo Level 3</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

youfull/objects/Geo_Level_4__c.object
<CustomObject>
    <fields>
        <fullName>Geo_Level_3__c</fullName>
        <label>Geo Level 3</label>
        <referenceTo>Geo_Level_3__c</referenceTo>
        <relationshipLabel>Geo Level 4</relationshipLabel>
        <relationshipName>Geo_Level_4</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>MRKT_ID__c</fullName>
        <externalId>true</externalId>
        <label>MRKT_ID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Geo Level 4</label>
    <nameField>
        <label>Geo Level 4 Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Geo Level 4</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

youfull/objects/Market__c.object
<CustomObject>
    <fields>
        <fullName>ASLF_Report_Url__c</fullName>
        <label>ASLF Report Url</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ASLF_Timezone_Offset__c</fullName>
        <defaultValue>0</defaultValue>
        <inlineHelpText>Timezone differential from your ASLF host. For example Bucharest is GMT+2 and is hosted in Corby (GMT) so the offset is -2.</inlineHelpText>
        <label>ASLF Timezone Offset</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Allow_Freeform_Email__c</fullName>
        <description>Profile allowed to send freeform emails</description>
        <inlineHelpText>Profile allowed to send freeform emails</inlineHelpText>
        <label>Allow Freeform Email</label>
        <picklist>
            <picklistValues>
                <fullName>Avon Leader</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Avon Zone Manager</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Avon Division Manager</fullName>
            </picklistValues>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <fields>
        <fullName>Available_Languages__c</fullName>
        <label>Available Languages</label>
        <picklist>
            <picklistValues>
                <fullName>en_US</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>fr</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ro</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>es</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>pl</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>hu</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>cs</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ru</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>es_MX</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>uk</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>sk</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>sh</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>en_MY</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>en_IN</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>bg</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>en_PH</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>en_AU</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>mk</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>bs</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>hr</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>sl</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>en_GB</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>en_CA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>fr_CA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>fi</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>pt_BR</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ka</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>et</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>lv</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>lt</fullName>
            </picklistValues>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <fields>
        <fullName>Business_Plan_KPIs__c</fullName>
        <description>This field decides which KPIs need to be shown in the 90DBP</description>
        <inlineHelpText>This field decides which KPIs need to be shown in the 90DBP</inlineHelpText>
        <label>Business Plan KPIs</label>
        <length>3200</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>CMPGN_END_DT__c</fullName>
        <label>CMPGN_END_DT</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>CMPGN_NR__c</fullName>
        <label>CMPGN_NR</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CMPGN_STRT_DT__c</fullName>
        <label>CMPGN_STRT_DT</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>CURRENT_QRTR__c</fullName>
        <description>Current Quarter number. Format: YYYY-Q#, e.g 2012-Q1</description>
        <inlineHelpText>Current Quarter number. Format: YYYY-Q#, e.g 2012-Q1</inlineHelpText>
        <label>CURRENT_QRTR</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CURRNT_CMPGN_RMN_DAY_CNT__c</fullName>
        <label>CURRNT_CMPGN_RMN_DAY_CNT</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Eligibility_No_Flags__c</fullName>
        <description>Market-specific set of eligibility flags that should be considered while computing the value of the 	Is_Eligible__c field. The flags must be set to &apos;No&apos;/False for user to be eligible</description>
        <inlineHelpText>Select User fields that must be set to &apos;No&apos;/False for user to be eligible. E.g. 
&apos;System Override&apos; must be set to &apos;No&apos;/False</inlineHelpText>
        <label>Eligibility No Flags</label>
        <picklist>
            <picklistValues>
                <fullName>ZM_Override__c</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>System_Override__c</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Out_of_Office__c</fullName>
            </picklistValues>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <fields>
        <fullName>Eligibility_Yes_Flags__c</fullName>
        <description>Market-specific set of eligibility flags that should be considered while computing the value of the 	Is_Eligible__c field. The flags must be set to True for user to be eligible</description>
        <inlineHelpText>Select User fields that must be set to &apos;Yes&apos;/True for user to be eligible. E.g. Opt-In must be set to &apos;Yes&apos;/True</inlineHelpText>
        <label>Eligibility Yes Flags</label>
        <picklist>
            <picklistValues>
                <fullName>Opt_In__c</fullName>
            </picklistValues>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <fields>
        <fullName>Enabled_Action_Item__c</fullName>
        <label>Enabled Action Item</label>
        <picklist>
            <picklistValues>
                <fullName>Orders</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sales</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Current Business</fullName>
            </picklistValues>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <fields>
        <fullName>LeadMandatoryFields__c</fullName>
        <description>Mandatory fields for the Lead Entry Form</description>
        <inlineHelpText>Mandatory fields for the Lead Entry Form</inlineHelpText>
        <label>Lead Mandatory Fields</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Mail_Plan_Enabled__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Mail Plan Enabled</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Market_Administrator__c</fullName>
        <label>Market Administrator</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Markets</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Market_Id__c</fullName>
        <externalId>true</externalId>
        <label>MRKT_ID</label>
        <length>15</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Max_Ldr_Titl_LVL__c</fullName>
        <label>Max_Ldr_Titl_LVL</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>NEXT_1_CMPGN_NR__c</fullName>
        <label>NEXT_1_CMPGN_NR</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>OPERTNL_CMPGN_CMPLTN_PCT__c</fullName>
        <label>OPERTNL_CMPGN_CMPLTN_PCT</label>
        <precision>15</precision>
        <scale>3</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>PREV_1_CMPGN_NR__c</fullName>
        <label>PREV_1_CMPGN_NR</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SPONSOR_QLFYING_ORD_AMT__c</fullName>
        <label>Order Amount for Qualifying Appointment</label>
        <precision>15</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>SPPY_CMPGN_NR__c</fullName>
        <label>SPPY_CMPGN_NR</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>X90_Day_Camp_CNT__c</fullName>
        <label>90 Day Campaign Count</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Market</label>
    <nameField>
        <label>Market Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Markets</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

youfull/objects/User_Sales_Org_Hierarchy__c.object
<CustomObject>
    <fields>
        <fullName>ACCT_NR__c</fullName>
        <label>Account Number</label>
        <length>35</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>MRKT_ID__c</fullName>
        <label>MRKT_ID</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Market__c</fullName>
        <label>Market</label>
        <referenceTo>Market__c</referenceTo>
        <relationshipLabel>User_Sales_Org_Hierarchies</relationshipLabel>
        <relationshipName>User_Sales_Org_Hierarchy</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>SLS_ORG_CD__c</fullName>
        <label>SLS_ORG_CD</label>
        <length>35</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SLS_ORG_LVL_CD__c</fullName>
        <label>SLS_ORG_LVL_CD</label>
        <length>1</length>
        <type>Text</type>
    </fields>
    <label>User_Sales_Org_Hierarchy</label>
    <nameField>
        <displayFormat>USLS-{000000}</displayFormat>
        <label>User Sales Org Hierarchy Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>User_Sales_Org_Hierarchies</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

youfull/classes/ZM_User_Sales_Org_Hierarchy_Handler.cls
public with sharing class ZM_User_Sales_Org_Hierarchy_Handler {
	
	//======================================
	//Generigc Handler for the before delete event
	public void onBeforeDelete(map<Id,User_Sales_Org_Hierarchy__c> oldMap)
	{
		set<String> stringSet = new set<String>();
		for(String s :oldMap.keySet())
		  stringSet.add(s);
		  	removeFromZoneGroup(stringSet);
	}
	
	//===========================================
	//Generigc Handler for the after update event
	public void onAfterInsert(map<Id,User_Sales_Org_Hierarchy__c> oldMap, map<Id,User_Sales_Org_Hierarchy__c> newMap)
	{
		set<String> stringSet = new set<String>();
		for(String s :newMap.keySet())
		  stringSet.add(s);
		  
		addToZoneGroup(stringSet);
		
	}
	
	//===============================================
	//removes the user from the associated zone Group
	public static void removeFromZoneGroup(set<String> userSalesOrgHierarchyUtil)
	{
		//User_Sales_Org_Hierarchy__c.SLS_ORG_CD__c
		System.debug('DEL userSalesOrgHierarchyUtil: '+userSalesOrgHierarchyUtil);
		set<String> zoneGroupNames = new set<String>();
		set<String> zoneUsers = new set<String>();
		set<String> zoneMarket = new set<String>();
		map<String, Id> userAcctMap = new map<String, Id>();
		map<String, Id> zoneGroupMap = new map<String, Id>();
		map<String, String> gMemberMap = new map<String, String>();
		set<String> delGroupMembers = new set<String>();
		
		//create a list of zone Ids
		for(User_Sales_Org_Hierarchy__c u : [Select Id,MRKT_ID__c,SLS_ORG_CD__c,ACCT_NR__c , SLS_ORG_LVL_CD__c
		                                       from User_Sales_Org_Hierarchy__c 
		                                      	where Id in :userSalesOrgHierarchyUtil]){
		   zoneGroupNames.add('Mrkt '+u.MRKT_ID__c+' '+u.SLS_ORG_LVL_CD__c+' '+u.SLS_ORG_CD__c);
		   zoneUsers.add(u.ACCT_Nr__c);
		   zoneMarket.add(u.MRKT_ID__c);
		}
		
		//get the user data
		for(user u : [Select Id, ACCT_Nr__c, MRKT_ID__c from User where ACCT_Nr__c in :zoneUsers ])
		   userAcctMap.put(u.ACCT_Nr__c+'-'+u.MRKT_ID__c, u.Id);
		
		System.debug('::::::::: ADD userAcctMap :::::::: '+userAcctMap);
		
		//retrieve the groups based on the zone - Select g.UserOrGroupId, g.GroupId From GroupMember g
		for(Group g : [Select Id, Name from Group where name in :zoneGroupNames])
		{
			zoneGroupMap.put(g.Name.substring(g.Name.indexOf(' Zone ')+6, g.Name.length()), g.Id);
		}
		
		System.debug('::::::::: DEL zoneGroupMap :::::::: '+zoneGroupMap);
		//create a map that identifies which groups to delete
		for(User_Sales_Org_Hierarchy__c u :  [Select Id,MRKT_ID__c,SLS_ORG_CD__c , ACCT_NR__c from User_Sales_Org_Hierarchy__c where Id in :userSalesOrgHierarchyUtil]){
			
			System.debug('::::::::: DEL u.ACCT_Nr__c+-+u.MRKT_ID__c >>> '+u.ACCT_Nr__c+'-'+u.MRKT_ID__c);
			gMemberMap.put(userAcctMap.get(u.ACCT_Nr__c+'-'+u.MRKT_ID__c)+'-'+zoneGroupMap.get(u.SLS_ORG_CD__c),'DEL');
		}
		System.debug('::::::::: DEL gMemberMap :::::::: '+gMemberMap);
		//retrieve the GroupMember Records to delete
		for(GroupMember gm : [Select Id, UserOrGroupId, GroupId 
		                        from GroupMember 
		                       where GroupId in :zoneGroupMap.values() 
		                         and UserOrGroupId in :userAcctMap.values()] )
		{
			
			System.debug('::::::::: DEL gm.UserOrGroupId+-+gm.GroupId >>> '+gm.UserOrGroupId+'-'+gm.GroupId);
			if(gMemberMap.containsKey(gm.UserOrGroupId+'-'+gm.GroupId))
			   delGroupMembers.add(gm.Id);
		}
		
		System.debug('::::::::: DEL delGroupMembers :::::::: '+delGroupMembers);
		//delete the GroupMember Records
		if(delGroupMembers.size() > 0) deleteUserGroup(delGroupMembers);
	}
	
	@future
	public static void deleteUserGroup(set<String> delGroupMembers)
	{
		list<GroupMember> gMembers = new list<GroupMember>();
		for(String s : delGroupMembers)
		  gMembers.add(new GroupMember(Id=s));
		  
		if(gMembers.size() > 0) delete gMembers; 
	}
	//===========================================
	//Adds the user to the associated zone Group
	@future
	public static void addToZoneGroup(set<string> userSalesOrgHierarchyUtil)
	{
		//User_Sales_Org_Hierarchy__c.SLS_ORG_CD__c
		System.debug('ADD userSalesOrgHierarchyUtil: '+userSalesOrgHierarchyUtil);
		set<String> zoneGroupNames = new set<String>();
		set<String> zoneUsers = new set<String>();
		set<String> zoneMarket = new set<String>();
		map<String, Id> userAcctMap = new map<String, Id>();
		map<String, Id> zoneGroupMap = new map<String, Id>();
		list<GroupMember> gMembers = new list<GroupMember>();
		
		//create a list of zone Ids
		for(User_Sales_Org_Hierarchy__c u : [Select Id,MRKT_ID__c,SLS_ORG_CD__c, ACCT_NR__c , SLS_ORG_LVL_CD__c
		                                       from User_Sales_Org_Hierarchy__c 
		                                      where Id in :userSalesOrgHierarchyUtil]){
		   
		  
		   zoneGroupNames.add('Mrkt '+u.MRKT_ID__c+' '+u.SLS_ORG_LVL_CD__c+' '+u.SLS_ORG_CD__c);
		   zoneUsers.add(u.ACCT_Nr__c);
		   zoneMarket.add(u.MRKT_ID__c);
		}
		
		//get the user data
		for(user u : [Select Id, ACCT_Nr__c, MRKT_ID__c from User where ACCT_Nr__c in :zoneUsers ])
		   userAcctMap.put(u.ACCT_Nr__c+'-'+u.MRKT_ID__c, u.Id);
		
		System.debug('::::::::: ADD userAcctMap :::::::: '+userAcctMap);
		
		//retrieve the groups based on the zone - Select g.UserOrGroupId, g.GroupId From GroupMember g
		for(Group g : [Select Id, Name from Group where name in :zoneGroupNames])
		{
			zoneGroupMap.put(g.Name.substring(g.Name.indexOf(' Z ') + 3, g.Name.length()), g.Id);
		}
		System.debug('::::::::: ADD zoneGroupMap :::::::: '+zoneGroupMap);
		
		for(User_Sales_Org_Hierarchy__c u :  [Select Id,MRKT_ID__c,SLS_ORG_CD__c,ACCT_NR__c from User_Sales_Org_Hierarchy__c where Id in :userSalesOrgHierarchyUtil]){
			System.debug('::::::::: ADD userAcctMap.get(u.ACCT_Nr__c+-+u.MRKT_ID__c) >>> '+userAcctMap.get(u.ACCT_Nr__c+'-'+u.MRKT_ID__c));
			System.debug('::::::::: ADD zoneGroupMap.get(u.SLS_ORG_CD__c) >>> '+zoneGroupMap.get(u.SLS_ORG_CD__c));
			
			gMembers.add(new GroupMember(UserOrGroupId = userAcctMap.get(u.ACCT_Nr__c+'-'+u.MRKT_ID__c)
			                            ,GroupId = zoneGroupMap.get(u.SLS_ORG_CD__c)));
		}
		
		if(gMembers.size() > 0) database.insert(gMembers, false);
		
		System.debug('::::::::: ADD gMembers :::::::: '+gMembers);
	}
	
	//@S-144891 : Commented by Blaine Rothrock on Nov 23
	/*static testMethod void testThisClass()
	{
		//create the user
		User usr = [Select Id from User where Id = :UserInfo.getUserId()];
		usr.MRKT_ID__c = '62';
		usr.ACCT_NR__c = '12345';
		update usr;
		
		//create or retrieve the group
		Group g = new Group( Name = 'Mrkt '+usr.MRKT_ID__c+' Z '+usr.ACCT_NR__c
			                ,Type = 'Regular');
		insert g;
		
		//create the market
		Market__c market = new Market__c(   Name='Test Market',
	                                        Market_Id__c='62',
	                                        Market_Administrator__c=UserInfo.getUserId(),
	                                        Available_Languages__c='en_US',
	                                        CurrencyISOCode='USD',
	                                        Mail_Plan_Enabled__c=true,
	                                        ASLF_Timezone_Offset__c=0.0,
	                                        ASLF_Report_URL__c='http://aslf.report.avon.com',
	                                        CURRNT_CMPGN_RMN_DAY_CNT__c=10,
	                                        CMPGN_NR__c='201204',
	                                        OPERTNL_CMPGN_CMPLTN_PCT__c=25,
	                                        NEXT_1_CMPGN_NR__c='201205',
	                                        CURRENT_QRTR__c='2012-Q3',
	                                        Enabled_Action_Item__c='Orders; Sales; Current Business',
	                                        PREV_1_CMPGN_NR__c='201203',
	                                        SPONSOR_QLFYING_ORD_AMT__c=1,
	                                        CMPGN_STRT_DT__c=System.today(),
	                                        CMPGN_END_DT__c=System.today(),
	                                        Eligibility_No_Flags__c='ZM_Override__c;Out_of_Office__c',
	                                        Eligibility_Yes_Flags__c='Opt_In__c',
	                                        LeadMandatoryFields__c='User_Type__c,FirstName,Day__c,Month__c,Year__c,Geo_Level_1__c,Geo_Level_2__c,Geo_Level_3__c,Geo_Level_4__c,Mobile__c',
	                                        SPPY_CMPGN_NR__c='201001',
	                                        X90_Day_Camp_CNT__c=6,
	                                        Business_Plan_KPIs__c ='Unit_Earnings_dollar;Total_Unit_Sales_dollor;G1_Sales_Leaders_UL;G1_Activity_Rate;Bonus_Earnings;Earnings_from_Personal_Sales;Executive_Earnings;New_G1_UL;New_G1_EUL;New_G1_AUL;Total_and_Est_Earnings_dollar;Personal_Appointments;Qualified_Personal_Appointments;Personal_Volume_dollar;G1_Removals;G1_Active_Representatives',
	                                        Max_Ldr_Titl_LVL__c = 9,
	                                        Allow_Freeform_Email__c='Avon Leader;Avon Division Manager',
	                                        Allow_Free_Emails_For__c ='G1');
                                        
          insert market;
                    
		//create the User_Sales_Org_Hierarchy__c record
		User_Sales_Org_Hierarchy__c u = new User_Sales_Org_Hierarchy__c();
		u.SLS_ORG_LVL_CD__c = 'Z';
		u.SLS_ORG_CD__c = '111';
		u.Market__c = market.Id; 
		u.MRKT_ID__c = '62';
		u.MRKT_ID_ACCT_NR_SLS_ORG_KEY__c = '620000000129660111'; 
        u.ACCT_NR__c = '12345';
        //call the insert method
        insert u;
		
		//verify results
		//System.assertEquals(usr.Id, [select UserOrGroupId from GroupMember where UserOrGroupId = :usr.Id and GroupId = :g.Id].UserOrGroupId);
		
		//call the delete method
		delete u;
	}*/

}