youfull/objects/Leader_Title__c.object
<CustomObject>
    <fields>
        <fullName>EXEC_IND__c</fullName>
        <description>Executive Indicator. &apos;Y&apos; means executive</description>
        <inlineHelpText>Executive Indicator. &apos;Y&apos; means executive</inlineHelpText>
        <label>Executive Indicator</label>
        <length>1</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>GENRTN_1_ERNGS_PCT__c</fullName>
        <label>Gen 1 % Earnings</label>
        <precision>15</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>GENRTN_1_MIN_ORD_AMT__c</fullName>
        <label>Gen 1 Minimum Order Amount</label>
        <precision>15</precision>
        <scale>3</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>GENRTN_2_ERNGS_PCT__c</fullName>
        <label>Gen 2 % Earnings</label>
        <precision>15</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>GENRTN_2_MIN_ORD_AMT__c</fullName>
        <label>Gen 2 Minimum Order Amount</label>
        <precision>15</precision>
        <scale>3</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>GENRTN_3_ERNGS_PCT__c</fullName>
        <label>Gen 3 % Earnings</label>
        <precision>15</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>GENRTN_3_MIN_ORD_AMT__c</fullName>
        <label>Gen 3 Minimum Order Amount</label>
        <precision>15</precision>
        <scale>3</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>LANG_CD__c</fullName>
        <label>Language</label>
        <picklist>
            <picklistValues>
                <fullName>en_US</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>fr</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ro</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>pl</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>hu</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ru</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>cs</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>es_MX</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>es</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>uk</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>sh</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>sk</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>en_MY</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>en_IN</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>bg</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>en_PH</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>en_GB</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>fr_CA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>en_CA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>en_AU</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>fi</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>pt_BR</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>sl</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ka</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>et</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>lv</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>lt</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>th</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>LCL_LDRSHP_TITL_CD__c</fullName>
        <label>Title Code</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>LCL_LDRSHP_TITL_LANG_DESC_TXT__c</fullName>
        <label>Title Description</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>LDRSHP_TITL_LVL_NR_NUMBER__c</fullName>
        <formula>VALUE( TEXT(LDRSHP_TITL_LVL_NR__c ))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Leader Title Level Num 2 Num</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>LDRSHP_TITL_LVL_NR__c</fullName>
        <label>Title Level Number</label>
        <picklist>
            <picklistValues>
                <fullName>UQ</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>-2</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>0</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>3</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>4</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>5</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>21</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>6</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>7</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>8</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>9</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>10</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>MIN_GRP_SLS_REQD_AMT__c</fullName>
        <label>Minimum Group Sales Required</label>
        <precision>15</precision>
        <scale>3</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>MIN_PRSNL_SLS_REQD_AMT__c</fullName>
        <label>Minimum Personal Volume Required</label>
        <precision>15</precision>
        <scale>3</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>MIN_REP_RCRTMNTS_REQD_NR__c</fullName>
        <label>Gen 1 Minimum Active Reps</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>MRKT_ID__c</fullName>
        <label>Market Id</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>MRKT_TAG_QLFR_3_NR__c</fullName>
        <label>MRKT_TAG_QLFR_3_NR</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Market__c</fullName>
        <label>Market</label>
        <referenceTo>Market__c</referenceTo>
        <relationshipLabel>Leader Titles</relationshipLabel>
        <relationshipName>Leader_Titles</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Leader Title</label>
    <nameField>
        <displayFormat>LDT-{000000}</displayFormat>
        <label>Leader Title Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Leader Titles</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

youfull/objects/Market__c.object
<CustomObject>
    <fields>
        <fullName>Market_Id__c</fullName>
        <externalId>true</externalId>
        <label>MRKT_ID</label>
        <length>15</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Market</label>
    <nameField>
        <label>Market Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Markets</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

youfull/classes/MarketLeaderTitleUtils.cls
public class MarketLeaderTitleUtils {
	//return list of executive leaders and above for specific market
	public static Set<String> findELeaders(String mktId){
		Set<String> ELeaderTitles = new Set<String>();
		for(Leader_Title__c lt: [Select l.Name, l.MRKT_ID__c, l.LDRSHP_TITL_LVL_NR__c, l.Id, l.EXEC_IND__c From Leader_Title__c l
								 where MRKT_ID__c=:	mktId and EXEC_IND__c ='Y']){
				ELeaderTitles.add(lt.LDRSHP_TITL_LVL_NR__c);							 	
		}
		return ELeaderTitles;
	}
	private Map<String,String> ldrTitles = new Map<String,String>();
	private Map<String, Leader_Title__c> mapLeaderTitle = new Map<String, Leader_Title__c>(); //added Gaziz. 3/16/2012

	public void initialize(User currUser){
		ldrTitles = new Map<String,String>();
		for(Leader_Title__c ldrTitle :[	Select	Market__c, MRKT_TAG_QLFR_3_NR__c, LDRSHP_TITL_LVL_NR__c, LDRSHP_TITL_LVL_NR_NUMBER__c,
												LCL_LDRSHP_TITL_LANG_DESC_TXT__c, 
												LCL_LDRSHP_TITL_CD__c, LANG_CD__c, GENRTN_3_MIN_ORD_AMT__c, 
												GENRTN_3_ERNGS_PCT__c, GENRTN_2_MIN_ORD_AMT__c, 
												GENRTN_2_ERNGS_PCT__c, GENRTN_1_MIN_ORD_AMT__c, 
												GENRTN_1_ERNGS_PCT__c, MIN_PRSNL_SLS_REQD_AMT__c,
												MIN_GRP_SLS_REQD_AMT__c, MIN_REP_RCRTMNTS_REQD_NR__c
												//,EXEC_IND__c
										From 	Leader_Title__c
										where	Market__r.Market_Id__c=:currUser.MRKT_ID__c
										and		LANG_CD__c=:currUser.LanguageLocaleKey])
		{
			//ldrTitles.put(ldrTitle.LDRSHP_TITL_LVL_NR__c,ldrTitle.LCL_LDRSHP_TITL_LANG_DESC_TXT__c);
			ldrTitles.put(ldrTitle.LDRSHP_TITL_LVL_NR__c,ldrTitle.LCL_LDRSHP_TITL_CD__c);
		}
	}		
	
	//return map of Title_Level_Number to Leader_Title_Record
	public Map<String, Leader_Title__c> initializeAndRetMapLT(User currUser) {  //added Gaziz. 3/16/2012
		mapLeaderTitle = new Map<String, Leader_Title__c>();
		for(Leader_Title__c ldrTitle :[	Select	Market__c, MRKT_TAG_QLFR_3_NR__c, LDRSHP_TITL_LVL_NR__c, LDRSHP_TITL_LVL_NR_NUMBER__c,
												LCL_LDRSHP_TITL_LANG_DESC_TXT__c, 
												LCL_LDRSHP_TITL_CD__c, LANG_CD__c, GENRTN_3_MIN_ORD_AMT__c, 
												GENRTN_3_ERNGS_PCT__c, GENRTN_2_MIN_ORD_AMT__c, 
												GENRTN_2_ERNGS_PCT__c, GENRTN_1_MIN_ORD_AMT__c, 
												GENRTN_1_ERNGS_PCT__c, MIN_PRSNL_SLS_REQD_AMT__c,
												MIN_GRP_SLS_REQD_AMT__c, MIN_REP_RCRTMNTS_REQD_NR__c
												,EXEC_IND__c
										From 	Leader_Title__c
										where	Market__r.Market_Id__c=:currUser.MRKT_ID__c
										and		LANG_CD__c=:currUser.LanguageLocaleKey])
		{
			mapLeaderTitle.put(ldrTitle.LDRSHP_TITL_LVL_NR__c,ldrTitle);
		}
		
		return mapLeaderTitle;
	}
	
	//List sorted by Number title badge
	public List<Leader_Title__c> initializeAndRestListSortedByTitleNumber(Id marketId, String languageKey) {
        System.debug('====================== MarketLeaderTitleUtils. marketID : ' + marketID);
        System.debug('====================== MarketLeaderTitleUtils. languageKey : ' + languageKey);
		if ((marketId == null) || 
		         (languageKey == null && languageKey.length() == 0)) {
		         	
		    return null;
		}
		
		List<Leader_Title__c> result = new List<Leader_Title__c>();
		
		result = [Select	Market__c, MRKT_TAG_QLFR_3_NR__c, LDRSHP_TITL_LVL_NR__c, LDRSHP_TITL_LVL_NR_NUMBER__c,
												LCL_LDRSHP_TITL_LANG_DESC_TXT__c, 
												LCL_LDRSHP_TITL_CD__c, LANG_CD__c, GENRTN_3_MIN_ORD_AMT__c, 
												GENRTN_3_ERNGS_PCT__c, GENRTN_2_MIN_ORD_AMT__c, 
												GENRTN_2_ERNGS_PCT__c, GENRTN_1_MIN_ORD_AMT__c, 
												GENRTN_1_ERNGS_PCT__c, MIN_PRSNL_SLS_REQD_AMT__c,
												MIN_GRP_SLS_REQD_AMT__c, MIN_REP_RCRTMNTS_REQD_NR__c
												,EXEC_IND__c
										From 	Leader_Title__c
										where	Market__r.Id =: marketId
										and		LANG_CD__c=:languageKey
										ORDER BY LDRSHP_TITL_LVL_NR_NUMBER__c asc];
										
        LandingPageUtils.debugList(result, 'Leader Title in Market Utils');
		return result;
	}


    // List sorted by String title Badge
	public List<Leader_Title__c> initializeAndRetList(User currUser){
		ldrTitles = new Map<String,String>();
		List<Leader_Title__c> tempLdrList = new List<Leader_Title__c>();
		for(Leader_Title__c ldrTitle :[	Select	Market__c, MRKT_TAG_QLFR_3_NR__c, LDRSHP_TITL_LVL_NR__c, LDRSHP_TITL_LVL_NR_NUMBER__c,
												LCL_LDRSHP_TITL_LANG_DESC_TXT__c, 
												LCL_LDRSHP_TITL_CD__c, LANG_CD__c, GENRTN_3_MIN_ORD_AMT__c, 
												GENRTN_3_ERNGS_PCT__c, GENRTN_2_MIN_ORD_AMT__c, 
												GENRTN_2_ERNGS_PCT__c, GENRTN_1_MIN_ORD_AMT__c, 
												GENRTN_1_ERNGS_PCT__c
										From 	Leader_Title__c
										where	Market__r.Market_Id__c=:currUser.MRKT_ID__c
										and		LANG_CD__c=:currUser.LanguageLocaleKey
										order by LDRSHP_TITL_LVL_NR__c asc])
		{
			tempLdrList.add(ldrTitle);
			ldrTitles.put(ldrTitle.LDRSHP_TITL_LVL_NR__c,ldrTitle.LCL_LDRSHP_TITL_LANG_DESC_TXT__c);
		}
		return tempLdrList;
	}		

	public Leader_Title__c initializeAndRetTitle(User currUser,String lvlNbr){
		ldrTitles = new Map<String,String>();
		Leader_Title__c leaderTitl;
		for(Leader_Title__c ldrTitle :[	Select	Market__c, MRKT_TAG_QLFR_3_NR__c, LDRSHP_TITL_LVL_NR__c, LDRSHP_TITL_LVL_NR_NUMBER__c,
												LCL_LDRSHP_TITL_LANG_DESC_TXT__c, 
												LCL_LDRSHP_TITL_CD__c, LANG_CD__c, GENRTN_3_MIN_ORD_AMT__c, 
												GENRTN_3_ERNGS_PCT__c, GENRTN_2_MIN_ORD_AMT__c, 
												GENRTN_2_ERNGS_PCT__c, GENRTN_1_MIN_ORD_AMT__c, 
												GENRTN_1_ERNGS_PCT__c
										From 	Leader_Title__c
										where	Market__r.Market_Id__c=:currUser.MRKT_ID__c
										and		LANG_CD__c=:currUser.LanguageLocaleKey])
		{
			if(lvlNbr == ldrTitle.LDRSHP_TITL_LVL_NR__c){
				leaderTitl = ldrTitle;	
			}
			ldrTitles.put(ldrTitle.LDRSHP_TITL_LVL_NR__c,ldrTitle.LCL_LDRSHP_TITL_LANG_DESC_TXT__c);
		}
		return leaderTitl;
	}		

	public void initialize(User currUser,String titleLevel){
		ldrTitles = new Map<String,String>();
		for(Leader_Title__c ldrTitle :[	Select	Market__c, MRKT_TAG_QLFR_3_NR__c, LDRSHP_TITL_LVL_NR__c, LDRSHP_TITL_LVL_NR_NUMBER__c,
												LCL_LDRSHP_TITL_LANG_DESC_TXT__c, 
												LCL_LDRSHP_TITL_CD__c, LANG_CD__c, GENRTN_3_MIN_ORD_AMT__c, 
												GENRTN_3_ERNGS_PCT__c, GENRTN_2_MIN_ORD_AMT__c, 
												GENRTN_2_ERNGS_PCT__c, GENRTN_1_MIN_ORD_AMT__c, 
												GENRTN_1_ERNGS_PCT__c
										From 	Leader_Title__c
										where	Market__r.Market_Id__c=:currUser.MRKT_ID__c
										and		LANG_CD__c=:currUser.LanguageLocaleKey
										and		LDRSHP_TITL_LVL_NR__c = :titleLevel])
		{
			ldrTitles.put(ldrTitle.LDRSHP_TITL_LVL_NR__c,ldrTitle.LCL_LDRSHP_TITL_LANG_DESC_TXT__c);
		}
	}		
	
	public String getLeaderTitle(String titleLevelNbr){
		return this.ldrTitles.get(titleLevelNbr);
	}
	//subhamay 022012
	public Map<String,String> getLeaderTitle(){
		return this.ldrTitles;
	}
	//eoc subhamay 022012

    //@S-144891 : Commented by Blaine Rothrock on Nov 23
    /*public static testmethod void testLeaderTitles(){
		MarketLeaderTitleUtils ctlr = new MarketLeaderTitleUtils();
		TestDataHelper testData = new TestDataHelper();
		testData.createLeaderTitles();
		User testUsr = testData.createLeaderUser('123456');
		System.runAs(testUsr){
			ctlr.initialize(testUsr);
			System.assert(ctlr.getLeaderTitle('1')=='TL 1');
			List<Leader_Title__c> tempList = ctlr.initializeAndRetList(testUsr);
			system.debug('>><><><><><<'+tempList.size());
			System.assert(tempList.size()==8);
			
			ctlr.initialize(testUsr,'1');
			System.assert(ctlr.getLeaderTitle('1')=='Title 1');
			System.assert(ctlr.initializeAndRetTitle(testUsr,'1').LCL_LDRSHP_TITL_LANG_DESC_TXT__c=='Title 1');
			ctlr.initializeAndRetTitle(testUsr,'1');
			//TODO add System.assert
			ctlr.initializeAndRetList(testUsr);
			//TODO add System.assert
			ctlr.initializeAndRestListSortedByTitleNumber(testData.market.Id,testUsr.LanguageLocaleKey);
			//TODO add System.assert
			ctlr.initializeAndRetMapLT(testUsr);
			//TODO add System.assert
		}
    	
    }*/
	

}