youfull/objects/Leader_Title__c.object
<CustomObject>
    <fields>
        <fullName>LANG_CD__c</fullName>
        <label>Language</label>
        <picklist>
            <picklistValues>
                <fullName>en_US</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>fr</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ro</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>pl</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>hu</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ru</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>cs</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>es_MX</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>es</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>uk</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>sh</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>sk</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>en_MY</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>en_IN</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>bg</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>en_PH</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>en_GB</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>fr_CA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>en_CA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>en_AU</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>fi</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>pt_BR</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>sl</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ka</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>et</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>lv</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>lt</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>th</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>LCL_LDRSHP_TITL_LANG_DESC_TXT__c</fullName>
        <label>Title Description</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>LDRSHP_TITL_LVL_NR_NUMBER__c</fullName>
        <formula>VALUE( TEXT(LDRSHP_TITL_LVL_NR__c ))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Leader Title Level Num 2 Num</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>LDRSHP_TITL_LVL_NR__c</fullName>
        <label>Title Level Number</label>
        <picklist>
            <picklistValues>
                <fullName>UQ</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>-2</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>0</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>3</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>4</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>5</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>21</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>6</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>7</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>8</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>9</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>10</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>MRKT_ID__c</fullName>
        <label>Market Id</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Market__c</fullName>
        <label>Market</label>
        <referenceTo>Market__c</referenceTo>
        <relationshipLabel>Leader Titles</relationshipLabel>
        <relationshipName>Leader_Titles</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Leader Title</label>
    <nameField>
        <displayFormat>LDT-{000000}</displayFormat>
        <label>Leader Title Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Leader Titles</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

youfull/objects/Market__c.object
<CustomObject>
    <label>Market</label>
    <nameField>
        <label>Market Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Markets</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

youfull/classes/ReportFiltersController.cls
/***************************************************************************
 Name          : ReportFiltersController 
 Created By    : Parul Gupta
 Description   : Displays report filters as per passed filters 
 Created Date  : Jan 6, 2014               
****************************************************************************/
public with sharing class ReportFiltersController {
    
    public List<ReportFilter> filters {get;set;}    
    public List<SelectOption> titleList = new List<SelectOption>();
    public List<SelectOption> generationList = new List<SelectOption>();
    public Market__c market {get;set;}
    public String selectedReportOption {get;set;}
    public List<SelectOption> reportOptions {get;set;}
    
    //==============================================================================================//
    //Use cached data from Leader_Title__c to provide a list of SelectOptions for the different Leader Title levels
    //==============================================================================================//    
  	public List<SelectOption> getTitleList() {
        //Initialize the list of titles
        User currentUser = [SELECT Id, Profile.Name, MRKT_ID__c, ACCT_NR__c, DFALT_DIV_NM__c, DFALT_ZONE_CD__c, User.LanguageLocaleKey, UserRole.Name 
                from User WHERE Id = :UserInfo.getUserId() LIMIT 1];
        titleList.add(new SelectOption('0,1,2,3,4', 'All Paid Titles'));
        for(Leader_Title__c t : [Select t.Market__c, t.LANG_CD__c, t.LDRSHP_TITL_LVL_NR__c, t.LDRSHP_TITL_LVL_NR_NUMBER__c, LCL_LDRSHP_TITL_LANG_DESC_TXT__c
                          From Leader_Title__c t
                          where LANG_CD__c = :currentUser.LanguageLocaleKey
                          and Market__c = :this.market.Id
                          order by Market__c, LANG_CD__c, LDRSHP_TITL_LVL_NR_NUMBER__c]) {
          titleList.add(new SelectOption(t.LDRSHP_TITL_LVL_NR__c, t.LCL_LDRSHP_TITL_LANG_DESC_TXT__c));
         }
        return titleList;
    }  
    public List<SelectOption> getGenerationList(){
    	String sAllValue='';
    	for(Integer iCount=0;iCount<=9;iCount++){
    		sAllValue+=String.valueOf(iCount)+',';
    	}
    	sAllValue+='10';
    	generationList.add(new SelectOption(sAllValue,'All'));
      	for(Integer iCount=0;iCount<=10;iCount++){
      		generationList.add(new SelectOption(String.ValueOf(iCount),String.ValueOf(iCount)));
      	}   
      	return generationList;
    }  
         
}