youfull/objects/MailPlan_Order_Oppty__c.object
<CustomObject>
    <fields>
        <fullName>CMPGN_NR__c</fullName>
        <label>CMPGN_NR</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Market__c</fullName>
        <label>Market</label>
        <referenceTo>Market__c</referenceTo>
        <relationshipLabel>MailPlan_Order_Opptys</relationshipLabel>
        <relationshipName>MailPlan_Order_Opptys</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>MailPlan_Order_Oppty</label>
    <nameField>
        <displayFormat>MPLN-{000000}</displayFormat>
        <label>Mail Plan Order Oppty Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>MailPlan_Order_Opptys</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

youfull/objects/Market__c.object
<CustomObject>
    <fields>
        <fullName>CMPGN_NR__c</fullName>
        <label>CMPGN_NR</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Mail_Plan_Enabled__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Mail Plan Enabled</label>
        <type>Checkbox</type>
    </fields>
    <label>Market</label>
    <nameField>
        <label>Market Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Markets</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

youfull/objects/Sales_Org_Summary__c.object
<CustomObject>
    <fields>
        <fullName>ACTV_REP_FRCST_CNT__c</fullName>
        <label>Active Rep Forecast</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>FLD_SLS_CMPGN_NR__c</fullName>
        <label>Field Campaign Number</label>
        <length>6</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>LST_DT_RSPD__c</fullName>
        <label>Last Date Responded</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>MRKT_KEY__c</fullName>
        <label>Market</label>
        <referenceTo>Market__c</referenceTo>
        <relationshipLabel>Sales Org Summary</relationshipLabel>
        <relationshipName>Sales_Org_Summary</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>OPERTNL_CMPGN_NR__c</fullName>
        <label>Operational Campaign Number</label>
        <length>6</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SLS_ORG_DESC_TXT__c</fullName>
        <label>Area</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SLS_ORG_LVL_DESC_TXT__c</fullName>
        <label>Sales Org Type</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ZONE_MGR__c</fullName>
        <label>Zone Manager</label>
        <referenceTo>User</referenceTo>
        <relationshipLabel>Zone Summary</relationshipLabel>
        <relationshipName>Zone_Summary</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Sales Org Summary</label>
    <nameField>
        <label>Sales Org Summary Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sales Org Summaries</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

youfull/objects/ZM_MarketZoneKPIConfig__c.object
<CustomObject>
    <fields>
        <fullName>Context__c</fullName>
        <label>Context</label>
        <picklist>
            <picklistValues>
                <fullName>Compass</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>KPI Summary 1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>KPI Summary 2</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>KPI Summary 3</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Forecast Input</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Forecast Output</fullName>
            </picklistValues>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <fields>
        <fullName>MarketDefaultPlan__c</fullName>
        <label>MarketDefaultPlan</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>MarketUsesDefault__c</fullName>
        <defaultValue>false</defaultValue>
        <description>boolean, always true if no PlanField. If true, plan required</description>
        <label>MarketUsesDefault</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Market__c</fullName>
        <label>Market</label>
        <referenceTo>Market__c</referenceTo>
        <relationshipName>MarketZoneKPIConfigs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SortOrder__c</fullName>
        <label>SortOrder</label>
        <picklist>
            <picklistValues>
                <fullName>1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>3</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>4</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>5</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>6</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>7</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>8</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>9</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>10</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>11</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>12</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>13</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>14</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>15</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>16</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>17</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>18</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>19</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>20</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>21</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>22</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>23</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>24</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>25</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>26</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>27</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>28</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>29</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>30</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>ZM_ZoneKPIConfigName__c</fullName>
        <label>Zone KPI Configuration</label>
        <picklist>
            <picklistValues>
                <fullName>APPT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NET_SLS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ACTV_REP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>UPR</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>RMOVL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>RNSTMT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>LOA1_NET_SLS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MRKT_TAG_1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MRKT_TAG_2</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MRKT_TAG_3</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MRKT_TAG_4</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>TITL_0_STF</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>TITLD_STF</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>TITL_1_STF</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>TITL_2_STF</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>TITL_3_STF</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>TITL_4_STF</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>TITL_5_STF</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>TITL_6_STF</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>TITL_7_STF</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>TITL_8_STF</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>TITL_9_STF</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>TITL_10_STF</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>TITL_11_STF</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>TITL_12_STF</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>TITL_13_STF</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>TITL_14_STF</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>TITL_15_STF</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>TOP_SLR_LVL_1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>TOP_SLR_LVL_2</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Market Zone KPI Configuration</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Market Zone KPI Configs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

youfull/objects/ZM_ZoneKPIConfig__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <customSettingsVisibility>Public</customSettingsVisibility>
    <description>Configuration of specific KPI to be used in reports for zone manager</description>
    <fields>
        <fullName>CustomLabel__c</fullName>
        <label>CustomLabel</label>
        <length>50</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ForecastField__c</fullName>
        <label>ForecastField</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ForecastGoalField__c</fullName>
        <label>ForecastGoalField</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ForecastInput__c</fullName>
        <label>ForecastInput</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PlanField__c</fullName>
        <label>PlanField</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <label>ZM_ZoneKPIConfig</label>
</CustomObject>

youfull/classes/ZM_ForecastATInputController.cls
/*
** Apex Class/Controller Name           : ZM_ForecastATInputController
** VF Pages associated [Names]          : ZM_ActivityForecastTrackerInput
** 
** Is Extension                         : No
** Is Test Class                        : No
**
** Purpose [short summary]              : Controller for report ZM_ActivityForecastTrackerInput
** 
** Triggers Spawned                     : N/A
**
** Change Log (Put the latest entry on top) :
** ~Format: Date | Author | Change description 
**  3/11 Created G
**  3/19 modified G
** 
*/

public class ZM_ForecastATInputController {
    public Sales_Org_Summary__c inputRecord {get; set;}
    public Sales_Org_Summary__c blankInputRecord {get; set;}
    public List<String> inputFieldsCollection;
    public Map<String, ZM_ZoneKPIConfig__c> mapFields;
    public String activeZone {get; set;}
    public SelectOption[] zoneOptions {get; set;}
    public String campaignNum{get;set;}
    public String s_User_Language{get{return UserInfo.getLanguage();}}
    
    private String userId;
    private List<Sales_Org_Summary__c> listRecords;
    private Map<String, ZM_MarketZoneKPIConfig__c> mapMarketConfig;
    private Map<String, ZM_ZoneKPIConfig__c> mapKpi;
    private ZM_Utility_KPIConfig configUtil;
    private String marketId;
    private String context;
    private Map<String, Sales_Org_Summary__c> mapZones;
    public list<String> sortedFieldList{get;set;}
    public list<string> configFields{get;set;}
    private set<Integer> sortOrderSet = new set<Integer>();
    private list<Integer> sortOrderList = new list<Integer>();
    private map<Integer, String> sortOrderMap = new map<Integer, String>();
    
    
    public String strProfileName;



    public ZM_ForecastATInputController(){
        BuildandRunQuery();
    }
    
    
    /*
    * changes values on page according to active selected zone
    */
    public PageReference changeZone() {
    	system.debug ('activeZone = ' + activeZone);
        inputRecord = mapZones.get(activeZone);
        //Apexpages.addMessage(new Apexpages.Message(Apexpages.Severity.ERROR, 'inputRecord: '+inputRecord) );
        
        //Apexpages.addMessage(new Apexpages.Message(Apexpages.Severity.ERROR, 'mapFields: '+mapFields));
        
        blankInputRecord = new Sales_Org_Summary__c();
        return null;
    }
    
    public Decimal getZoneTotal()
    {
        Decimal zoneTotal = 0;
        for(ZM_ZoneKPIConfig__c s : mapFields.values())
        {
            zoneTotal += (Decimal)inputRecord.get((String)s.ForecastField__c)==null?0:(Decimal)inputRecord.get((String)s.ForecastField__c) ;
        }
        
        return zoneTotal;
                
    }
    
    /*
    * returns map of iterable labels as keys to fields' names
    * the output and input page iterates this map and displays
    * corresponding fields and labels
    */
    public Map<String, ZM_ZoneKPIConfig__c> getMapFields() {
        
        if (mapFields == null) {
            mapFields = configUtil.createMapFields(this.mapMarketConfig.values(), this.mapKpi);
        }
        sortOrderMap = new map<Integer, String>();
        
        for(ZM_MarketZoneKPIConfig__c mk : mapMarketConfig.values())
        {
            sortOrderMap.put(Integer.ValueOf(mk.SortOrder__c), mk.ZM_ZoneKPIConfigName__c);
        }
        
        sortOrderList = new list<Integer>();
        sortOrderList.addAll(sortOrderMap.keySet());
        sortOrderList.sort();
                
        sortedFieldList = new list<String>();
        configFields.clear();
        for(Integer i : sortOrderList)
        {
           sortedFieldList.add(sortOrderMap.get(i));
        }
        
        // Added by Raktim on 22nd Oct, 2013 - Defect 3228 Fix START        
        for(String field : sortedFieldList){
        	
        	for(ZM_ZoneKPIConfig__c z : mapFields.values()){
        		
        		if( field == z.Name){
        			
        			configFields.add(z.CustomLabel__c);
        			
        		}
        	}
        }
        
        /*
        for(ZM_ZoneKPIConfig__c z : mapFields.values())
        {
            for(String s : sortedFieldList)
            {
                if(s == z.Name)
                  configFields.Add(z.CustomLabel__c);
            }
        }*/
        System.debug('\n ############ GOT IT configFields FINAL @@@ \n'+configFields); 
        // Added by Raktim on 22nd Oct, 2013 - Defect 3228 Fix END
        
        return mapFields;
    }
    
    /*
        saves numbers for forecast input form
    */
    public PageReference submit() {
        if (listRecords.size() == 0 && !Test.isRunningTest()) { // !!! quick and dirty check
            Apexpages.addMessage(new Apexpages.Message(Apexpages.Severity.ERROR, 'No Sales Org Summary Records ') );
            return null;
    }
        
        try {
            
            //set the values in the inputRecord from blankInputRecord 
            Decimal sum=0;
            for(ZM_ZoneKPIConfig__c s : mapFields.values())
            {
                Decimal x = (Decimal)inputRecord.get((String)s.ForecastField__c)==null?0:(Decimal)inputRecord.get((String)s.ForecastField__c) ;
                Decimal y = (Decimal)blankInputRecord.get((String)s.ForecastField__c)==null?0:(Decimal)blankInputRecord.get((String)s.ForecastField__c);
                Decimal z = x+y;
                sum += y;
                Decimal d = (Decimal)inputRecord.get((String)s.PlanField__c);
                if(mapMarketConfig.containsKey(s.Name) && mapMarketConfig.get(s.Name).MarketUsesDefault__c)
                   d = mapMarketConfig.get(s.Name).MarketDefaultPlan__c;
                
                  
                //Apexpages.addMessage(new Apexpages.Message(Apexpages.Severity.INFO, s.ForecastField__c +'['+ x +'], ['+ y +'], ['+ z +'], ['+ d +']') );
                //Apexpages.addMessage(new Apexpages.Message(Apexpages.Severity.INFO, '['+ s.PlanField__c +'], ['+ s.ForecastGoalField__c +']') );
                //Apexpages.addMessage(new Apexpages.Message(Apexpages.Severity.INFO, '['+ inputRecord.Id +']') );
                try{
                    
                  if(s.ForecastField__c != null)
                    inputRecord.put((String)s.ForecastField__c, z );
                  
                  if(s.ForecastInput__c != null)
                    inputRecord.put((String)s.ForecastInput__c, d );
                  
                  if(d != null && d > 0 && s.ForecastGoalField__c != null) inputRecord.put( (String)s.ForecastGoalField__c, (z/d)*100 );
                                  
                  inputRecord.LST_DT_RSPD__c  = System.today();            
                  //apexPages.addMessage(new Apexpages.Message(Apexpages.Severity.ERROR, ':::::> ' + (Decimal)inputRecord.get((String)s.ForecastField__c) )) ;
                } 
                catch(Exception e) {
                    
                    Apexpages.addMessage(new Apexpages.Message(Apexpages.Severity.ERROR, Label.ZM_Forecast_Update_Error+'['+e.getMessage()+']') );
                }
                
                
            }
            if(sum == 0)
            {
                  Apexpages.addMessage(new Apexpages.Message(Apexpages.Severity.ERROR, Label.ZM_No_forecast_data_entered) );
                  return null;
            }
            update inputRecord;
            blankInputRecord = new Sales_Org_Summary__c();
            
        } catch(Exception e) {
            Apexpages.addMessage(new Apexpages.Message(Apexpages.Severity.ERROR, Label.ZM_Forecast_Update_Error+'[>'+e.getMessage()+'<]') );
        }
        return null;
    }
    
   /* public String buildSOQLWhereStatement(QueryBuilder builder ) {
    	 query += ' FROM Sales_Org_Summary__c  WHERE SLS_ORG_DESC_TXT__c = :zoneList and SLS_ORG_LVL_DESC_TXT__c = \'Z\' and  FLD_SLS_CMPGN_NR__c = :strCurrentCmpgnNR and MRKT_KEY__c = :marketId';//
       
    	return query;
    } */
    // New method - for Omniture Integration
    public String getOmniturePageName()      
    {  
        String pageNameOutput = 'ZM_ActivityForecastTrackerOutput';
        String pageNameInput = 'ZM_ActivityForecastTrackerInput';
        
        String pageName;
        
        String url = Apexpages.currentPage().getUrl();
        
        if(url.indexOf(pageNameInput) > -1)
            pageName = pageNameInput;
        else if(url.indexOf(pageNameOutput) > -1)
            pageName = pageNameOutput;        
        
        return ALMPlusUtils.generateOmniturePageName(pageName, null, strProfileName);
                 
    } //this is for getting page name mapping for omniture
    
    // utility exceptions
    class InvalidPermissionException extends Exception {
    }
    
    class NoRecordFoundException extends Exception {
    }
    
    class AmbiguityException extends Exception {
    }
 
 /*   
    @isTest(SeeAllData=true)
    static void testThisClass()
    {
        TestDataHelper testData =   new TestDataHelper();
        
        String acctNbr = '123456';
        
        // Creates Market Data
        Market__c mkt = testData.createMarket();
        User zmUsr;
        User thisUser = [ select Id from User where Id = :UserInfo.getUserId() ];
        
        System.runAs ( thisUser ) {
            zmUsr = testData.createUser(acctNbr, 'XZ1', 'Avon Mkt 62 Zone Manager');
            
            mkt.OwnerId = zmUsr.Id;
            mkt.Mail_Plan_Enabled__c = true;
            update  mkt;
            
            // Creates ZM MarketZoneKPIConfig data
            ZM_MarketZoneKPIConfig__c zmMrktZoneKPIConfg = new ZM_MarketZoneKPIConfig__c(ZM_ZoneKPIConfigName__c = 'ACTV_REP', SortOrder__c = '1',
                                                                                         Market__c = mkt.ID, Name = 'ConfigX', Context__c = 'Forecast Input',
                                                                                         OwnerId = zmUsr.Id, CurrencyISOCode='USD');
            insert zmMrktZoneKPIConfg;  
            
            // Creates Sales Org Summary data
            Sales_Org_Summary__c slsOrgSummry = new Sales_Org_Summary__c(Name = 'test', OPERTNL_CMPGN_NR__c = mkt.CMPGN_NR__c, ACTV_REP_FRCST_CNT__c = 10.0,
                                                                         ZONE_MGR__c = Userinfo.getUserId(), OwnerId = zmUsr.Id, FLD_SLS_CMPGN_NR__c = mkt.CMPGN_NR__c,
                                                                         CurrencyISOCode='USD', SLS_ORG_LVL_DESC_TXT__c = 'Z', MRKT_KEY__c = mkt.Id,
                                                                         SLS_ORG_DESC_TXT__c = 'XZ1'); 
            insert slsOrgSummry;                                                                                                                                             
            
        }
        
        // Creates MailPlan data
        MailPlan_Order_Oppty__c mlplnOrdOppty = testData.creatMailPlans(mkt, zmUsr.DFALT_ZONE_CD__c);
        
        PageReference p = Page.ZM_ActivityForecastTrackerInput;
        Test.setCurrentPage(p);
        
        System.runAs(zmUsr){
            
            ZM_ForecastATInputController ctl = new ZM_ForecastATInputController();
            
            ctl.getMapFields();
            ctl.getOmniturePageName();
            ctl.changeZone();
            ctl.submit();
            
        }
        
        
        
    }
    */
   
    
    private void BuildandRunQuery() {
   		  configFields = new list<string>();
        //get sales org summary records for this user
        //authentication part STARTS HERE
        blankInputRecord = new Sales_Org_Summary__c();
        Id IdUserProfile = UserInfo.getProfileId();
        ZM_UtilityClass objutilityclass= new ZM_UtilityClass();
        configUtil = new ZM_Utility_KPIConfig();
        objutilityclass.SetVariable();
        strProfileName = objutilityclass.strProfileName;
        campaignNum = objutilityclass.strCurrentCmpgnNR;
        
        //get market information
        //!!! hardcoded for test
        //marketId = 'a00F0000008AKlm';
        marketId = objutilityclass.strMarketRecordId;
        System.debug('====================== market id : ' + marketId);
        
        //get user Id
        userId = UserInfo.getUserId();//'005Z0000000ln3z';//
        //userId = 
        
        // !!! use constants
        if (!strProfileName.contains('Zone Manager') &&  
            !strProfileName.contains('Division Manager') && 
            !strProfileName.equals('Avon System Administrator') &&
            !Test.isRunningTest()) {
            
            throw new InvalidPermissionException();
        }
        //authentication part ENDS HERE
        
        //context depends on whether page is input or output
        String currentPage = ApexPages.currentPage().getUrl(); //check what current page is
        currentPage = currentPage.split('apex/')[1];
        if (!currentPage.contains('Forecast') && !Test.isRunningTest()) { // error
            throw new InvalidPermissionException();
        } else if (currentPage.contains('Input') && currentPage.contains('Output')) {
            throw new AmbiguityException();
        }
        
        if (currentPage.containsIgnoreCase('Input')) {// !!! constant
            context = 'Forecast Input';
        } else if (currentPage.containsIgnoreCase('Output')) {
            context = 'Forecast Output';
        }
        mapMarketConfig = configUtil.getKPIConfigForMarketAndContext(marketId, context); 
        
        
        
        mapKpi = ZM_ZoneKPIConfig__c.getAll();
        if (mapKpi.size() == 0) {
            throw new NoRecordFoundException();
        }
        
        //get field API names
        //use metadata to get all possible field names for ZM_ZoneKPIConfig__c
        Schema.DescribeSObjectResult r = ZM_ZoneKPIConfig__c.sObjectType.getDescribe();
        Map<String, Schema.SObjectField> mapZoneKpiFields = r.fields.getMap();
        Set<String> setKpiFieldNames = new Set<String>();
        String str = '';
        for (Schema.SObjectField sf: mapZoneKpiFields.values()) {
            str = sf.getDescribe().getName();
            if (str.contains('Field')) {
                setKpiFieldNames.add(str);
            }
        }
        
        
        getMapFields();
        String fieldsToGet = '';
        
        //knowing possible fields in zoneKpi and having all data from zoneKpi
        //only get data we need if field is not empty
        String val = '';
        
        string query = 'Select Id ';
        
        //get all sObjects
        map<String, Schema.SObjectType> m = Schema.getGlobalDescribe() ;
        
        //get the listof fields for the Sales_Org_Summary__c object
        Schema.SObjectType s = m.get('Sales_Org_Summary__c') ;
        Schema.DescribeSObjectResult sr = s.getDescribe() ;  
         
        // Get all the Sales_Org_Summary__c fields  
        Map<String, Schema.SObjectField> fields = sr.fields.getMap() ; 
         
        //iterate through the Sales_Org_Summary__c fields loading the field list with custon, non-required fields
        for(Schema.SObjectField f : fields.values())
        {
            //retrieve the field name
            string field = f.getDescribe().getName();
            if(!field.equalsIgnoreCase('Id'))
              query += ','+field;
            
        }
        list<String> zoneList = new list<String>();
        zoneOptions = objutilityclass.getZoneList();
        system.debug('zoneOptions = ' + zoneOptions);
       
        
        for(SelectOption o : zoneOptions)
           zoneList.add(o.getValue());
         
        string strCurrentCmpgnNR = objutilityclass.strCurrentCmpgnNR;
        
         system.debug ('MF ---- strCurrentCmpgnNR = ' + strCurrentCmpgnNR);
         system.debug ('MF---zoneList = ' + zoneList);
         system.debug('MF --- marketId = ' + marketId);
        
        //complete the query
        //query += ' FROM Sales_Org_Summary__c  WHERE SLS_ORG_DESC_TXT__c = :zoneList and SLS_ORG_LVL_DESC_TXT__c = \'Z\' and  OPERTNL_CMPGN_NR__c = :strCurrentCmpgnNR and MRKT_KEY__c = :marketId';//
        query += ' FROM Sales_Org_Summary__c  WHERE SLS_ORG_DESC_TXT__c = :zoneList and SLS_ORG_LVL_DESC_TXT__c = \'Z\' and  FLD_SLS_CMPGN_NR__c = :strCurrentCmpgnNR and MRKT_KEY__c = :marketId';//
        system.debug('MF---- query = ' + query);
        listRecords = Database.query(query);
        
        if (listRecords.size() < 0) { 
            throw new NoRecordFoundException();
        } 
        
        mapZones = new Map<String, Sales_Org_Summary__c>();
        
        
        
        //List<Sales_Org_Summary__c> lstZoneNrSOS= Database.query(query);
        //Apexpages.addMessage(new Apexpages.Message(Apexpages.Severity.INFO, 'zoneOptions.size()::::> '+zoneOptions.size() ));
        if(listRecords.size()>1 || Test.isRunningTest()){
            //zoneOptions= new List<SelectOption>();
            set<string> setSLSORGDESCTXT = new set<string>();
            for(Sales_Org_Summary__c listRecs : listRecords) {
                setSLSORGDESCTXT.add(listRecs.SLS_ORG_DESC_TXT__c);
                mapZones.put(listRecs.SLS_ORG_DESC_TXT__c, listRecs);
            }
            /*
            for(string strSet : setSLSORGDESCTXT) {
                zoneOptions.add(new SelectOption(strSet, strSet));
            }
            zoneOptions.sort();
            */
        
       }
       if(listRecords.size() > 0)
       {
        // the first record is default
        inputRecord = listRecords[0];
        activeZone = listRecords[0].SLS_ORG_DESC_TXT__c;
       }
        		  
   
    }
}