youfull/objects/MailPlan_Order_Oppty__c.object
<CustomObject>
    <fields>
        <fullName>CMPGN_NR__c</fullName>
        <label>CMPGN_NR</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Market__c</fullName>
        <label>Market</label>
        <referenceTo>Market__c</referenceTo>
        <relationshipLabel>MailPlan_Order_Opptys</relationshipLabel>
        <relationshipName>MailPlan_Order_Opptys</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>MailPlan_Order_Oppty</label>
    <nameField>
        <displayFormat>MPLN-{000000}</displayFormat>
        <label>Mail Plan Order Oppty Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>MailPlan_Order_Opptys</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

youfull/objects/Market__c.object
<CustomObject>
    <fields>
        <fullName>CMPGN_NR__c</fullName>
        <label>CMPGN_NR</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PREV_1_CMPGN_NR__c</fullName>
        <label>PREV_1_CMPGN_NR</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <label>Market</label>
    <nameField>
        <label>Market Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Markets</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

youfull/classes/modelPremiumZoneManager.cls
/*******************************************************************************
 Name          : modelPremiumZoneManager 
 Description   : Modelling PremiumZoneManager
 Created By    : Parul Gupta 
 Created Date  : 4 Feb, 2014               
*******************************************************************************/
public class modelPremiumZoneManager extends modelPerson{
	
	public Market__c market {get;set;} 
	
	//========================================================================//
  	// Method returns current campaign
  	//========================================================================//
	Public override String getCurrentCampaign(){
		return market.CMPGN_NR__c;
	}
	
	//========================================================================//
  	// Method returns previous campaign
  	//========================================================================//
	Public override String getPreviousCampaign(){
		return market.PREV_1_CMPGN_NR__c;
	}
	
	//========================================================================//
  	// Method returns mail plan
  	//========================================================================//
	Public override MailPlan_Order_Oppty__c getMailPlan(){
		MailPlan_Order_Oppty__c mailPlan;
		return mailPlan;
	}
}