youfull/objects/MailPlan_Order_Oppty__c.object
<CustomObject>
    <fields>
        <fullName>CMPGN_NR__c</fullName>
        <label>CMPGN_NR</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CURRNT_NEXT_CMPGN_PRFX_CD__c</fullName>
        <label>CURRNT_NEXT_CMPGN_PRFX_CD</label>
        <length>1</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>MRKT_ID__c</fullName>
        <label>MRKT_ID</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Market__c</fullName>
        <label>Market</label>
        <referenceTo>Market__c</referenceTo>
        <relationshipLabel>MailPlan_Order_Opptys</relationshipLabel>
        <relationshipName>MailPlan_Order_Opptys</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>MailPlan_Order_Oppty</label>
    <nameField>
        <displayFormat>MPLN-{000000}</displayFormat>
        <label>Mail Plan Order Oppty Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>MailPlan_Order_Opptys</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

youfull/objects/Market__c.object
<CustomObject>
    <fields>
        <fullName>Batch_Load_In_Process__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Flag to be set by CDW when starting the nightly batch and reset after its complete.</description>
        <inlineHelpText>Flag to be set by CDW when starting the nightly batch and reset after its complete.</inlineHelpText>
        <label>Batch Load In Process</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Batch_Load_Strt_Dt__c</fullName>
        <description>The date time when CDW started the batch process. This field is set by a workflow rule based on the flag value.</description>
        <label>Batch Load Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>CMPGN_NR__c</fullName>
        <label>CMPGN_NR</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Mail_Plan_Enabled__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Mail Plan Enabled</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>NEXT_1_CMPGN_NR__c</fullName>
        <label>NEXT_1_CMPGN_NR</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>NRT_Enabled__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Flag to determine, if this market is participating in NRT or not.</description>
        <label>NRT Enabled</label>
        <type>Checkbox</type>
    </fields>
    <label>Market</label>
    <nameField>
        <label>Market Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Markets</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

youfull/classes/Test_NRT_Utils.cls
/***************************************************************************
 Name          : Test_NRT_Utils 
 Created By    : Barkha Jain (JDC)
 Description   : Test class for NRT_Utils 
 Created Date  : Nov 16, 2013                
****************************************************************************/
@isTest
private class Test_NRT_Utils {
	static String mktIdKey = 'XX';
	
	//---------------------------------------------------------------------------
    // Method Name  : testNRTUtil
    // Description  : Method for Test Coverage for NRT_Utils
    //---------------------------------------------------------------------------
    static testMethod void testNRTUtil() {
    	// Create Leader User 
        User usr = TestDataHelper.createUser('1234', 'XZ1', 'Avon Leader', false);
     	usr.MRKT_ID__c = mktIdKey;
     	insert usr;
     	
        // Creating market data
    	Market__c mkt = TestDataHelper.createMarket(mktIdKey, false);
        mkt.Batch_Load_In_Process__c = true;
    	mkt.Batch_Load_Strt_Dt__c = System.now().addMinutes(-50);
        insert mkt;   
        
        Test.startTest();
        system.runAs(usr){
        	NRT_Utils.isBatchLoadInProcess();
        	NRT_Utils.getBatchLoadStarted();
        	system.assert(!NRT_Utils.isNrtEnabled());
        	NRT_Utils.getLastUpdatedTimeStamp(mktIdKey);
        	system.assertEquals(mkt.CMPGN_NR__c, NRT_Utils.getCurrentCampaign(mkt, usr));
        	system.assertEquals(mkt.NEXT_1_CMPGN_NR__c, NRT_Utils.getNextCampaign(mkt, usr));
        }	
        
    	mkt.Mail_Plan_Enabled__c = true;
    	mkt.NRT_Enabled__c = true;
    	update mkt;
    	
    	List<MailPlan_Order_Oppty__c> mailPlans = new List<MailPlan_Order_Oppty__c>();
    	MailPlan_Order_Oppty__c mp = TestDataHelper.createMPOrderOpp(mkt.Id, mkt.CMPGN_NR__c, 'N', System.today().addDays(1+10), 
											'M1', 'XZ1', 'M', false);
		mp.CURRNT_NEXT_CMPGN_PRFX_CD__c = 'C';
		mp.MRKT_ID__c = mktIdKey;
		mailPlans.add(mp);
		MailPlan_Order_Oppty__c mp1 = TestDataHelper.createMPOrderOpp(mkt.Id, mkt.NEXT_1_CMPGN_NR__c, 'N', System.today().addDays(1+10), 
											'M1', 'XZ1', 'M', false);
		mp1.CURRNT_NEXT_CMPGN_PRFX_CD__c = 'N';
		mp1.MRKT_ID__c = mktIdKey;
		mailPlans.add(mp1);
		insert mailPlans;
    	
    	system.runAs(usr){	
    		system.assert(NRT_Utils.isNrtEnabled());
    		NRT_Utils.getLastUpdatedTimeStamp(mktIdKey);
    		NRT_Utils.getLastUpdatedTimeStampBatch(mktIdKey);
 
    		system.assert(NRT_Utils.getCurrentCampaign(mkt, usr).contains(mailPlans[0].CMPGN_NR__c));
        	system.assert(NRT_Utils.getNextCampaign(mkt, usr).contains(mailPlans[1].CMPGN_NR__c));
        }
        Test.stopTest();        
    }
}