youfull/objects/MailPlan_Order_Oppty__c.object
<CustomObject>
    <fields>
        <fullName>CMPGN_NR__c</fullName>
        <label>CMPGN_NR</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>MRKT_ID__c</fullName>
        <label>MRKT_ID</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Market__c</fullName>
        <label>Market</label>
        <referenceTo>Market__c</referenceTo>
        <relationshipLabel>MailPlan_Order_Opptys</relationshipLabel>
        <relationshipName>MailPlan_Order_Opptys</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>SLS_ZONE_CD__c</fullName>
        <label>SLS_ZONE_CD</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <label>MailPlan_Order_Oppty</label>
    <nameField>
        <displayFormat>MPLN-{000000}</displayFormat>
        <label>Mail Plan Order Oppty Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>MailPlan_Order_Opptys</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

youfull/objects/Market__c.object
<CustomObject>
    <fields>
        <fullName>CMPGN_NR__c</fullName>
        <label>CMPGN_NR</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Mail_Plan_Enabled__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Mail Plan Enabled</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Market_Id__c</fullName>
        <externalId>true</externalId>
        <label>MRKT_ID</label>
        <length>15</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Market</label>
    <nameField>
        <label>Market Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Markets</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

youfull/objects/ZM_Report_Translation__c.object
<CustomObject>
    <fields>
        <fullName>MRKT_ID__c</fullName>
        <description>To relate to the Market Object</description>
        <label>Market</label>
        <referenceTo>Market__c</referenceTo>
        <relationshipLabel>ZM Report Market Translations</relationshipLabel>
        <relationshipName>ZM_Report_Market_Translations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Market_Id__c</fullName>
        <label>Market Id</label>
        <picklist>
            <picklistValues>
                <fullName>62</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>66</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>100</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>999</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>55</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>23</fullName>
            </picklistValues>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <label>ZM Report Market Translation</label>
    <nameField>
        <label>ZM Report Translation Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>ZM Report Market Translations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

youfull/classes/Test_ZM_HomepageQuicklinksCtl.cls
/***************************************************************************
 Name         : Test_ZM_HomepageQuicklinksCtl
 Created By   : Barkha Jain (JDC)
 Description  : Test class for ZM_HomepageQuicklinksCtl
 Created Date : Oct 28, 2013                
****************************************************************************/
@isTest(SeeAllData=true)
private class Test_ZM_HomepageQuicklinksCtl {
		static testMethod void testHomepageQuicklinks(){
			Date currDate = System.today().addDays(1);
		    String acctNbr = '123456';
		    
		    // Creates Market Data
		    Market__c mkt = TestDataHelper.createMarket('test market', '123456', false);
        	mkt.CMPGN_NR__c = '201304';
		    User zmUsr = TestDataHelper.createUser(acctNbr, 'XZ1', 'Avon Mkt 62 Zone Manager', true);
		    System.runAs ( zmUsr ) {
		        mkt.Mail_Plan_Enabled__c = true;
		        insert  mkt;
		    }
		    // Creates MailPlan data
		    MailPlan_Order_Oppty__c mlplnOrdOppty = TestDataHelper.createMPOrderOpp(mkt.Id, mkt.CMPGN_NR__c, 'N', currDate.addDays(1+10), null, null, null, false);
            mlplnOrdOppty.SLS_ZONE_CD__c = zmUsr.DFALT_ZONE_CD__c;
            mlplnOrdOppty.MRKT_ID__c = '123456';
            insert mlplnOrdOppty;
		    
		    // Creates ZM Report Market Translation data
		    Report r = [Select Name, Id from Report limit 1];
		    ZM_Report_Translation__c z = TestDataHelper.createReportTranslation(r.Name, r.Id, mkt.Market_Id__c, 1, 
	        									   zmUsr.LanguageLocaleKey, 'Quick Links', 'Zone', true);	
		    
		    System.runAs(zmUsr){
		        ZM_HomepageQuicklinksCtl ctlr = new ZM_HomepageQuicklinksCtl();
		        
		        ctlr.getDefaultCampaignId();
		        ctlr.getReportLinks();
		        ctlr.getDefaultZone(true);		        
		    }
		    
		    ZM_HomepageQuicklinksCtl.fixReportUrls('https://cs11.salesforce.com');
		    
		    System.runAs ( zmUsr ) {
		        mkt.Mail_Plan_Enabled__c = false;
		        update mkt;
		    }
		    
		    System.runAs(zmUsr){
		        ZM_HomepageQuicklinksCtl ctlr = new ZM_HomepageQuicklinksCtl();
		        ctlr.getDefaultCampaignId();
		    }
		}
}