youfull/objects/MailPlan_Order_Oppty__c.object
<CustomObject>
    <fields>
        <fullName>CMPGN_NR__c</fullName>
        <label>CMPGN_NR</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>MRKT_ID__c</fullName>
        <label>MRKT_ID</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Market__c</fullName>
        <label>Market</label>
        <referenceTo>Market__c</referenceTo>
        <relationshipLabel>MailPlan_Order_Opptys</relationshipLabel>
        <relationshipName>MailPlan_Order_Opptys</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>SLS_ZONE_CD__c</fullName>
        <label>SLS_ZONE_CD</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <label>MailPlan_Order_Oppty</label>
    <nameField>
        <displayFormat>MPLN-{000000}</displayFormat>
        <label>Mail Plan Order Oppty Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>MailPlan_Order_Opptys</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

youfull/objects/Market__c.object
<CustomObject>
    <fields>
        <fullName>CMPGN_NR__c</fullName>
        <label>CMPGN_NR</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Mail_Plan_Enabled__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Mail Plan Enabled</label>
        <type>Checkbox</type>
    </fields>
    <label>Market</label>
    <nameField>
        <label>Market Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Markets</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

youfull/objects/Sales_Org_Summary__c.object
<CustomObject>
    <label>Sales Org Summary</label>
    <nameField>
        <label>Sales Org Summary Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sales Org Summaries</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

youfull/objects/ZM_MarketZoneKPIConfig__c.object
<CustomObject>
    <fields>
        <fullName>Market__c</fullName>
        <label>Market</label>
        <referenceTo>Market__c</referenceTo>
        <relationshipName>MarketZoneKPIConfigs</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Market Zone KPI Configuration</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Market Zone KPI Configs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

youfull/classes/Test_ZM_ForecastATInputController.cls
/***************************************************************************
 Name         : Test_ZM_ForecastATInputController
 Created By   : Barkha Jain (JDC)
 Description  : Test class for ZM_ForecastATInputController
 Created Date : Oct 28, 2013                
****************************************************************************/
@isTest
private class Test_ZM_ForecastATInputController {
	
	//----------------------------------------------------------------------------
    // Method Name  : testForecastATInputCtrl
    // Description  : Method for Test Coverage of Class : ZM_ForecastATInputController
    //----------------------------------------------------------------------------
    static testMethod void testForecastATInputCtrl() {
        String marktId = 'DE';
        
        // creating test 'Zone Manager' user
        User zmUsr = TestDataHelper.createUser('1234', 'XZ1', 'Avon Mkt 62 Zone Manager', false);
        zmUsr.MRKT_ID__c = marktId;
		insert zmUsr;
		
        //Creating custom setting
        TestDataHelper.createZoneKPIConfig('ConfigX', 'test', null, true);
        
        // Creates Market Data
        Market__c mkt = TestDataHelper.createMarket('test market', marktId, false);
        mkt.CMPGN_NR__c = '201304';
        mkt.Mail_Plan_Enabled__c = true;
        
        System.runAs (zmUsr) {
        	insert mkt;
            
            // Creates ZM MarketZoneKPIConfig data
        	ZM_MarketZoneKPIConfig__c zmMrktZoneKPIConfg = TestDataHelper.createMarketZoneKPIConfig('ACTV_REP', 'ConfigX', mkt.ID, '1', 'Forecast Input', 'USD', false, 12, true);
        	
            // Creating Sales org Summary data
            Sales_Org_Summary__c sos = TestDataHelper.createSalesOrgSummary(mkt, zmUsr, true);
        }
        
        // Creates MailPlan data
	    MailPlan_Order_Oppty__c mlplnOrdOppty = TestDataHelper.createMPOrderOpp(mkt.Id, mkt.CMPGN_NR__c, 'N', System.today().addDays(1+10), null, null, null, false);
        mlplnOrdOppty.SLS_ZONE_CD__c = zmUsr.DFALT_ZONE_CD__c;
        insert mlplnOrdOppty;
        
        PageReference p = Page.ZM_ActivityForecastTrackerInput;
		Test.setCurrentPage(p);
		
		System.runAs(zmUsr){            
            ZM_ForecastATInputController ctl = new ZM_ForecastATInputController();            
            ctl.getMapFields();
			ctl.getOmniturePageName();
			ctl.changeZone();
			ctl.submit();            
        }
    }
}