youfull/objects/MailPlan_Order_Oppty__c.object
<CustomObject>
    <fields>
        <fullName>CMPGN_NR__c</fullName>
        <label>CMPGN_NR</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CURRNT_CMPGN_MAIL_RMN_DAY_CNT__c</fullName>
        <label># of Days to Close</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>CURRNT_CMPGN_ONLN_RMN_DAY_CNT__c</fullName>
        <label>CURRNT_CMPGN_ONLN_RMN_DAY_CNT</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>CURRNT_NEXT_CMPGN_PRFX_CD__c</fullName>
        <label>CURRNT_NEXT_CMPGN_PRFX_CD</label>
        <length>1</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>MLPLN_CD__c</fullName>
        <label>MLPLN_CD</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>MLPLN_CLOSD_IND__c</fullName>
        <label>MLPLN_CLOSD_IND</label>
        <length>1</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>MLPLN_END_DT__c</fullName>
        <label>MLPLN_END_DT</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>MRKT_ID__c</fullName>
        <label>MRKT_ID</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Market__c</fullName>
        <label>Market</label>
        <referenceTo>Market__c</referenceTo>
        <relationshipLabel>MailPlan_Order_Opptys</relationshipLabel>
        <relationshipName>MailPlan_Order_Opptys</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>NEXT_MLPLN_TO_CLOS_CD__c</fullName>
        <label>NEXT_MLPLN_TO_CLOS_CD</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SLS_ZONE_CD__c</fullName>
        <label>SLS_ZONE_CD</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <label>MailPlan_Order_Oppty</label>
    <nameField>
        <displayFormat>MPLN-{000000}</displayFormat>
        <label>Mail Plan Order Oppty Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>MailPlan_Order_Opptys</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

youfull/objects/Market__c.object
<CustomObject>
    <fields>
        <fullName>CMPGN_NR__c</fullName>
        <label>CMPGN_NR</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CURRNT_CMPGN_MAIL_RMN_DAY_CNT__c</fullName>
        <label>Remaining days to Mail Order</label>
        <precision>13</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>CURRNT_CMPGN_ONLN_RMN_DAY_CNT__c</fullName>
        <label>Remaining days to Online Order</label>
        <precision>13</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>PREV_1_CMPGN_NR__c</fullName>
        <label>PREV_1_CMPGN_NR</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <label>Market</label>
    <nameField>
        <label>Market Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Markets</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

youfull/classes/modelSalesLeader.cls
/*******************************************************************************
 Name          : modelSalesLeader 
 Description   : Modelling SalesLeader
 Created By    : Parul Gupta 
 Created Date  : 4 Feb, 2014               
*******************************************************************************/
public class modelSalesLeader extends modelPerson{
	
	public Market__c market {get;set;} 
	
	//========================================================================//
  	// Method returns current campaign
  	//========================================================================//
	Public override String getCurrentCampaign(){
		return market.CMPGN_NR__c;
	}
	
	//========================================================================//
  	// Method returns previous campaign
  	//========================================================================//
	Public override String getPreviousCampaign(){
		return market.PREV_1_CMPGN_NR__c;
	}
	
	//========================================================================//
  	// Method returns mail plan
  	//========================================================================//
	Public override MailPlan_Order_Oppty__c getMailPlan(){
		MailPlan_Order_Oppty__c mailPlan = [SELECT SLS_ZONE_CD__c, 
											NEXT_MLPLN_TO_CLOS_CD__c, MRKT_ID__c, 
                                            MLPLN_CD__c, CURRNT_NEXT_CMPGN_PRFX_CD__c, 
                                            CURRNT_CMPGN_ONLN_RMN_DAY_CNT__c, CURRNT_CMPGN_MAIL_RMN_DAY_CNT__c, 
                                            CMPGN_NR__c ,MLPLN_END_DT__c
                                            FROM MailPlan_Order_Oppty__c 
                                            WHERE Market__c = :market.Id
                                            AND MLPLN_END_DT__c >= today
                                            AND MLPLN_CLOSD_IND__c != 'Y'
                                            ORDER BY MLPLN_END_DT__c];
		return mailPlan;
	}
}