youfull/objects/Market__c.object
<CustomObject>
    <label>Market</label>
    <nameField>
        <label>Market Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Markets</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

youfull/objects/ZM_MarketZoneKPIConfig__c.object
<CustomObject>
    <fields>
        <fullName>Market__c</fullName>
        <label>Market</label>
        <referenceTo>Market__c</referenceTo>
        <relationshipName>MarketZoneKPIConfigs</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Market Zone KPI Configuration</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Market Zone KPI Configs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

youfull/objects/ZM_MarketZoneKPIContent__c.object
<CustomObject>
    <fields>
        <fullName>Language_Code__c</fullName>
        <label>Language Code</label>
        <picklist>
            <picklistValues>
                <fullName>ar</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>bg</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>bs</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>cs</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>cy</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>da</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>de</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>el</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>en_AU</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>en_CA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>en_GB</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>en_IN</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>en_MY</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>en_PH</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>en_US</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>es</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>es_MX</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>et</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>eu</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>fi</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>fr</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>fr_CA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ga</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>hi</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>hr</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>hu</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>hy</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>in</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>is</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>it</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>MarketZoneKPIConfig__c</fullName>
        <label>MarketZoneKPIConfig</label>
        <referenceTo>ZM_MarketZoneKPIConfig__c</referenceTo>
        <relationshipLabel>KPI Content</relationshipLabel>
        <relationshipName>KPIContent</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <label>KPI Content</label>
    <nameField>
        <label>Custom Object Label Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>KPI Content</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

youfull/objects/ZM_ZoneKPIConfig__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <customSettingsVisibility>Public</customSettingsVisibility>
    <description>Configuration of specific KPI to be used in reports for zone manager</description>
    <label>ZM_ZoneKPIConfig</label>
</CustomObject>

youfull/classes/Test_ZM_Utility_KPIConfig.cls
/***************************************************************************
 Name         : Test_ZM_Utility_KPIConfig
 Created By   : Barkha Jain (JDC)
 Description  : Test class for ZM_Utility_KPIConfig
 Created Date : Nov 7, 2013                
****************************************************************************/
@isTest 
private class Test_ZM_Utility_KPIConfig {
	
	//----------------------------------------------------------------------------
    // Method Name  : testKPIConfigUtility
    // Description  : Method for Test Coverage of Class : ZM_Utility_KPIConfig
    //----------------------------------------------------------------------------
    static testMethod void testKPIConfigUtility() {
        //creating test market records
        Market__c mkt = TestDataHelper.createMarket('DE', true);
    
    	//creating test ZM_ZoneKPIConfig__c records
        Map<String, ZM_ZoneKPIConfig__c> zoneConfigMap = new Map<String, ZM_ZoneKPIConfig__c>();
        zoneConfigMap.put('APPT0', TestDataHelper.createZoneKPIConfig('APPT0', 'Appointments', null, false));
        zoneConfigMap.put('APPT1', TestDataHelper.createZoneKPIConfig('APPT1', 'Appointments', 'APPT0', false));
        zoneConfigMap.put('APPT2', TestDataHelper.createZoneKPIConfig('APPT2', 'Appointments', 'APPT1', false));
        insert zoneConfigMap.values();
        
        //creating test ZM_MarketZoneKPIConfig__c records
        List<ZM_MarketZoneKPIConfig__c> marketConfigLst = new List<ZM_MarketZoneKPIConfig__c>();
        marketConfigLst.add(TestDataHelper.createMarketZoneKPIConfig('Config 1', 'APPT0', mkt.id, '1', 'KPI Summary 1;Compass', null, false, 12, false));
        marketConfigLst.add(TestDataHelper.createMarketZoneKPIConfig('Config 2', 'APPT1', mkt.id, '2', 'KPI Summary 1;Compass;', null, false, 12, false));
        marketConfigLst.add(TestDataHelper.createMarketZoneKPIConfig('Config 3', 'APPT2', mkt.id, '3', 'KPI Summary 1;Compass;TL;', null, false, 12, false)); 
        insert marketConfigLst;
        
        //creating ZM_MarketZoneKPIContent__c record
        ZM_MarketZoneKPIContent__c content = new ZM_MarketZoneKPIContent__c(MarketZoneKPIConfig__c = marketConfigLst[0].Id, 
        					Start_Date__c = Date.today().addDays(-1), Language_Code__c = Userinfo.getLanguage());
        insert content;
        
        Test.startTest();
        ZM_Utility_KPIConfig util = new ZM_Utility_KPIConfig();
        
        //test createMapInputFields method
        Map<String, String> fieldsMap = util.createMapInputFields(marketConfigLst, zoneConfigMap);
        //verify result
        system.assertEquals('APPT_CNT__c', fieldsMap.get('Appointments'));
        
        //test getKPIConfigForMarketAndContext method
        system.assertEquals(3, util.getKPIConfigForMarketAndContext(mkt.id, 'KPI Summary 1').size());
        
        //test getZoneKPIConfig method
        system.assertEquals(1, util.getZoneKPIConfig(mkt.id, 'TL').size());
        
        //test createMapFields method
        system.assert(util.createMapFields(marketConfigLst, zoneConfigMap).containsKey('Appointments'));
        
        //test getMarketZoneKPIContentMap method
        system.assertEquals(1, ZM_Utility_KPIConfig.getMarketZoneKPIContentMap().size());
        Test.stopTest();
    }
}