youfull/objects/Market__c.object
<CustomObject>
    <fields>
        <fullName>CMPGN_NR__c</fullName>
        <label>CMPGN_NR</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Mail_Plan_Enabled__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Mail Plan Enabled</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Market_Id__c</fullName>
        <externalId>true</externalId>
        <label>MRKT_ID</label>
        <length>15</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>NEXT_1_CMPGN_NR__c</fullName>
        <label>NEXT_1_CMPGN_NR</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PREV_1_CMPGN_NR__c</fullName>
        <label>PREV_1_CMPGN_NR</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <label>Market</label>
    <nameField>
        <label>Market Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Markets</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

youfull/objects/ZM_Report_Translation__c.object
<CustomObject>
    <fields>
        <fullName>Application_Context__c</fullName>
        <label>Application Context</label>
        <picklist>
            <picklistValues>
                <fullName>Quick Links</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Report Center</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>My Team Orders</fullName>
            </picklistValues>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <fields>
        <fullName>Language_Code__c</fullName>
        <label>Language Code</label>
        <picklist>
            <picklistValues>
                <fullName>en_PH</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>en_US</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ro</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>es</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>es_MX</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>en_GB</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>MRKT_ID__c</fullName>
        <description>To relate to the Market Object</description>
        <label>Market</label>
        <referenceTo>Market__c</referenceTo>
        <relationshipLabel>ZM Report Market Translations</relationshipLabel>
        <relationshipName>ZM_Report_Market_Translations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Market_Id__c</fullName>
        <label>Market Id</label>
        <picklist>
            <picklistValues>
                <fullName>62</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>66</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>100</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>999</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>55</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>23</fullName>
            </picklistValues>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <fields>
        <fullName>Report_Id__c</fullName>
        <label>Report Id</label>
        <length>18</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Report_Label__c</fullName>
        <label>Report Label</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Report_Role__c</fullName>
        <label>Report Role</label>
        <picklist>
            <picklistValues>
                <fullName>Zone</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Division</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Admin</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Training</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Standard Leader</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sales</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Report_URL__c</fullName>
        <label>Report URL</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Sort_Order__c</fullName>
        <label>Sort Order</label>
        <precision>3</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>ZM Report Market Translation</label>
    <nameField>
        <label>ZM Report Translation Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>ZM Report Market Translations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

youfull/classes/ZM_Report_RouterCtl.cls
public without sharing class ZM_Report_RouterCtl {
	
	User currentUser;
	public string getDefaultZone()
	{
		
    	String zones = '';
    	ZM_UtilityClass z = new ZM_UtilityClass();
    	z.SetVariable();
    	Integer cnt = 0;
    	for(SelectOption s : z.getZoneList())
    	{
    		if(cnt > 0)
    		   zones += ','+s.getValue();
    		else
    		  zones = s.getValue();
    		  
    		cnt ++;
    	}
	    return zones;
	}
  
  // Modified by Raktim on 28Jun 2013 - Mail Plan
	public pageReference routReport()
	{
		String DefaultCampaignId;
		currentUser = [Select Id, User.LanguageLocaleKey, DFALT_ZONE_CD__c, MRKT_ID__c, Profile.Name, Has_Seen_Legal_Message__c 
		                      from User 
		                     where Id = :UserInfo.getUserId()];
		                     
		// New field added for Mail Plan - raktim on 28Jun 2013                     
		for(Market__c	market : [SELECT Id, Market_Id__c, PREV_1_CMPGN_NR__c, CMPGN_NR__c, NEXT_1_CMPGN_NR__c, Mail_Plan_Enabled__c
	                                FROM Market__c 
	                                where Market_Id__c = :currentUser.MRKT_ID__c])
	    
	    //Modified by Raktim on 28Jun 2013 - Mail Plan                             
	    if( !market.Mail_Plan_Enabled__c )                            
			DefaultCampaignId = market.CMPGN_NR__c; 
		else{
			if(currentUser.Profile.Name.contains(ALMConstants.ZONE)){
				//DefaultCampaignId = MailPlanUtils.getMailPlanCampaignZMDM(currentUser.DFALT_ZONE_CD__c, market.Market_Id__c);
				ZM_UtilityClass z = new ZM_UtilityClass();
				String zones = z.getZones(market.id);
				try{
					DefaultCampaignId = MailPlanUtils.getMailPlanCampaignZMDM(zones, market.Market_Id__c);
				}catch(Exception e){
            		System.debug('\n Caught Exception in ZM_Report_Router for Mail Plan '+e.getMessage());
            		DefaultCampaignId = market.CMPGN_NR__c;
            	}
				
			}else if(currentUser.Profile.Name.contains(ALMConstants.DIVISION))
				DefaultCampaignId = market.CMPGN_NR__c; 
		}
    
		string reportName = ApexPages.currentPage().getParameters().get('reportname');
		System.debug('Report Name--'+reportname);
		reportName = reportName.replace('_',' ');	                   
		reportName = reportName.replace('+',' ');	  
		// ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR, reportName));
		//return null;               
		//reportName = reportName.replace('_',' ');	                   
		for(ZM_Report_Translation__c z : [Select z.Sort_Order__c
											   , z.Report_URL__c
											   , z.Report_Label__c
											   , z.Report_Id__c
											   , z.Market_Id__c
											   , z.Language_Code__c
											   , z.Id
											   , z.Application_Context__c 
											   , z.Report_Role__c
										    From ZM_Report_Translation__c z
										   where Language_Code__c = :currentUser.LanguageLocaleKey
										    and Market_Id__c includes(:currentUser.MRKT_ID__c)
										    //and Application_Context__c includes ('Quick Links')
										    and Name = :reportName])
		{
			if(currentUser.Profile.Name == null || currentUser.Profile.Name.containsIgnoreCase(z.Report_Role__c)) 
				return new PageReference(z.Report_URL__c+'?pv0='+DefaultCampaignId+'&pv1='+getDefaultZone());
		}
		
		return Page.ZM_ReportCenter;
	}
	
	// New Method - Omniture Addition
    public String getOmniturePageName()      
    {  
        return ALMPlusUtils.generateOmniturePageName('ZM_Report_Router', null, currentUser.Profile.Name);         
    } //this is for getting page name mapping for omniture
		
	@isTest(SeeAllData=true)
	static void testThisClass()
	{
		
	    Report r = [Select Name, Id from Report limit 1];
	    
	    
		ZM_Report_Translation__c z = new ZM_Report_Translation__c();
		z.Sort_Order__c = 1;
	    z.Report_URL__c = 'x';
	    z.Report_Label__c = r.Name.replace('_',' ').replace('+',' ');
	    z.Report_Id__c = r.Id;
	    z.Market_Id__c = '62';
	    z.Language_Code__c = 'en_US';
	    z.Application_Context__c = 'Quick Links';
	    z.Report_Role__c = 'System';
	    z.Name = r.Name.replace('_',' ').replace('+',' ');
	    
	    insert z;
		System.debug('zm report translation--'+z);
		User u = [Select Id, MRKT_ID__c,DFALT_DIV_NM__c from User where Id = :UserInfo.getUserId()];
		if(u.MRKT_ID__c == null) 
		{
			u.MRKT_ID__c = '62';
			u.LanguageLocaleKey = 'en_US';
		}
    	if(u.DFALT_DIV_NM__c == null) 
		{
			u.DFALT_DIV_NM__c = 'Metro Achievers';
		}
    	
		update u;
		PageReference pr = Page.ZM_Report_Router;
		pr.getParameters().put('reportname',z.Report_Label__c);
		Test.setCurrentPage(pr);
		ZM_Report_RouterCtl h = new ZM_Report_RouterCtl();
		h.routReport();
		
		pr.getParameters().put('reportname','testxtest');
		Test.setCurrentPage(pr);
		ZM_Report_RouterCtl h2 = new ZM_Report_RouterCtl();
		h2.routReport();
		
	}
	
	//@S-144891 : Commented by Blaine Rothrock on Nov 23
	/*@isTest(SeeAllData=true)
	static void testThisClassmp()
	{
		
	    Report r = [Select Name, Id from Report limit 1];
	    
		ZM_Report_Translation__c z = new ZM_Report_Translation__c();
		z.Sort_Order__c = 1;
	    z.Report_URL__c = 'x';
	    z.Report_Label__c = r.Name;
	    z.Report_Id__c = r.Id;
	    z.Market_Id__c = '62';
	    z.Language_Code__c = 'en_US';
	    z.Application_Context__c = 'Quick Links';
	    z.Report_Role__c = 'System';
	    z.Name = r.Name;
	    
	    insert z;

		User u = [Select Id, MRKT_ID__c,DFALT_DIV_NM__c from User where Id = :UserInfo.getUserId()];
		if(u.MRKT_ID__c == null) 
		{
			u.MRKT_ID__c = '62';
			u.LanguageLocaleKey = 'en_US';
		}
    	if(u.DFALT_DIV_NM__c == null) 
		{
			u.DFALT_DIV_NM__c = 'Metro Achievers';
		}
    	
    	TestDataHelper th=new TestDataHelper();
    	//create zone user
    	User runuser=th.createUser('1234','201','Avon Mkt 62 Zone Manager');
    	runuser.MRKT_ID__c='62';
    	update runuser;
    	
    	//create division user
    	User runuserdiv=th.createUser('12345','202','Avon Mkt 62 Division Manager');
    	runuserdiv.MRKT_ID__c='62';
    	update runuserdiv;
    	
    	Market__c testmarket=[select Id,Mail_Plan_Enabled__c from Market__c where Market_ID__c=:u.MRKT_ID__c];
        testmarket.Mail_Plan_Enabled__c=true;
        update testmarket;
		update u;
		System.RunAs(u){		
		PageReference pr = Page.ZM_Report_Router;
		pr.getParameters().put('reportname',z.Report_Label__c);
		Test.setCurrentPage(pr);
		ZM_Report_RouterCtl h = new ZM_Report_RouterCtl();
		h.routReport();
		
		pr.getParameters().put('reportname','testxtest');
		Test.setCurrentPage(pr);
		ZM_Report_RouterCtl h2 = new ZM_Report_RouterCtl();
		h2.routReport();
		}
		System.RunAs(runuser){
		PageReference pr = Page.ZM_Report_Router;
		pr.getParameters().put('reportname',z.Report_Label__c);
		Test.setCurrentPage(pr);
		ZM_Report_RouterCtl h = new ZM_Report_RouterCtl();
		h.routReport();	
		}
		
		System.RunAs(runuserdiv){
		PageReference pr = Page.ZM_Report_Router;
		pr.getParameters().put('reportname',z.Report_Label__c);
		Test.setCurrentPage(pr);
		ZM_Report_RouterCtl h = new ZM_Report_RouterCtl();
		h.routReport();
		h.getOmniturePageName();	
		}
		
	}*/
	
	

}