youfull/objects/Market__c.object
<CustomObject>
    <fields>
        <fullName>Market_Id__c</fullName>
        <externalId>true</externalId>
        <label>MRKT_ID</label>
        <length>15</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Market</label>
    <nameField>
        <label>Market Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Markets</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

youfull/objects/Report_Config__c.object
<CustomObject>
    <fields>
        <fullName>Applicable_to__c</fullName>
        <label>Applicable to</label>
        <picklist>
            <picklistValues>
                <fullName>Avon Leader</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Avon Division Manager</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Avon Zone Manager</fullName>
            </picklistValues>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <fields>
        <fullName>Is_Impersonation_Applicable__c</fullName>
        <defaultValue>true</defaultValue>
        <description>Check if the given report should be displayed in the Impersonation reports/pages list drop-down</description>
        <inlineHelpText>Check if the given report should be displayed in the Impersonation reports/pages list drop-down</inlineHelpText>
        <label>Is Impersonation Applicable?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Market__c</fullName>
        <label>Market</label>
        <referenceTo>Market__c</referenceTo>
        <relationshipName>Market_Drilldown_Configs</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Report_Id__c</fullName>
        <description>Unique Id for the drilldown</description>
        <externalId>true</externalId>
        <inlineHelpText>Unique Code that will be passed from the pages.</inlineHelpText>
        <label>Report Id</label>
        <length>7</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Report_Sequence__c</fullName>
        <label>Report Sequence</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Report_Type__c</fullName>
        <label>Report Type</label>
        <picklist>
            <picklistValues>
                <fullName>Inactive</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Inherited</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Orders_Not_Submitted</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Orders_on_Hold</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Orders_below_Minimum</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Orders_at_Minimum</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending_Orders</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Total_Orders_received</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Return_Orders</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Achieved_Minimum_Order</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Current_Balance_Past_Due_Status</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Personal_Sales_Qualifier</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Additions_Reinstatements</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Candidate_Development</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Development_LOA_1_6</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Downline_Detail</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PATD_Certified</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ranking_and_Recognition</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Title_Change</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Birthday_Anniversaries</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Balance_Past_Due</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Personal_Sales_Qual</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Returns</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Brochures_Not_Purchased</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>1st_Order_Award_Sales</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AI_Orders_Not_Submitted</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AI_Orders_on_Hold</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AI_Orders_below_Minimum</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AI_Orders_at_Minimum</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AI_Pending_Orders</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Report_URL__c</fullName>
        <label>Report URL</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>TITL_LVL_NBR__c</fullName>
        <description>Stores Title Level Numbers</description>
        <inlineHelpText>User can select multiple datas for this field in a single record</inlineHelpText>
        <label>Title Level Number</label>
        <picklist>
            <picklistValues>
                <fullName>0</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>3</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>4</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>5</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>6</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>7</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>-2</fullName>
            </picklistValues>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <label>Report Config</label>
    <nameField>
        <label>Report Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Report Configs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

youfull/classes/DropdownComponentController.cls
//udpated by SA 6/12/2012
public class DropdownComponentController  {
  public boolean impersonate {get;set;}
  public String userTitleNumber {get;set;}
  public String impersonatedAcctKey {get;set;}
  public String pgId {get;set;}
  public String marketId {get;set;}
  public String profileName {get;set;}
  public String currentReportType {get;set;}
  
    public List<SelectOption> getDropdownSelectOptions() {
      impersonatedAcctKey = ApexPages.currentPage().getParameters().get(ALMConstants.IMPERSON_PARAM_NAME);
      if(marketId == null) {
        return null;
      }
        List<SelectOption> listSelectOptions = getReportLinks(marketId, profileName, userTitleNumber, impersonate, impersonatedAcctKey, currentReportType);        
        return listSelectOptions;
    }
    
    //currentReportType - is report currently being viewed, i.e. item that should be excluded from the drop-down
    public List<SelectOption> getReportLinks(String marketId, String profileName, String userTitleNumber, Boolean impersonate, String impersonatedAcctKey, String currentReportType) {
    /*  System.debug('userTitleNumber: ' + userTitleNumber);
      System.debug('impersonatedAcctKey: ' + impersonatedAcctKey);
      System.debug('marketId: ' + marketId);
      System.debug('profileName: ' + profileName);
      System.debug('impersonate: ' + impersonate);
      System.debug('================= DropdownComponentController. impersonate: ' + impersonate);
      System.debug('================= DropdownComponentController. CurrentReportType: ' + currentReportType);*/
      impersonatedAcctKey = ApexPages.currentPage().getParameters().get(ALMConstants.IMPERSON_PARAM_NAME); //DO NOT remove this line
      pgId = ApexPages.currentPage().getParameters().get('pgId');
      
        List<SelectOption> listReports = new List<SelectOption>();
        
        // Change for defect id : 2400 - Raktim Sarkar - START 
       // listReports.add(new Selectoption('','Novalue'));
       // Change for defect id : 2400 - Raktim Sarkar - END
        //System.debug('\n.......   1 ');
        if( impersonate!=null && impersonate) {
          //System.debug('\n.......   1 impersonate ....... ');
          	if(pgId <> '1'){
            	listReports.add(new SelectOption('/apex/youhome?pgId=1&acctkey=' + impersonatedAcctKey, 'ALM_Home'));
          	}
            listReports.add(new SelectOption('javascript:viewRepDetail("'+impersonatedAcctKey+'");', 'Coaching_Record'));
        }
        //System.debug('\n.......   2  ....... ');
        //System.debug('\n getReportLinks impersonate '+impersonate);
        List<Report_Config__c> listReportConfigs = fetchReportLinks(marketId, profileName, userTitleNumber, impersonate);
        //System.debug('\n.......   3....... listReportConfigs size '+listReportConfigs.size()+' .. listReportConfigs \n '+listReportConfigs);
        if(listReportConfigs != null && listReportConfigs.size()>0) {
          //System.debug('\n.......   4 ');
            for(Report_Config__c rc : listReportConfigs) {
              //System.debug('\n.......   5 ....... ');
                //if(rc.Report_Type__c != currentReportType){
                    String reportURL = rc.Report_URL__c 
                                    + (rc.Report_URL__c !=null && rc.Report_URL__c.contains('?') ? '&' : '?')
                                    + (impersonate!=null && impersonate ? 'acctkey='+impersonatedAcctKey : '');
                   // System.debug('\n.......   6 ....... ');
                    // Change for defect id : 2400 - Raktim Sarkar - START     
                    if(currentReportType != null && !currentReportType.trim().equals('')){           
                      if(currentReportType.equals(ALMConstants.REPORT_TYPE_MYTEAM_REPORT)){   
                        if(rc.Report_Type__c != ALMConstants.REPORT_TYPE_MYTEAM_REPCONFIG)                 
                          listReports.add(new Selectoption(reportURL, rc.Report_Type__c));
                          
                    }else if(currentReportType.equals(ALMConstants.REPORT_TYPE_MYTEAM_ORDER)){  
                        if(rc.Report_Type__c != ALMConstants.REPORT_TYPE_MYTEAMORDER_REPCONFIG)                 
                          listReports.add(new Selectoption(reportURL, rc.Report_Type__c));
                          
                    }else if(currentReportType.equals(ALMConstants.REPORT_TYPE_G1SALESLEADERS)){  
                        if(rc.Report_Type__c != ALMConstants.REPORT_TYPE_G1SALESLEADERS)                 
                          listReports.add(new Selectoption(reportURL, rc.Report_Type__c));
                          
                    }else if(currentReportType.equals(ALMConstants.REPORT_TYPE_G1CANDIDATES)){  
                        if(rc.Report_Type__c != ALMConstants.REPORT_TYPE_G1CANDIDATES)                 
                          listReports.add(new Selectoption(reportURL, rc.Report_Type__c));
                          
                    }else if(currentReportType.equals(ALMConstants.REPORT_TYPE_RISINGSTARS)){  
                        if(rc.Report_Type__c != ALMConstants.REPORT_TYPE_RISINGSTARS)                 
                          listReports.add(new Selectoption(reportURL, rc.Report_Type__c));
                          
                    }else if(currentReportType.equals(ALMConstants.REPORT_TYPE_G1APPT)){  
                        if(rc.Report_Type__c != ALMConstants.REPORT_TYPE_G1APPT)                 
                          listReports.add(new Selectoption(reportURL, rc.Report_Type__c));
                          
                    }else if(currentReportType.equals(ALMConstants.REPORT_TYPE_TITLE_ADV_REPORT)){  
                      if(rc.Report_Type__c != ALMConstants.REPORT_TYPE_TITL_ADV_REPCONFIG)                 
                        listReports.add(new Selectoption(reportURL, rc.Report_Type__c));
                    }else if(currentReportType.equals(ALMConstants.REPORT_TYPE_SL_GENEALOGY)){  
                      if(rc.Report_Type__c != ALMConstants.REPORT_TYPE_SL_GENEALOGY)                 
                        listReports.add(new Selectoption(reportURL, rc.Report_Type__c));
                    }else if(currentReportType.equals(ALMConstants.REPORT_TYPE_EXEC_SL_GENEALOGY)){  // Added for My Exec Genealogy - Dropdown for Imprsn - Rajib 
                      if(rc.Report_Type__c != ALMConstants.REPORT_TYPE_EXEC_SL_GENEALOGY)                 
                        listReports.add(new Selectoption(reportURL, rc.Report_Type__c));
                    }
                    
                }else{
                  listReports.add(new Selectoption(reportURL, rc.Report_Type__c));
                }  
                    // Change for defect id : 2400 - Raktim Sarkar - END
                    
                //}
            }
        }
        //System.debug('\n.......   AFTER LOOP  ....... ');
        System.debug('listReports: ' + listReports);
        
        return listReports;
    }
    
    private List<Report_Config__c> fetchReportLinks(String mktId, String userProfileName, String userTitleNbr, Boolean isImpersonation){
        String query = 'Select r.TITL_LVL_NBR__c, r.Report_URL__c, r.Report_Type__c, r.Report_Id__c, r.Name, r.Report_Sequence__c,' + 
                       ' r.Market__r.Market_Id__c, r.Market__c, r.Id, r.Applicable_to__c From Report_Config__c r ';
                       
        String whereClause = ' where r.Market__r.Market_Id__c =: mktId AND Applicable_to__c INCLUDES (:userProfileName) AND TITL_LVL_NBR__c INCLUDES (:userTitleNbr) AND r.Report_Sequence__c>-1';//changed by swarnava for Team List
        if(isImpersonation)
            whereClause += ' AND Is_Impersonation_Applicable__c = true ';
        whereClause += ' order by r.Report_Sequence__c asc';
        query += whereClause;
        
        System.debug('\n query : ' + query);
        return (List<Report_Config__c>) Database.query(query);
    }
    
    
    
}