youfull/objects/Market__c.object
<CustomObject>
    <label>Market</label>
    <nameField>
        <label>Market Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Markets</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

youfull/objects/ZM_MarketZoneKPIConfig__c.object
<CustomObject>
    <fields>
        <fullName>Context__c</fullName>
        <label>Context</label>
        <picklist>
            <picklistValues>
                <fullName>Compass</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>KPI Summary 1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>KPI Summary 2</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>KPI Summary 3</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Forecast Input</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Forecast Output</fullName>
            </picklistValues>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <fields>
        <fullName>Goal_To_Maximize_Override__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Goal To Maximize Override</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>MarketDefaultPlan__c</fullName>
        <label>MarketDefaultPlan</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>MarketUsesDefault__c</fullName>
        <defaultValue>false</defaultValue>
        <description>boolean, always true if no PlanField. If true, plan required</description>
        <label>MarketUsesDefault</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Market__c</fullName>
        <label>Market</label>
        <referenceTo>Market__c</referenceTo>
        <relationshipName>MarketZoneKPIConfigs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SortOrder__c</fullName>
        <label>SortOrder</label>
        <picklist>
            <picklistValues>
                <fullName>1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>3</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>4</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>5</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>6</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>7</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>8</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>9</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>10</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>11</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>12</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>13</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>14</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>15</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>16</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>17</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>18</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>19</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>20</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>21</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>22</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>23</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>24</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>25</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>26</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>27</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>28</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>29</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>30</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>ZM_ZoneKPIConfigName__c</fullName>
        <label>Zone KPI Configuration</label>
        <picklist>
            <picklistValues>
                <fullName>APPT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NET_SLS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ACTV_REP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>UPR</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>RMOVL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>RNSTMT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>LOA1_NET_SLS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MRKT_TAG_1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MRKT_TAG_2</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MRKT_TAG_3</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MRKT_TAG_4</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>TITL_0_STF</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>TITLD_STF</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>TITL_1_STF</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>TITL_2_STF</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>TITL_3_STF</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>TITL_4_STF</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>TITL_5_STF</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>TITL_6_STF</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>TITL_7_STF</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>TITL_8_STF</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>TITL_9_STF</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>TITL_10_STF</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>TITL_11_STF</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>TITL_12_STF</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>TITL_13_STF</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>TITL_14_STF</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>TITL_15_STF</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>TOP_SLR_LVL_1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>TOP_SLR_LVL_2</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Market Zone KPI Configuration</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Market Zone KPI Configs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

youfull/objects/ZM_MarketZoneKPIContent__c.object
<CustomObject>
    <fields>
        <fullName>Language_Code__c</fullName>
        <label>Language Code</label>
        <picklist>
            <picklistValues>
                <fullName>ar</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>bg</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>bs</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>cs</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>cy</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>da</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>de</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>el</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>en_AU</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>en_CA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>en_GB</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>en_IN</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>en_MY</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>en_PH</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>en_US</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>es</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>es_MX</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>et</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>eu</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>fi</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>fr</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>fr_CA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ga</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>hi</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>hr</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>hu</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>hy</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>in</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>is</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>it</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>MarketZoneKPIConfig__c</fullName>
        <label>MarketZoneKPIConfig</label>
        <referenceTo>ZM_MarketZoneKPIConfig__c</referenceTo>
        <relationshipLabel>KPI Content</relationshipLabel>
        <relationshipName>KPIContent</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>SuggestedActivities__c</fullName>
        <label>SuggestedActivities</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <label>KPI Content</label>
    <nameField>
        <label>Custom Object Label Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>KPI Content</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

youfull/objects/ZM_ZoneKPIConfig__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <customSettingsVisibility>Public</customSettingsVisibility>
    <description>Configuration of specific KPI to be used in reports for zone manager</description>
    <fields>
        <fullName>ActualField__c</fullName>
        <label>ActualField</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CustomLabel__c</fullName>
        <label>CustomLabel</label>
        <length>50</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>ZM_ZoneKPIConfig</label>
</CustomObject>

youfull/classes/ZM_Utility_KPIConfig.cls
//
//  Name            : ZM_Utility_KPIConfig
//  Description     : Controller 
//  Author          : V. Mittal
//  Created Date    : Feb, 2013
//  

public without sharing class ZM_Utility_KPIConfig {

    public Map<String,ZM_MarketZoneKPIConfig__c> getKPIConfigForMarketAndContext(String MarketId,string ContextName ){
    	
        Map<String,ZM_MarketZoneKPIConfig__c> MapKPIConfig=New Map<String, ZM_MarketZoneKPIConfig__c>();
        
        List<ZM_MarketZoneKPIConfig__c> lstMarketZone=[Select ZM_ZoneKPIConfigName__c, SortOrder__c, OwnerId, Name, Market__c,
        														 MarketUsesDefault__c, MarketDefaultPlan__c, Id, Context__c,
        														 Goal_To_Maximize_Override__c  
											           From ZM_MarketZoneKPIConfig__c  
											           WHERE Market__c= :MarketId AND Context__c includes (:ContextName)
											           order by SortOrder__c];
											           
        for(ZM_MarketZoneKPIConfig__c objMarketZoneKPIConfig: lstMarketZone){
            MapKPIConfig.put(objMarketZoneKPIConfig.ZM_ZoneKPIConfigName__c,objMarketZoneKPIConfig);
        }
        
        system.debug('ZM_Utility_KPIConfig.getKPIConfigForMarketAndContext returned map => ' + MapKPIConfig);
        return MapKPIConfig;
    }
    
    
	/*
	* creates collection of iterable input fields
	* the input page iterates this collection and displays
	* corresponding input Actual fields
	*/
	public Map<String, String> createMapInputFields(List<ZM_MarketZoneKPIConfig__c> listMConfig, Map<String, ZM_ZoneKPIConfig__c> mapZConfig) {
		Map<String, String> result = new Map<String, String>();
		ZM_ZoneKPIConfig__c zConfig = null;
		
		if (listMConfig == null || listMConfig.size() == 0 || mapZConfig == null || mapZConfig.size() == 0) {
			return null;
		}
		
		for (ZM_MarketZoneKPIConfig__c mConfig : listMConfig) {
			zConfig = mapZConfig.get(mConfig.ZM_ZoneKPIConfigName__c);
			result.put(zConfig.CustomLabel__c, zConfig.ActualField__c);
		}
		
		return result;
	}
	
	/*
	* creates collection of iterable KPIs with fields
	* the input and output pages iterate through this collection and display
	* corresponding fields
	*/
	public Map<String, ZM_ZoneKPIConfig__c> createMapFields(List<ZM_MarketZoneKPIConfig__c> listMConfig, Map<String, ZM_ZoneKPIConfig__c> mapZConfig) {
		ZM_ZoneKPIConfig__c zConfig = null;
		Map<String, ZM_ZoneKPIConfig__c> result = new Map<String, ZM_ZoneKPIConfig__c>();
		
		if (listMConfig == null || listMConfig.size() == 0 || mapZConfig == null || mapZConfig.size() == 0) {
			return null;
		}
		
		// Added by Raktim on 22nd Oct, 2013 - Defect 3228 Fix
		listMConfig.sort();		
		// EoC
		
		list<String> fieldSort = new list<String>();
		for (ZM_MarketZoneKPIConfig__c mConfig : listMConfig) {
			zConfig = mapZConfig.get(mConfig.ZM_ZoneKPIConfigName__c);
			result.put(zConfig.CustomLabel__c, zConfig);
			
		}
		
		return result;
	}
	
	/*
	* method will return all the custom setting (ZM_ZoneKPIConfig__c) data/rows for a given CONFIG_NAME
	* logic used to get the required data is:
	*   1. Fetch the ZM_MarketZoneKPIConfig__c records with the given contectId and markert Id
	*   2. Use the data from above point, to get the related custom setting data with same CONFIG_NAME
	*/
    public List<ZM_ZoneKPIConfig__c> getZoneKPIConfig(string MarketId,string ContextName){

    	string strQuery='Select ZM_ZoneKPIConfigName__c, SortOrder__c, OwnerId, Name, Market__c, MarketUsesDefault__c, MarketDefaultPlan__c,Id,Context__c From ZM_MarketZoneKPIConfig__c where Context__c includes (\'' +ContextName+ '\') and Market__c=\''+MarketId +'\'order by SortOrder__c';
    	system.debug('strQuery:'+strQuery);

    	List<ZM_MarketZoneKPIConfig__c> lstMarketZone=Database.query(strQuery);
    	system.debug('lstMarketZone:'+lstMarketZone);
    	
    	Map<String,ZM_ZoneKPIConfig__c> Map_CustomValueRecords = ZM_ZoneKPIConfig__c.getAll();
    	system.debug('Map_CustomValueRecords:'+Map_CustomValueRecords);
    	
    	List<ZM_ZoneKPIConfig__c> result= new List<ZM_ZoneKPIConfig__c>();
    	
    	for(ZM_MarketZoneKPIConfig__c objZMMZKPIC: lstMarketZone){
    			system.debug('objZMMZKPIC.ZM_ZoneKPIConfigName__c:'+objZMMZKPIC.ZM_ZoneKPIConfigName__c);
    			if(Map_CustomValueRecords.get(objZMMZKPIC.ZM_ZoneKPIConfigName__c)!=null){
    				result.add(Map_CustomValueRecords.get(objZMMZKPIC.ZM_ZoneKPIConfigName__c) );
    			}	
    	}
    	return result;
    	
    } 
    
    /* 
    * Method to get all the MarketZoneKPIContent records related to MarketZoneKPIConfig which is stated just before today
    * and where Language Code matches the one of logged-in user's language code.
    */
    public static Map<String,ZM_MarketZoneKPIContent__c> getMarketZoneKPIContentMap() {
    	
    	// Create a Map of marketZonConfigName as Key and MarketZoneKPIContent record as its value
    	Map<String,ZM_MarketZoneKPIContent__c> mapMarketZoneKPIContent = new Map<String,ZM_MarketZoneKPIContent__c>();
    	
    	for(ZM_MarketZoneKPIContent__c mzkc : [select Id, MarketZoneKPIConfig__c, MarketZoneKPIConfig__r.ZM_ZoneKPIConfigName__c, SuggestedActivities__c
    							from ZM_MarketZoneKPIContent__c where Start_Date__c < today and Language_Code__c =: Userinfo.getLanguage() 
    							order by Start_Date__c ASC ]) {
    								
    		mapMarketZoneKPIContent.put(mzkc.MarketZoneKPIConfig__r.ZM_ZoneKPIConfigName__c, mzkc);
    	}
    	
    	// return the above created map
    	return mapMarketZoneKPIContent;
    }
}