youfull/objects/Market__c.object
<CustomObject>
    <fields>
        <fullName>CMPGN_NR__c</fullName>
        <label>CMPGN_NR</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Hide_Next_Campaign__c</fullName>
        <defaultValue>false</defaultValue>
        <description>When checked, Next Campaign data will be hidden from  KPI Summary 1 table on &quot;KPIs at a Glance&quot; tab.</description>
        <label>Hide Next Campaign?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>NEXT_1_CMPGN_NR__c</fullName>
        <label>NEXT_1_CMPGN_NR</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PREV_1_CMPGN_NR__c</fullName>
        <label>PREV_1_CMPGN_NR</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <label>Market</label>
    <nameField>
        <label>Market Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Markets</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

youfull/objects/Sales_Org_Summary__c.object
<CustomObject>
    <fields>
        <fullName>ACTV_REP_CNT__c</fullName>
        <label>Act. Reps Invoiced</label>
        <precision>13</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>ACTV_REP_DIV_RNK__c</fullName>
        <label>Act. Reps Division Rank</label>
        <precision>13</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>ACTV_REP_PLAN_CNT__c</fullName>
        <label>Act. Reps Plan</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>ACTV_REP_PLAN_SPPY_CNT__c</fullName>
        <label>Act. Reps SPPY Plan</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>ACTV_REP_SPPY_CNT__c</fullName>
        <label>Act. Reps PY</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>APPT_CNT__c</fullName>
        <label>Appointments Actual</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>APPT_DIV_RNK__c</fullName>
        <label>Appointments Division Rank</label>
        <precision>13</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>APPT_PLAN_CNT__c</fullName>
        <label>Appointments Plan</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>APPT_PLAN_SPPY_CNT__c</fullName>
        <label>Appointments SPPY Plan</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>APPT_SPPY_CNT__c</fullName>
        <label>Appointments SPPY Actual</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Analysis_Done__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Analysis Done</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>FLD_SLS_CMPGN_NR__c</fullName>
        <label>Field Campaign Number</label>
        <length>6</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>LOA1_NET_SLS_AMT__c</fullName>
        <label>LOA1 Sales Actual</label>
        <precision>13</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>LOA1_NET_SLS_DIV_RNK__c</fullName>
        <label>LOA1 Sales Division Rank</label>
        <precision>13</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>LOA1_NET_SLS_PLAN_AMT__c</fullName>
        <label>LOA1 Sales Plan</label>
        <precision>13</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>LOA1_NET_SLS_PLAN_SPPY_AMT__c</fullName>
        <label>LOA1 Sales SPPY Plan</label>
        <precision>13</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>LOA1_NET_SLS_SPPY_AMT__c</fullName>
        <label>LOA1 Sales SPPY Actual</label>
        <precision>13</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>LOA_1_6_NET_SLS_AMT__c</fullName>
        <label>LOA1-6 Sales Actual</label>
        <precision>13</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>LOA_1_6_NET_SLS_DIV_RNK__c</fullName>
        <label>LOA1-6 Sales Division Rank</label>
        <precision>13</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>LOA_1_6_NET_SLS_PLAN_AMT__c</fullName>
        <label>LOA1-6 Sales Plan</label>
        <precision>13</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>LOA_1_6_NET_SLS_PLAN_SPPY_AMT__c</fullName>
        <label>LOA1-6 Sales SPPY Plan</label>
        <precision>13</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>LOA_1_6_NET_SLS_SPPY_AMT__c</fullName>
        <label>LOA1-6 sales sppy Actual</label>
        <precision>13</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>NET_SLS_DIV_RNK__c</fullName>
        <label>Net sales division rank</label>
        <precision>13</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>NET_SLS_PLAN_AMT__c</fullName>
        <label>Net Sales Plan</label>
        <precision>15</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>NET_SLS_PLAN_SPPY_AMT__c</fullName>
        <label>Net sales sppy plan</label>
        <precision>15</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>NET_SLS_SPPY_AMT__c</fullName>
        <label>Net Sales PY</label>
        <precision>15</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>OPERTNL_CMPGN_NR__c</fullName>
        <label>Operational Campaign Number</label>
        <length>6</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>RMOVL_CNT__c</fullName>
        <label>Removals Actuals</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>RMOVL_DIV_RNK__c</fullName>
        <label>removals division rank</label>
        <precision>13</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>RMOVL_PLAN_CNT__c</fullName>
        <label>removals plan</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>RMOVL_PLAN_SPPY_CNT__c</fullName>
        <label>removals sppy plan</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>RMOVL_SPPY_CNT__c</fullName>
        <label>removals sppy actual</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>RNSTMT_CNT__c</fullName>
        <label>Actual Reinstatements</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>RNSTMT_DIV_RNK__c</fullName>
        <label>reinstatements division rank</label>
        <precision>13</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>RNSTMT_PLAN_CNT__c</fullName>
        <label>Reinstatements Plan</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>RNSTMT_PLAN_SPPY_CNT__c</fullName>
        <label>reinstatements sppy plan</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>RNSTMT_SPPY_CNT__c</fullName>
        <label>reinstatements sppy actual</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>RTURN_NET_SLS_AMT__c</fullName>
        <label>Actual Returns</label>
        <precision>13</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>RTURN_NET_SLS_DIV_RNK__c</fullName>
        <label>returned sales division rank</label>
        <precision>13</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>RTURN_NET_SLS_PLAN_AMT__c</fullName>
        <label>returned sales plan</label>
        <precision>13</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>RTURN_NET_SLS_PLAN_SPPY_AMT__c</fullName>
        <label>returned sales sppy plan</label>
        <precision>13</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>RTURN_NET_SLS_SPPY_AMT__c</fullName>
        <label>returned sales sppy actual</label>
        <precision>13</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>SLS_ORG_DESC_TXT__c</fullName>
        <label>Area</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>TITLD_STF_CNT__c</fullName>
        <label>count of Unit leader and above actual</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>TITLD_STF_DIV_RNK__c</fullName>
        <label>count of Unit leader and above DR</label>
        <precision>13</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>TITLD_STF_PLAN_CNT__c</fullName>
        <label>count of Unit leader and above plan</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>TITLD_STF_PLAN_SPPY_CNT__c</fullName>
        <label>count of Unit leader and above sppy plan</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>TITLD_STF_SPPY_CNT__c</fullName>
        <label>count of Unit leader sppy actual</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>TITL_0_STF_CNT__c</fullName>
        <label>candidates - count</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>TITL_0_STF_DIV_RNK__c</fullName>
        <label>candidates - division rank</label>
        <precision>13</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>TITL_0_STF_PLAN_CNT__c</fullName>
        <label># of Candidates Plan</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>TITL_0_STF_PLAN_SPPY_CNT__c</fullName>
        <label>candidates - sppy plan</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>TITL_0_STF_SPPY_CNT__c</fullName>
        <label>candidates - sppy actual</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>UPR_CNT__c</fullName>
        <label>Actual UPR</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>UPR_DIV_RNK_CNT__c</fullName>
        <label>UPR division rank</label>
        <precision>13</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>UPR_PLAN_CNT__c</fullName>
        <label>UPR (unit per rep) plan</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>UPR_PLAN_SPPY_CNT__c</fullName>
        <label>UPR (unit per rep) sppy plan</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>UPR_SPPY_CNT__c</fullName>
        <label>UPR (unit per rep) sppy actual</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>ZONE_MGR__c</fullName>
        <label>Zone Manager</label>
        <referenceTo>User</referenceTo>
        <relationshipLabel>Zone Summary</relationshipLabel>
        <relationshipName>Zone_Summary</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Sales Org Summary</label>
    <nameField>
        <label>Sales Org Summary Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sales Org Summaries</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

youfull/objects/ZM_MarketZoneKPIConfig__c.object
<CustomObject>
    <fields>
        <fullName>Market__c</fullName>
        <label>Market</label>
        <referenceTo>Market__c</referenceTo>
        <relationshipName>MarketZoneKPIConfigs</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Market Zone KPI Configuration</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Market Zone KPI Configs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

youfull/objects/ZM_ZoneKPIConfig__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <customSettingsVisibility>Public</customSettingsVisibility>
    <description>Configuration of specific KPI to be used in reports for zone manager</description>
    <fields>
        <fullName>CountAtRiskField__c</fullName>
        <label>CountAtRiskField</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CountOfRisingStarsField__c</fullName>
        <label>CountOfRisingStarsField</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Goal_To_Maximize__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Goal To Maximize</label>
        <type>Checkbox</type>
    </fields>
    <label>ZM_ZoneKPIConfig</label>
</CustomObject>

youfull/classes/Test_ZM_SalesOrgSummaryController.cls
/***************************************************************************
 Name         : Test_ZM_SalesOrgSummaryController
 Created By   : Barkha Jain (JDC)
 Description  : Test class for ZM_SalesOrgSummaryController
 Created Date : Oct 28, 2013                
****************************************************************************/
@isTest
private class Test_ZM_SalesOrgSummaryController {
     
     //----------------------------------------------------------------------------
     // Method Name  : testSalesOrgSummaryController
     // Description  : Method for Test Coverage of Class : ZM_SalesOrgSummaryController
     //----------------------------------------------------------------------------
     static testMethod void testSalesOrgSummaryController() {
     	
     	// Create test data
        User u1 = TestDataHelper.createUser('62', '601', 'Avon Mkt 62 Zone Manager', true);        
        Market__c mark = TestDataHelper.createMarket('62', false);
        mark.CMPGN_NR__c = '201302';
        mark.PREV_1_CMPGN_NR__c = '201301';
        mark.NEXT_1_CMPGN_NR__c = '201303';
        mark.Hide_Next_Campaign__c = true;
        insert mark;   
        
        // Create Congig records
        List<ZM_MarketZoneKPIConfig__c> marketZoneKPIConfigs = new List<ZM_MarketZoneKPIConfig__c>(); 
        ZM_MarketZoneKPIConfig__c ZMMarketConfig = TestDataHelper.createMarketZoneKPIConfig('Config 1', 'APPT', mark.Id, '1', 'KPI Summary 1;Compass', 'USD', true, 1, false);
        marketZoneKPIConfigs.add(ZMMarketConfig);
        ZMMarketConfig = TestDataHelper.createMarketZoneKPIConfig('Config 2', 'RMOVL', mark.Id, '2', 'KPI Summary 1;Compass', 'USD', true, 1, false);
        marketZoneKPIConfigs.add(ZMMarketConfig);
        insert marketZoneKPIConfigs;
        
        List<ZM_ZoneKPIConfig__c> zoneKPIConfigs = new List<ZM_ZoneKPIConfig__c>();
        ZM_ZoneKPIConfig__c ZMZoneKPIConfig = TestDataHelper.createZoneKPIConfig('APPT', 'Appointments', null, false);
        ZMZoneKPIConfig.CountOfRisingStarsField__c = 'APPT_RSNG_STR_CNT__c';
		ZMZoneKPIConfig.CountAtRiskField__c = 'APPT_TAR_CNT__c';
		ZMZoneKPIConfig.Goal_To_maximize__c = true;
		zoneKPIConfigs.add(ZMZoneKPIConfig);
		ZMZoneKPIConfig = TestDataHelper.createZoneKPIConfig('RMOVL', 'Appointments', null, false);
        ZMZoneKPIConfig.CountOfRisingStarsField__c = 'RMOVL_RSNG_STR_CNT__c';
		ZMZoneKPIConfig.Goal_To_maximize__c = false;
		zoneKPIConfigs.add(ZMZoneKPIConfig);
		insert zoneKPIConfigs;
      	
      	// Create Sales_Org_Summary__c records
        List<Sales_Org_Summary__c> salesOrg = new list<Sales_Org_Summary__c>();
        salesOrg.add(createSalesOrgSummary(u1.id, u1.id,
    									'601', '201303', false));
        salesOrg.add(createSalesOrgSummary(u1.id, u1.id,
    									'601', '201302', false));      
        salesOrg.add(createSalesOrgSummary(u1.id, u1.id,
    									'601', '201301', false));
        insert salesOrg;
        
        Test.StartTest();       
        System.runAs(u1) {
        	PageReference pg = new PageReference('/apex/ZM_BusinessPlan');
            Test.setCurrentPageReference(pg);
            ApexPages.currentPage().getParameters().put('SLSORGDESCTXT', '601');
        	ApexPages.StandardController objController = new ApexPages.StandardController(salesOrg[0]);
        	ZM_SalesOrgSummaryController con = new ZM_SalesOrgSummaryController(objController);
        	con.changeData();
            con.strZoneNrSOS='601';
            con.ZoneSalesOrg();
            con.starCount(5);
            con.saveAsPDF();
            con.saveAsDraft();
            system.assertEquals(con.lstSalesOrgSummary.size(),1);
            con.getOmniturePageName();                
        }
        
        Test.StopTest();       
    }
    
    //---------------------------------------------------------------------------
    // Method Name  : createSalesOrgSummary
    // Description  : Create and Insert object : Sales_Org_Summary__c
    //---------------------------------------------------------------------------
    public static Sales_Org_Summary__c createSalesOrgSummary(String ownerId, String zoneManagerId,
    									String slsDescTxt, String oprCampaignNumber, boolean isInsert) {
    										   	
    	Sales_Org_Summary__c salesOrgSummary = new Sales_Org_Summary__c (OwnerId = ownerId, 
										    	ZONE_MGR__c=zoneManagerId, 
										    	ACTV_REP_CNT__c=300, 
										    	UPR_CNT__c=8, 
										    	SLS_ORG_DESC_TXT__c=slsDescTxt, 
										    	OPERTNL_CMPGN_NR__c=oprCampaignNumber, 
										    	FLD_SLS_CMPGN_NR__c = oprCampaignNumber,  
										    	TITLD_STF_CNT__c=8,  
										    	RTURN_NET_SLS_PLAN_SPPY_AMT__c=1550.00, 
										    	TITL_0_STF_CNT__c=8,  
										    	UPR_DIV_RNK_CNT__c=100, 
										    	RNSTMT_DIV_RNK__c=100, 
										    	UPR_PLAN_SPPY_CNT__c=9,
										    	RMOVL_PLAN_CNT__c=6, 
										    	LOA_1_6_NET_SLS_DIV_RNK__c=100, 
										    	RTURN_NET_SLS_AMT__c=1500.00, 
										    	RMOVL_SPPY_CNT__c=8, 
										    	LOA_1_6_NET_SLS_PLAN_SPPY_AMT__c=1000.00, 
										    	RMOVL_PLAN_SPPY_CNT__c=8,    
										    	NET_SLS_SPPY_AMT__c=1555000.00, 
										    	LOA_1_6_NET_SLS_SPPY_AMT__c=1000.00, 
										    	RNSTMT_PLAN_CNT__c=5, 
										    	RMOVL_CNT__c=9, 
										    	TITLD_STF_DIV_RNK__c=100,   
										    	RNSTMT_CNT__c=2,   
										    	ACTV_REP_PLAN_SPPY_CNT__c=1500, 
										    	NET_SLS_DIV_RNK__c=100, 
										    	TITL_0_STF_PLAN_SPPY_CNT__c=9,  
										    	APPT_CNT__c=9, TITL_0_STF_PLAN_CNT__c=9, 
										    	TITL_0_STF_DIV_RNK__c=100, 
										    	LOA_1_6_NET_SLS_AMT__c=30000.00,  
										    	  UPR_PLAN_CNT__c=9, 
										    	  ACTV_REP_DIV_RNK__c=100,
										    	  RNSTMT_SPPY_CNT__c=7, 
										    	  LOA1_NET_SLS_DIV_RNK__c=100, 
										    	  ACTV_REP_SPPY_CNT__c=1600, 
										    	  LOA1_NET_SLS_AMT__c=1000.00,  
										    	  RMOVL_DIV_RNK__c=100, 
										    	  LOA1_NET_SLS_SPPY_AMT__c=1000.00, 
										    	  NET_SLS_PLAN_SPPY_AMT__c=1555000.00, 
										    	  LOA1_NET_SLS_PLAN_SPPY_AMT__c=1000.00, 
										    	  TITLD_STF_SPPY_CNT__c=9, 
										    	  TITL_0_STF_SPPY_CNT__c=9,  
										    	  APPT_DIV_RNK__c=100, 
										    	  UPR_SPPY_CNT__c=9, 
										    	  APPT_PLAN_CNT__c=12, 
										    	  LOA_1_6_NET_SLS_PLAN_AMT__c=322000.00, 
										    	  RTURN_NET_SLS_DIV_RNK__c=100, 
										    	  Analysis_Done__c=false, 
										    	  RTURN_NET_SLS_SPPY_AMT__c=1550.00,
										    	  APPT_PLAN_SPPY_CNT__c=15, 
										    	  NET_SLS_PLAN_AMT__c=500000.00,  
										    	  RNSTMT_PLAN_SPPY_CNT__c=7, 
										    	  APPT_SPPY_CNT__c=15, 
										    	  ACTV_REP_PLAN_CNT__c=200, 
										    	  LOA1_NET_SLS_PLAN_AMT__c=100000.00,
										    	  TITLD_STF_PLAN_SPPY_CNT__c=9, 
										    	  RTURN_NET_SLS_PLAN_AMT__c=1500.00, 
										    	  TITLD_STF_PLAN_CNT__c=9); 
    	if (isInsert) {
    		insert salesOrgSummary;
    	}
    	
    	return salesOrgSummary;
    }
}